version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable-all: false

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  max-same-issues: 50
