// factory-run is the RFC-201 §5 generation factory: it generates seeded query
// candidates, executes them against a real FoundationDB through the production
// SQL path, blesses the ones every oracle agrees on, deduplicates them against
// the corpus already committed, and WRITES the survivors into
// pkg/relational/conformance/factorycorpus/testdata as permanent suite content.
//
// Generated tests are committed, not regenerated. A frozen expectation keeps
// testing the engine when the generator, the oracles and the Java server are
// broken or gone; it bisects with git; and it turns oracle agreement — a fact
// about one moment — into a regression pin, a permanent one.
//
// Run a batch:
//
//	bazelisk run //cmd/factory-run -- -seeds 400 -quota 200 -date 2026-07-31
//
// Cross-engine blessing needs a reachable Java conformance server:
//
//	bazelisk run //conformance:conformance_server        # in another terminal
//	bazelisk run //cmd/factory-run -- -java-url http://127.0.0.1:PORT
//
// Without -java-url the batch is blessed by the metamorphic oracles alone and
// every emitted file says so in its header — honest, weaker, and upgradeable
// by a later run that can reach a server.
//
// Exit codes: 0 = batch complete, no oracle disagreed; 1 = at least one ORACLE
// DISAGREEMENT (a potential engine bug, persisted under -findings); 2 = INFRA
// failure; 3 = the batch committed nothing, which is a broken pipeline rather
// than a quiet success.
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"sort"
	"time"

	"fdb.dev/pkg/relational/conformance/factory"
	"fdb.dev/pkg/relational/conformance/factorycorpus"
	foundationdbtc "fdb.dev/pkg/testcontainers/foundationdb"

	_ "fdb.dev/pkg/relational/sqldriver"
)

const (
	exitOK       = 0
	exitFindings = 1
	exitInfra    = 2
	exitEmpty    = 3
)

func main() {
	cfg := config{}
	flag.Uint64Var(&cfg.seeds, "seeds", 400, "number of seeds to sweep")
	flag.Uint64Var(&cfg.seedStart, "seed-start", 1, "first seed")
	flag.IntVar(&cfg.quota, "quota", 1000, "maximum scenarios committed by this batch (RFC-201 §5.2 keeps a batch PR reviewable)")
	flag.StringVar(&cfg.out, "out", "pkg/relational/conformance/factorycorpus/testdata", "corpus directory to write scenarios into")
	flag.StringVar(&cfg.findings, "findings", "factory-findings", "directory oracle disagreements are persisted into")
	flag.StringVar(&cfg.manifest, "manifest", "factory-manifest.json", "path for the run's batch manifest")
	flag.StringVar(&cfg.date, "date", "", "batch date YYYY-MM-DD, stamped into every header (required: generation must never read the clock)")
	flag.StringVar(&cfg.javaURL, "java-url", "", "base URL of a running Java conformance server; empty = metamorphic blessing only")
	flag.BoolVar(&cfg.updateCensus, "update-census", true, "rewrite the corpus census baseline after the batch")
	flag.Parse()
	os.Exit(run(cfg))
}

type config struct {
	seeds, seedStart uint64
	quota            int
	out, findings    string
	manifest, date   string
	javaURL          string
	updateCensus     bool
}

func run(cfg config) int {
	// §5.4: generation never uses wall-clock. The date is an INPUT so a
	// committed file can be regenerated byte-identically, which is exactly
	// what TestFactoryDeterminism checks — defaulting it to time.Now() here
	// would make every file unreproducible the day after it was written.
	if cfg.date == "" {
		fmt.Fprintln(os.Stderr, "INFRA: -date is required; generation must not read the clock (RFC-201 §5.4)")
		return exitInfra
	}
	if _, err := time.Parse("2006-01-02", cfg.date); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: -date %q is not YYYY-MM-DD: %v\n", cfg.date, err)
		return exitInfra
	}
	if err := os.MkdirAll(cfg.out, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: corpus dir: %v\n", err)
		return exitInfra
	}

	startCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	// A note for whoever wires up the Java leg (-java-url), because this cost
	// an hour to learn: the JVM's libfdb_c cannot reach a testcontainer through
	// a DNAT-mapped port — it aborts with `pkt.canonicalRemotePort ==
	// peerAddress.port failed`. The conformance suite's answer is
	// foundationdbtc.WithDirectIP(), which hands out the bridge-IP cluster file
	// instead. That was tried here and did NOT complete either (the client
	// stopped crashing and started hanging), so the option is deliberately NOT
	// set: an unvalidated container change carrying a comment that claims a
	// benefit nobody observed is worse than no change. Whoever gets the leg
	// working should set it here with the working configuration measured.
	container, err := foundationdbtc.Run(startCtx, "")
	cancel()
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: FDB container: %v\n", err)
		return exitInfra
	}
	defer container.Terminate(context.Background()) //nolint:errcheck

	ctx := context.Background()
	clusterContent, err := container.ClusterFile(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: cluster file: %v\n", err)
		return exitInfra
	}
	tmp, err := os.CreateTemp("", "factory-run-*.cluster")
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: temp file: %v\n", err)
		return exitInfra
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(clusterContent); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write cluster file: %v\n", err)
		return exitInfra
	}
	tmp.Close()
	clusterFile := tmp.Name()

	const dbPath = "/factoryrun"
	setupDB, err := sql.Open("fdbsql", fmt.Sprintf("fdbsql://%s?cluster_file=%s", dbPath, clusterFile))
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: open: %v\n", err)
		return exitInfra
	}
	defer setupDB.Close()
	if _, err := setupDB.ExecContext(ctx, "CREATE DATABASE "+dbPath); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: create database: %v\n", err)
		return exitInfra
	}

	var java factory.CrossEngine
	blessingMode := "metamorphic"
	if cfg.javaURL != "" {
		leg := newJavaLeg(cfg.javaURL, clusterContent)
		if leg == nil {
			// Assigning a typed nil into the interface would leave `java !=
			// nil` true and every candidate would panic on the first call.
			fmt.Fprintln(os.Stderr, "INFRA: the plandiff HTTP runner does not implement SetupRunner; cannot bless cross-engine")
			return exitInfra
		}
		java = leg
		blessingMode = "cross-engine"
	}

	batch, err := factory.NewBatch(cfg.out, cfg.quota)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: read existing corpus: %v\n", err)
		return exitInfra
	}

	var findings []*factory.Finding
	sweep := factory.Sweep{
		SetupDB:     setupDB,
		DBPath:      dbPath,
		ClusterFile: clusterFile,
		Java:        java,
		Date:        cfg.date,
	}
	for seed := cfg.seedStart; seed < cfg.seedStart+cfg.seeds; seed++ {
		if batch.Full() {
			break
		}
		outcomes, err := sweep.RunSeed(ctx, seed, batch)
		if err != nil {
			fmt.Fprintf(os.Stderr, "INFRA: seed %d: %v\n", seed, err)
			return exitInfra
		}
		for _, o := range outcomes {
			findings = append(findings, o.Findings...)
		}
		if (seed-cfg.seedStart+1)%25 == 0 {
			fmt.Printf("  seed %d: committed %d\n", seed, batch.Committed())
		}
	}

	manifest, err := batch.Finish(cfg.seedStart, cfg.seeds, cfg.date, blessingMode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: finish batch: %v\n", err)
		return exitInfra
	}
	if err := factory.WriteManifest(cfg.manifest, manifest); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write manifest: %v\n", err)
		return exitInfra
	}
	if err := factory.WriteFindings(cfg.findings, findings); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write findings: %v\n", err)
		return exitInfra
	}
	if cfg.updateCensus {
		// The baseline is rewritten from the FILES the batch left on disk, via
		// the same loader CI uses — never from the batch's own bookkeeping,
		// which would agree with itself even if nothing had been written.
		data, err := factorycorpus.RenderCensus(manifest.Census)
		if err == nil {
			err = os.WriteFile(censusPath(cfg.out), data, 0o644)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "INFRA: write census baseline: %v\n", err)
			return exitInfra
		}
	}

	report(manifest)

	// The second-plan oracle's run-level floor (RFC-201 §8.5). Its per-case
	// precondition is plan inequality, which degrades silently: if
	// DISABLED_PLANNER_RULES stopped being honoured, every case would find the
	// two plans identical, every case would skip, and the run would report a
	// clean green with the oracle switched off. A run that executed second
	// plans and kept NONE of them is that state.
	if o := manifest.Oracles; o.SecondPlanSkipped > 0 && o.SecondPlanKept == 0 {
		fmt.Fprintf(os.Stderr, "\nINFRA: the second-plan oracle never saw two different plans in %d executions. "+
			"DISABLED_PLANNER_RULES=[MatchLeafRule] is being accepted and ignored, or no generated query "+
			"reaches an index — either way the oracle is dark and nothing it blessed is worth its label.\n",
			o.SecondPlanSkipped)
		return exitInfra
	}

	switch {
	case len(findings) > 0:
		fmt.Fprintf(os.Stderr, "\n%d ORACLE DISAGREEMENTS persisted under %s — each is a potential engine bug\n", len(findings), cfg.findings)
		return exitFindings
	case manifest.Committed == 0:
		fmt.Fprintln(os.Stderr, "\nbatch committed nothing: a factory run that writes no test is a broken pipeline, not a quiet success")
		return exitEmpty
	}
	return exitOK
}

func censusPath(corpusDir string) string {
	// The baseline sits beside the package, not inside testdata, so the
	// corpus glob cannot pick it up as a scenario.
	return corpusDir + "/../" + factorycorpus.CensusBaselinePath
}

func report(m factory.Manifest) {
	fmt.Printf("\nRFC-201 factory batch %s (%s, seeds %d..%d)\n", m.Date, m.Generator, m.SeedStart, m.SeedStart+m.Seeds-1)
	fmt.Printf("  candidates generated %d, executed %d\n", m.CandidatesGen, m.CandidatesRun)
	fmt.Printf("  blessed %d, committed %d, dedup-rejected %d, points covered %d\n",
		m.Blessed, m.Committed, m.DedupRejected, m.DedupPoints)
	fmt.Printf("  blessing mode: %s %v\n", m.BlessingMode, m.Blessings)
	fmt.Printf("  oracles: tlp checked=%d violations=%d | second-plan kept=%d skipped=%d violations=%d | cross-engine kept=%d violations=%d\n",
		m.Oracles.TLPChecked, m.Oracles.TLPViolations,
		m.Oracles.SecondPlanKept, m.Oracles.SecondPlanSkipped, m.Oracles.SecondPlanViolations,
		m.Oracles.CrossEngineKept, m.Oracles.CrossEngineViolations)
	fmt.Println("  counted skips:")
	keys := make([]string, 0, len(m.SkipsByReason))
	for k := range m.SkipsByReason {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Printf("    %-40s %d\n", k, m.SkipsByReason[k])
	}
	fmt.Printf("  census after: %d scenarios, %d tests, %d feature vectors\n",
		m.Census.Scenarios, m.Census.Tests, len(m.Census.ByFeature))
}
