// factory-run is the RFC-201 §5 generation factory: it generates seeded query
// candidates, executes them against a real FoundationDB through the production
// SQL path, blesses the ones every oracle agrees on, deduplicates them against
// the corpus already committed, and WRITES the survivors into
// pkg/relational/conformance/factorycorpus/testdata as permanent suite content.
//
// Generated tests are committed, not regenerated. A frozen expectation keeps
// testing the engine when the generator, the oracles and the Java server are
// broken or gone; it bisects with git; and it turns oracle agreement — a fact
// about one moment — into a regression pin, a permanent one.
//
// Run a batch:
//
//	bazelisk run //cmd/factory-run -- -seeds 400 -quota 200 -date 2026-07-31
//
// Cross-engine blessing needs a reachable Java conformance server:
//
//	bazelisk run //conformance:conformance_server        # in another terminal
//	bazelisk run //cmd/factory-run -- -java-url http://127.0.0.1:PORT
//
// Without -java-url the batch is blessed by the metamorphic oracles alone and
// every emitted file says so in its header — honest, weaker, and upgradeable
// by a later run that can reach a server.
//
// Exit codes: 0 = batch complete, no oracle disagreed; 1 = at least one ORACLE
// DISAGREEMENT (a potential engine bug, persisted under -findings); 2 = INFRA
// failure; 3 = the batch committed nothing, which is a broken pipeline rather
// than a quiet success.
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"os"
	"sort"
	"time"

	"fdb.dev/pkg/relational/conformance/factory"
	"fdb.dev/pkg/relational/conformance/factorycorpus"
	foundationdbtc "fdb.dev/pkg/testcontainers/foundationdb"

	_ "fdb.dev/pkg/relational/sqldriver"
)

const (
	exitOK       = 0
	exitFindings = 1
	exitInfra    = 2
	exitEmpty    = 3
)

func main() {
	cfg := config{}
	flag.Uint64Var(&cfg.seeds, "seeds", 400, "number of seeds to sweep")
	flag.Uint64Var(&cfg.seedStart, "seed-start", 1, "first seed")
	flag.IntVar(&cfg.quota, "quota", 1000, "maximum scenarios committed by this batch (RFC-201 §5.2 keeps a batch PR reviewable)")
	flag.StringVar(&cfg.out, "out", "pkg/relational/conformance/factorycorpus/testdata", "corpus directory to write scenarios into")
	flag.StringVar(&cfg.findings, "findings", "factory-findings", "directory oracle disagreements are persisted into")
	flag.StringVar(&cfg.manifest, "manifest", "factory-manifest.json", "path for the run's batch manifest")
	flag.StringVar(&cfg.prBody, "pr-body", "factory-pr-body.md",
		"path for the batch PR body: the manifest's numbers WITHOUT the per-scenario census maps, "+
			"which are whole-corpus state and put the raw manifest an order of magnitude past GitHub's 65536-character body limit")
	flag.StringVar(&cfg.runURL, "run-url", "", "workflow run URL, linked from the PR body as where the full manifest artifact lives")
	flag.StringVar(&cfg.date, "date", "", "batch date YYYY-MM-DD, stamped into every header (required: generation must never read the clock)")
	flag.StringVar(&cfg.javaURL, "java-url", "", "base URL of a running Java conformance server; empty = metamorphic blessing only")
	flag.StringVar(&cfg.retirementLedger, "retirement-ledger", "",
		"reviewed corpus-retirement ledger authorizing one exact non-additive corpus transition; requires -update-census")
	flag.BoolVar(&cfg.updateCensus, "update-census", false,
		"rewrite the committed census baseline to this measured corpus; a decrease or content replacement requires -retirement-ledger. OFF by default: the baseline is otherwise VERIFIED, "+
			"and a producer that rewrites its own standard every run has a ratchet that cannot fire")
	flag.Parse()
	os.Exit(run(cfg))
}

type config struct {
	seeds, seedStart uint64
	quota            int
	out, findings    string
	manifest, date   string
	prBody, runURL   string
	javaURL          string
	retirementLedger string
	updateCensus     bool
}

func run(cfg config) int {
	// §5.4: generation never uses wall-clock. The date is an INPUT so a
	// committed file can be regenerated byte-identically, which is exactly
	// what TestFactoryDeterminism checks — defaulting it to time.Now() here
	// would make every file unreproducible the day after it was written.
	if cfg.date == "" {
		fmt.Fprintln(os.Stderr, "INFRA: -date is required; generation must not read the clock (RFC-201 §5.4)")
		return exitInfra
	}
	if _, err := time.Parse("2006-01-02", cfg.date); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: -date %q is not YYYY-MM-DD: %v\n", cfg.date, err)
		return exitInfra
	}
	if err := os.MkdirAll(cfg.out, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: corpus dir: %v\n", err)
		return exitInfra
	}

	startCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	// A note for whoever wires up the Java leg (-java-url), because this cost
	// an hour to learn: the JVM's libfdb_c cannot reach a testcontainer through
	// a DNAT-mapped port — it aborts with `pkt.canonicalRemotePort ==
	// peerAddress.port failed`. The conformance suite's answer is
	// foundationdbtc.WithDirectIP(), which hands out the bridge-IP cluster file
	// instead. That was tried here and did NOT complete either (the client
	// stopped crashing and started hanging), so the option is deliberately NOT
	// set: an unvalidated container change carrying a comment that claims a
	// benefit nobody observed is worse than no change. Whoever gets the leg
	// working should set it here with the working configuration measured.
	container, err := foundationdbtc.Run(startCtx, "")
	cancel()
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: FDB container: %v\n", err)
		return exitInfra
	}
	defer container.Terminate(context.Background()) //nolint:errcheck

	ctx := context.Background()
	clusterContent, err := container.ClusterFile(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: cluster file: %v\n", err)
		return exitInfra
	}
	tmp, err := os.CreateTemp("", "factory-run-*.cluster")
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: temp file: %v\n", err)
		return exitInfra
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(clusterContent); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write cluster file: %v\n", err)
		return exitInfra
	}
	tmp.Close()
	clusterFile := tmp.Name()

	const dbPath = "/factoryrun"
	setupDB, err := sql.Open("fdbsql", fmt.Sprintf("fdbsql://%s?cluster_file=%s", dbPath, clusterFile))
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: open: %v\n", err)
		return exitInfra
	}
	defer setupDB.Close()
	if _, err := setupDB.ExecContext(ctx, "CREATE DATABASE "+dbPath); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: create database: %v\n", err)
		return exitInfra
	}

	var java factory.CrossEngine
	blessingMode := "metamorphic"
	if cfg.javaURL != "" {
		leg := newJavaLeg(cfg.javaURL, clusterContent)
		if leg == nil {
			// Assigning a typed nil into the interface would leave `java !=
			// nil` true and every candidate would panic on the first call.
			fmt.Fprintln(os.Stderr, "INFRA: the plandiff HTTP runner does not implement SetupRunner; cannot bless cross-engine")
			return exitInfra
		}
		java = leg
		blessingMode = "cross-engine"
	}

	batch, err := factory.NewBatch(cfg.out, cfg.quota)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: read existing corpus: %v\n", err)
		return exitInfra
	}

	var findings []*factory.Finding
	sweep := factory.Sweep{
		SetupDB:     setupDB,
		DBPath:      dbPath,
		ClusterFile: clusterFile,
		Java:        java,
		Date:        cfg.date,
	}
	// A sweep failure is carried out of the loop rather than returned from
	// inside it, so that every path with findings in hand leaves through the
	// one place that persists them. A seed that fails on seed 300 has 299
	// seeds' worth of disagreements in memory and they are no less
	// irreplaceable than the ones a completed sweep produces.
	var sweepErr error
	for seed := cfg.seedStart; seed < cfg.seedStart+cfg.seeds; seed++ {
		if batch.Full() {
			break
		}
		outcomes, err := sweep.RunSeed(ctx, seed, batch)
		for _, o := range outcomes {
			findings = append(findings, o.Findings...)
		}
		if err != nil {
			sweepErr = fmt.Errorf("seed %d: %w", seed, err)
			break
		}
		if (seed-cfg.seedStart+1)%25 == 0 {
			fmt.Printf("  seed %d: committed %d\n", seed, batch.Committed())
		}
	}

	manifest, code := persist(cfg, batch, findings, blessingMode, sweepErr)
	if code != exitOK {
		return code
	}

	report(manifest)

	code, why := batchExit(manifest, findings, cfg.findings)
	if why != "" {
		fmt.Fprintln(os.Stderr, "\n"+why)
	}
	return code
}

// batchExit is the run's whole decision procedure: given what the batch
// measured and what it found, which exit code does the run carry, and why.
//
// It is a pure function over the manifest and the findings because that is the
// only way it can be tested. Buried inside run() it was reachable only through
// a real FDB container and a real sweep, so the four exit codes and the
// went-dark floor — the entire contract the nightly's automation reads — had
// no coverage at all. A floor nobody tests is a floor that silently stops
// firing, which is the same failure class it exists to catch.
//
// findingsDir appears only in the message; the decision does not depend on it.
func batchExit(m factory.Manifest, findings []*factory.Finding, findingsDir string) (int, string) {
	// The second-plan oracle's run-level floor (RFC-201 §8.5) comes FIRST, and
	// deliberately outranks the findings. Its per-case precondition is plan
	// inequality, which degrades silently: if DISABLED_PLANNER_RULES stopped
	// being honoured, every case would find the two plans identical, every case
	// would skip, and the run would report a clean green with the oracle
	// switched off. A run that executed second plans and kept NONE of them is
	// that state — and a run in that state cannot be trusted to have classified
	// its findings correctly either, so "the instrument is broken" is the
	// louder answer than "here are its readings".
	if o := m.Oracles; o.SecondPlanSkipped > 0 && o.SecondPlanKept == 0 {
		return exitInfra, fmt.Sprintf("INFRA: the second-plan oracle never saw two different plans in %d executions. "+
			"DISABLED_PLANNER_RULES=[MatchLeafRule] is being accepted and ignored, or no generated query "+
			"reaches an index — either way the oracle is dark and nothing it blessed is worth its label.",
			o.SecondPlanSkipped)
	}
	switch {
	case len(findings) > 0:
		return exitFindings, fmt.Sprintf("%d ORACLE DISAGREEMENTS persisted under %s — each is a potential engine bug",
			len(findings), findingsDir)
	case m.Committed == 0:
		return exitEmpty, "batch committed nothing: a factory run that writes no test is a broken pipeline, not a quiet success"
	}
	return exitOK, ""
}

// persist writes the run's outputs, FINDINGS FIRST, and returns the manifest
// plus exitOK or the infra exit code. sweepErr is the failure that ended the
// sweep early, or nil.
//
// The order is the whole point of the function. An oracle disagreement is the
// loudest signal this system produces — a candidate where two independent
// authorities disagreed about the rows, i.e. a probable engine bug — and it
// exists only in memory until it is written. Everything else here can fail:
// Finish re-reads the corpus directory through the loader, which treats an
// empty directory as an error (a gate over an empty corpus passes vacuously),
// so the very first bootstrap run into a fresh directory takes the infra exit
// path. Writing the manifest can fail on a bad path or a full disk. And the
// sweep itself can die mid-run with hundreds of seeds' findings already in
// hand. If any of that is handled before the findings are on disk, a run that
// found a real bug reports the failure and DESTROYS the evidence, and the bug
// is only rediscovered if some future run happens to draw the same seed.
//
// This is therefore the single exit for every path that has findings in hand,
// which is why the sweep's error arrives as an argument rather than as an
// early return at the call site. Nothing downstream needs the findings
// unwritten, so there is no cost to paying for durability first.
func persist(cfg config, batch *factory.Batch, findings []*factory.Finding, blessingMode string, sweepErr error) (factory.Manifest, int) {
	if err := factory.WriteFindings(cfg.findings, findings); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write findings: %v\n", err)
		return factory.Manifest{}, exitInfra
	}
	if sweepErr != nil {
		fmt.Fprintf(os.Stderr, "INFRA: %v\n", sweepErr)
		return factory.Manifest{}, exitInfra
	}
	if cfg.retirementLedger != "" && !cfg.updateCensus {
		fmt.Fprintln(os.Stderr, "INFRA: -retirement-ledger requires -update-census; the ledger was not applied")
		return factory.Manifest{}, exitInfra
	}
	manifest, err := batch.Finish(cfg.seedStart, cfg.seeds, cfg.date, blessingMode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: finish batch: %v\n", err)
		return manifest, exitInfra
	}
	if err := factory.WriteManifest(cfg.manifest, manifest); err != nil {
		fmt.Fprintf(os.Stderr, "INFRA: write manifest: %v\n", err)
		return manifest, exitInfra
	}
	// The PR body is written HERE, next to the manifest, rather than assembled
	// in the workflow: the shell had no way to drop the two per-scenario census
	// maps short of a jq dependency this repo does not have, so it inlined the
	// whole manifest and the PR call failed on GitHub's body limit — after the
	// branch was already committed and pushed. A typed renderer with tests is
	// the thing that can promise a bounded body; a heredoc cannot.
	if cfg.prBody != "" {
		if err := os.WriteFile(cfg.prBody, []byte(manifest.SummaryMarkdown(cfg.runURL)), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "INFRA: write PR body: %v\n", err)
			return manifest, exitInfra
		}
	}
	// THE RATCHET IS VERIFIED BY DEFAULT AND REWRITTEN ONLY ON REQUEST.
	//
	// A producer that rewrites its own baseline every run makes the ratchet
	// green by construction: whatever the batch produced becomes the standard
	// the batch is measured against, so no run can ever fail it, and the
	// automated lane — which commits the result — never sees a shrink. That is
	// a gate that cannot fire, which is worse than no gate, because the census
	// line in the PR still reads like evidence.
	//
	// So the default path CHECKS the corpus against the committed baseline and
	// fails on a downgrade. Rewriting the baseline is a deliberate act with a
	// flag, and its diff is then visible in the batch PR as the ratchet delta
	// — which is the only place authority movement is visible at all. A shrink
	// or exact-byte replacement additionally needs a reviewed ledger that binds
	// both corpus endpoints. This producer has only the logical census baseline,
	// so the companion Git-history gate compares raw trusted/HEAD trees and
	// rejects a no-ledger same-census replacement that cannot be inferred here.
	committed, err := factorycorpus.LoadCensus(censusPath(cfg.out))
	switch {
	case err != nil && !cfg.updateCensus:
		fmt.Fprintf(os.Stderr, "INFRA: read committed census baseline: %v\n"+
			"(bootstrapping a new corpus? re-run with -update-census to write the first baseline)\n", err)
		return manifest, exitInfra
	case err != nil && cfg.retirementLedger != "":
		fmt.Fprintf(os.Stderr, "INFRA: retirement ledger cannot authorize a transition without a readable before baseline: %v\n", err)
		return manifest, exitInfra
	case err == nil:
		shrinks := factorycorpus.CheckRatchet(committed, manifest.Census)
		if cfg.retirementLedger != "" {
			ledger, ledgerErr := factorycorpus.LoadRetirementLedger(cfg.retirementLedger)
			if ledgerErr == nil && ledger.Date != manifest.Date {
				ledgerErr = fmt.Errorf("ledger date %s does not match batch date %s", ledger.Date, manifest.Date)
			}
			if ledgerErr == nil && !hasNonAdditiveRetirementChange(ledger) {
				ledgerErr = fmt.Errorf("ledger has only added entries; additive growth needs no retirement authorization")
			}
			if ledgerErr == nil {
				ledgerErr = factorycorpus.ValidateRetirementTransition(ledger, committed, manifest.Census, cfg.out)
			}
			if ledgerErr != nil {
				fmt.Fprintf(os.Stderr, "INFRA: retirement ledger did not authorize this corpus transition: %v\n", ledgerErr)
				return manifest, exitInfra
			}
			fmt.Fprintf(os.Stderr, "ACKNOWLEDGED corpus retirement (%s): %s\n", ledger.RFC, ledger.Reason)
			break
		}
		if len(shrinks) > 0 {
			fmt.Fprintln(os.Stderr, "\nINFRA: this batch SHRANK the committed corpus:")
			for _, s := range shrinks {
				fmt.Fprintf(os.Stderr, "  %s\n", s)
			}
			return manifest, exitInfra
		}
	}
	if cfg.updateCensus {
		// Rendered from the FILES the batch left on disk, via the same loader
		// CI uses — never from the batch's own bookkeeping, which would agree
		// with itself even if nothing had been written.
		data, err := factorycorpus.RenderCensus(manifest.Census)
		if err == nil {
			err = os.WriteFile(censusPath(cfg.out), data, 0o644)
		}
		if err != nil {
			fmt.Fprintf(os.Stderr, "INFRA: write census baseline: %v\n", err)
			return manifest, exitInfra
		}
	}
	return manifest, exitOK
}

func hasNonAdditiveRetirementChange(ledger factorycorpus.RetirementLedger) bool {
	for _, change := range ledger.Changes {
		if change.Disposition == factorycorpus.DispositionRetired ||
			change.Disposition == factorycorpus.DispositionReplaced {
			return true
		}
	}
	return false
}

func censusPath(corpusDir string) string {
	// The baseline sits beside the package, not inside testdata, so the
	// corpus glob cannot pick it up as a scenario.
	return corpusDir + "/../" + factorycorpus.CensusBaselinePath
}

func report(m factory.Manifest) {
	fmt.Printf("\nRFC-201 factory batch %s (%s, seeds %d..%d)\n", m.Date, m.Generator, m.SeedStart, m.SeedStart+m.Seeds-1)
	fmt.Printf("  candidates generated %d, executed %d\n", m.CandidatesGen, m.CandidatesRun)
	fmt.Printf("  blessed %d, committed %d, dedup-rejected %d, points covered %d\n",
		m.Blessed, m.Committed, m.DedupRejected, m.DedupPoints)
	if m.NameCollisions > 0 {
		fmt.Printf("  NAME COLLISIONS %d: that many blessed candidates would have OVERWRITTEN a committed\n"+
			"    scenario with different content. The write was refused. The dedup key moved and the file\n"+
			"    name did not, which is what a planner change looks like from here.\n", m.NameCollisions)
	}
	fmt.Printf("  blessing mode: %s %v\n", m.BlessingMode, m.Blessings)
	if len(m.Exemptions) > 0 {
		// Printed unconditionally when the ledger is non-empty, not only when
		// something used it: the set of available exemptions is what a reader
		// needs to judge the authority mix above, and a weakening that only
		// shows up when it fires is one nobody audits until it already has.
		fmt.Println("  structural exemptions (TLP-only blessing permitted):")
		for _, e := range m.Exemptions {
			fmt.Printf("    %s\n", e)
		}
		fmt.Printf("    blessed under them: %d %v\n", m.Oracles.TLPOnlyBlessed, m.BlessedByFamily)
	}
	fmt.Printf("  oracles: tlp checked=%d violations=%d | second-plan kept=%d skipped=%d violations=%d | cross-engine kept=%d violations=%d\n",
		m.Oracles.TLPChecked, m.Oracles.TLPViolations,
		m.Oracles.SecondPlanKept, m.Oracles.SecondPlanSkipped, m.Oracles.SecondPlanViolations,
		m.Oracles.CrossEngineKept, m.Oracles.CrossEngineViolations)
	fmt.Println("  counted skips:")
	keys := make([]string, 0, len(m.SkipsByReason))
	for k := range m.SkipsByReason {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Printf("    %-40s %d\n", k, m.SkipsByReason[k])
	}
	fmt.Printf("  census after: %d scenarios, %d tests, %d feature vectors\n",
		m.Census.Scenarios, m.Census.Tests, len(m.Census.ByFeature))
}
