package factorycorpus

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"fdb.dev/pkg/relational/conformance/yamsql"
)

// DedupKeyOf is the corpus's primary key: a digest over the feature vector and
// the plan shape. Neither half is sufficient alone — the feature vector says
// what the query ASKED (two different plans for the same shape are two
// different tests) and the plan shape says what the planner DID (explaindiff's
// ShapeOf is type-only, so a scan filtered on `a` and one filtered on `b`
// collapse to the same shape). A candidate is committed only if this key is
// new.
func DedupKeyOf(featureVector string, planShape string) string {
	h := sha256.New()
	h.Write([]byte(featureVector))
	h.Write([]byte{0})
	h.Write([]byte(planShape))
	return hex.EncodeToString(h.Sum(nil))[:16]
}

// ShapeDigest folds a plan shape rendering (explaindiff.ShapeOf output) into
// the fixed-width form the header carries. The full rendering is many lines
// and would dominate the header; the digest is stable because the rendering is
// (it holds Go type names and tree positions, nothing versioned).
func ShapeDigest(shape []string) string {
	h := sha256.New()
	for _, line := range shape {
		h.Write([]byte(line))
		h.Write([]byte{'\n'})
	}
	return hex.EncodeToString(h.Sum(nil))[:16]
}

// MarshalFamily renders one family's scenarios as the bytes of its committed
// `.yamsql` file.
//
// The emitted file is genuine yamsql — parseable by the javayamsql parser and
// within the subset Java's own yaml-tests runner accepts, which is what makes
// cross-engine blessing literal: Java can execute the exact committed file.
// Provenance lives in the comment header (the one extension yamsql tolerates
// freely); each scenario is a (schema_template, setup, test_block) document
// triple whose `connect:` index names its own schema registration, so the
// whole file executes as one Java run and any single scenario executes alone
// after the loader rebases its connect index.
//
// The contract is BYTE-EXACT ROUND TRIPPING:
//
//	MarshalFamily(Load(MarshalFamily(entries))) == MarshalFamily(entries)
//
// Without it a re-bless (§5.3) produces a diff full of reformatting noise and
// the reader cannot see which expectation actually moved — which is the only
// thing a re-bless review is for. Scenario order inside the file is therefore
// derived, not positional: entries are sorted by (seed, query index,
// projection), so a nightly append lands in a deterministic place and
// re-emitting the whole family reproduces the file byte for byte.
func MarshalFamily(entries []*Scenario) ([]byte, error) {
	if len(entries) == 0 {
		return nil, fmt.Errorf("a family file with no scenarios asserts nothing")
	}
	family := FamilyOf(entries[0].Header.FeatureVector)
	sorted := make([]*Scenario, len(entries))
	copy(sorted, entries)
	sort.Slice(sorted, func(i, j int) bool {
		a, b := sorted[i].Header, sorted[j].Header
		if a.Seed != b.Seed {
			return a.Seed < b.Seed
		}
		if a.QueryIndex != b.QueryIndex {
			return a.QueryIndex < b.QueryIndex
		}
		return a.Projection < b.Projection
	})

	var b bytes.Buffer
	fileName := FamilyFileName(family)
	fmt.Fprintf(&b, "# %s\n#\n", fileName)
	for _, line := range []string{
		"GENERATED by the RFC-201 §5 generation factory — do not hand-edit.",
		"",
		"One committed .yamsql file per feature family (RFC-201 §5.7): every",
		"scenario below shares this file's family, and nightly batches append new",
		"scenarios here rather than minting new files. The file is genuine Java",
		"yaml-tests format — the Java runner can execute it verbatim.",
		"",
		"The result rows are FROZEN ORACLE OUTPUT, not an authored assertion:",
		"nobody predicted them, an oracle agreed with them. Editing a row by hand",
		"converts a proof into an opinion. When intended behaviour changes,",
		"re-bless through the factory in the same PR as the fix (RFC-201 §5.3) —",
		"never edit in place, and never mass-re-bless outside a behaviour-changing",
		"fix.",
	} {
		if line == "" {
			b.WriteString("#\n")
			continue
		}
		fmt.Fprintf(&b, "# %s\n", line)
	}
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# format-version: %d\n", FormatVersion)
	fmt.Fprintf(&b, "# family: %s\n", family)

	seenName := map[string]bool{}
	seenKey := map[string]string{}
	for i, e := range sorted {
		if got := FamilyOf(e.Header.FeatureVector); got != family {
			return nil, fmt.Errorf("%s: family %s does not match the file's %s", e.Header.Name, got, family)
		}
		if seenName[e.Header.Name] {
			return nil, fmt.Errorf("scenario %s appears twice in family %s", e.Header.Name, family)
		}
		seenName[e.Header.Name] = true
		if prev, dup := seenKey[e.Header.DedupKey]; dup {
			return nil, fmt.Errorf("%s and %s share dedup key %s: the same (feature vector, plan shape) point committed twice",
				prev, e.Header.Name, e.Header.DedupKey)
		}
		seenKey[e.Header.DedupKey] = e.Header.Name
		b.WriteString("#\n")
		b.WriteString(e.Header.Render())
		if err := marshalScenario(&b, e, i+1); err != nil {
			return nil, fmt.Errorf("%s: %w", e.Header.Name, err)
		}
	}
	return b.Bytes(), nil
}

// marshalScenario emits one scenario's document triple. connectIdx is the
// 1-based index of the scenario's schema_template registration within the
// whole file — Java resolves `connect: n` against the file-wide registration
// order, so the index is a property of the file, not of the scenario.
func marshalScenario(b *bytes.Buffer, e *Scenario, connectIdx int) error {
	s := e.Doc
	if e.Header.Name != s.Name {
		return fmt.Errorf("header name %q != scenario name %q", e.Header.Name, s.Name)
	}
	if s.SchemaTemplate == "" {
		return fmt.Errorf("schema_template is required")
	}
	if len(s.Setup) == 0 {
		return fmt.Errorf("a committed scenario with no setup freezes expectations over an empty table")
	}
	if len(s.Tests) == 0 {
		return fmt.Errorf("a committed scenario with no tests asserts nothing")
	}

	tmpl, err := sqlScalar(s.SchemaTemplate)
	if err != nil {
		return fmt.Errorf("schema_template: %w", err)
	}
	doc := &yaml.Node{Kind: yaml.MappingNode}
	appendKV(doc, "schema_template", tmpl)
	if err := encodeDoc(b, doc); err != nil {
		return err
	}

	steps := &yaml.Node{Kind: yaml.SequenceNode}
	for i, stmt := range s.Setup {
		n, err := sqlScalar(stmt)
		if err != nil {
			return fmt.Errorf("setup[%d]: %w", i, err)
		}
		step := &yaml.Node{Kind: yaml.MappingNode}
		appendKV(step, "query", n)
		steps.Content = append(steps.Content, step)
	}
	setup := &yaml.Node{Kind: yaml.MappingNode}
	appendKV(setup, "connect", intScalar(int64(connectIdx)))
	appendKV(setup, "steps", steps)
	doc = &yaml.Node{Kind: yaml.MappingNode}
	appendKV(doc, "setup", setup)
	if err := encodeDoc(b, doc); err != nil {
		return err
	}

	tests := &yaml.Node{Kind: yaml.SequenceNode}
	for i := range s.Tests {
		n, err := testNode(&s.Tests[i])
		if err != nil {
			return fmt.Errorf("tests[%d]: %w", i, err)
		}
		tests.Content = append(tests.Content, n)
	}
	tb := &yaml.Node{Kind: yaml.MappingNode}
	appendKV(tb, "name", strScalar(s.Name))
	// single_repetition_ordered: one execution per test, in file order, no
	// plan-cache pass. Repetition would re-run DML-free queries harmlessly but
	// triple the nightly's cost for no added assertion, and ordered execution
	// is what keeps a failure reproducible from its file position.
	appendKV(tb, "preset", &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: "single_repetition_ordered"})
	appendKV(tb, "connect", intScalar(int64(connectIdx)))
	appendKV(tb, "tests", tests)
	doc = &yaml.Node{Kind: yaml.MappingNode}
	appendKV(doc, "test_block", tb)
	return encodeDoc(b, doc)
}

func encodeDoc(b *bytes.Buffer, doc *yaml.Node) error {
	b.WriteString("---\n")
	enc := yaml.NewEncoder(b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return fmt.Errorf("encode: %w", err)
	}
	return enc.Close()
}

// testNode renders one test as the Java list form: the query command first,
// then its single result-consuming config.
func testNode(t *yamsql.Test) (*yaml.Node, error) {
	if t.Exec != "" {
		return nil, fmt.Errorf("exec must already be normalized into query by the caller")
	}
	if t.Query == "" {
		return nil, fmt.Errorf("query is empty")
	}
	if t.EffectiveErrorCode() != "" {
		// Nothing upstream produces one today (an engine rejection is a counted
		// skip, never a frozen expectation), so the arm is refused rather than
		// emitted untested. Java's `error:` config is the shape to emit when a
		// deliberate negative scenario is first blessed.
		return nil, fmt.Errorf("error expectations are not part of the committed factory corpus")
	}
	if strings.Contains(t.Query, "!!") {
		// `!!…!!` is the yamsql parameter-injection syntax; a query containing
		// it would be adapted, not executed verbatim.
		return nil, fmt.Errorf("query contains a `!!` parameter-injection delimiter")
	}
	q, err := sqlScalar(t.Query)
	if err != nil {
		return nil, fmt.Errorf("query: %w", err)
	}
	cmd := &yaml.Node{Kind: yaml.MappingNode}
	appendKV(cmd, "query", q)

	rows := &yaml.Node{Kind: yaml.SequenceNode}
	if len(t.Rows) == 0 {
		// An empty result set is a real, load-bearing expectation (the engine
		// returned nothing) and is spelled `result: []`.
		rows.Style = yaml.FlowStyle
	} else {
		if len(t.Columns) == 0 {
			return nil, fmt.Errorf("rows without column labels cannot be rendered as by-name cells")
		}
		if err := checkColumns(t.Columns); err != nil {
			return nil, err
		}
		for i, r := range t.Rows {
			if len(r) != len(t.Columns) {
				return nil, fmt.Errorf("rows[%d] has %d cells for %d columns", i, len(r), len(t.Columns))
			}
			row := &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle}
			for j, v := range r {
				n, err := valueScalar(v)
				if err != nil {
					return nil, fmt.Errorf("rows[%d][%d]: %w", i, j, err)
				}
				appendKV(row, t.Columns[j], n)
			}
			rows.Content = append(rows.Content, row)
		}
	}
	cfg := &yaml.Node{Kind: yaml.MappingNode}
	key := "result"
	if t.Unordered {
		key = "unorderedResult"
	}
	appendKV(cfg, key, rows)

	test := &yaml.Node{Kind: yaml.SequenceNode}
	test.Content = append(test.Content, cmd, cfg)
	return test, nil
}

// checkColumns enforces what by-name cells require of the labels: a shape the
// emitter can write as a plain YAML key, and case-insensitive uniqueness —
// Java resolves cell names with equalsIgnoreCase, so two labels differing only
// in case would both resolve to whichever column comes first.
//
// A query whose projection repeats a label cannot be committed in this form at
// all; `!pos` cells are the Java-supported fallback, to be wired up with the
// first real scenario that needs them rather than shipped untested.
func checkColumns(cols []string) error {
	seen := map[string]bool{}
	for _, c := range cols {
		if !plainKeyShape(c) {
			return fmt.Errorf("column label %q cannot be written as a plain YAML mapping key", c)
		}
		lc := strings.ToLower(c)
		if seen[lc] {
			return fmt.Errorf("column label %q repeats (case-insensitively); by-name cells would both resolve to the first occurrence", c)
		}
		seen[lc] = true
	}
	return nil
}

func plainKeyShape(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

func appendKV(m *yaml.Node, key string, val *yaml.Node) {
	m.Content = append(m.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: key},
		val)
}

func strScalar(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s, Style: yaml.DoubleQuotedStyle}
}

// sqlScalar renders a SQL statement as a literal block scalar (`|-`), the one
// YAML form that reproduces long text with no wrapping and no escaping.
//
// Two shapes cannot be spelled that way and are rejected rather than silently
// mangled: a line with trailing whitespace (a block scalar strips it on read)
// and a first line starting with a space (which needs an explicit indentation
// indicator). Neither can come out of the generator, so an occurrence is a
// generator bug and must be loud.
func sqlScalar(s string) (*yaml.Node, error) {
	if s == "" {
		return nil, fmt.Errorf("empty statement")
	}
	for i, line := range strings.Split(s, "\n") {
		if strings.TrimRight(line, " \t") != line {
			return nil, fmt.Errorf("line %d has trailing whitespace, which a block scalar strips on read: %q", i, line)
		}
	}
	if strings.HasPrefix(s, " ") || strings.HasPrefix(s, "\t") {
		return nil, fmt.Errorf("statement starts with whitespace: %q", s)
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s, Style: yaml.LiteralStyle}, nil
}

// valueScalar renders one expectation cell in the typed form Java's Matchers
// compare with. The KIND of the YAML scalar decides the Java expectation
// class, and the matcher is class-sensitive, so each Go type maps onto the one
// spelling whose class matches what the driver hands back for that column:
//
//   - nil        → `!null` — the by-name SQL NULL matcher (an UNTAGGED null
//     would flip the cell into Java's positional form and change its meaning);
//   - bool       → plain bool;
//   - integers   → plain int (SnakeYAML resolves to Integer when it fits and
//     Long otherwise; Java's matchIntField promotes Integer to a Long actual,
//     so one spelling covers INTEGER and BIGINT columns);
//   - float32    → `!f` — a FLOAT column's actual is a Float, which a plain
//     YAML float (a Double expectation) would never equal;
//   - float64    → plain float, rendered so it re-reads with the identical
//     bit pattern (canonicalFloat).
func valueScalar(v any) (*yaml.Node, error) {
	switch x := v.(type) {
	case nil:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!null", Value: ""}, nil
	case bool:
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: strconv.FormatBool(x)}, nil
	case int:
		return intScalar(int64(x)), nil
	case int32:
		return intScalar(int64(x)), nil
	case int64:
		return intScalar(x), nil
	case uint32:
		return intScalar(int64(x)), nil
	case uint64:
		// Values above MaxInt64 cannot be expressed as a Java Long expectation,
		// so they are refused rather than silently wrapping to a negative one.
		if x > math.MaxInt64 {
			return nil, fmt.Errorf("value %d exceeds int64; a Long expectation would compare a wrapped value", x)
		}
		return intScalar(int64(x)), nil
	case float32:
		if math.IsNaN(float64(x)) || math.IsInf(float64(x), 0) {
			return nil, fmt.Errorf("non-finite float32 %v cannot be frozen as a portable expectation", x)
		}
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!f", Value: canonicalFloat32(x)}, nil
	case float64:
		if math.IsNaN(x) || math.IsInf(x, 0) {
			return nil, fmt.Errorf("non-finite float64 %v cannot be frozen as a portable expectation", x)
		}
		return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!float", Value: canonicalFloat(x)}, nil
	case string:
		return strScalar(x), nil
	default:
		return nil, fmt.Errorf("value %v has type %T, which the corpus format cannot freeze; the executor must normalize it first", v, v)
	}
}

func intScalar(v int64) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: strconv.FormatInt(v, 10)}
}

// canonicalFloat spells a float64 in a form YAML re-reads as a float64 with
// the identical bit pattern.
//
// strconv's shortest round-trip form is the right numeric text, but it is not
// always valid YAML float SYNTAX: `-0` and `3` reload as ints. Appending `.0`
// when no `.` or `e` is present forces the float tag; the signed zero case is
// the one that matters, because `-0` → int 0 → `0` silently loses the sign of
// a value this repo has already shipped one wrong-rows bug on.
func canonicalFloat(f float64) string {
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// canonicalFloat32 is canonicalFloat at float32 width: the shortest text that
// parses back (through float64, which represents every float32 exactly) to the
// identical float32 bit pattern.
func canonicalFloat32(f float32) string {
	s := strconv.FormatFloat(float64(f), 'g', -1, 32)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}
