// gen_v5.cpp — v5 code generator: composable primitives + two-pass direct-write serialization.
// Compiles against real FDB headers via extract.h. Outputs Go files to a directory.
//
// Key differences from v4 (main.cpp's GoEmitter):
// - measureEndOff + writeDirect + two-pass MarshalFDB (measure then write)
// - No MarshalInto, no WriteXxx helpers, no MarshalXxx helpers
// - ParseXxxStringVector uses sub-slicing instead of make+copy

#include "extract.h"

// ============================================================
// GoEmitterV5 — composable primitives, two-pass direct-write
// ============================================================

struct GoEmitterV5 {
    FILE* f;

    void emitFull(const char* typeName, const std::vector<FieldDesc>& fields,
                  const std::vector<uint16_t>& vt, uint32_t fileId,
                  const std::vector<std::vector<uint16_t>>& closure) {
        // Determine import requirements.
        bool needsBinary = false;
        bool needsMath = false;
        bool isTopLevel = (fileId > 0 && !closure.empty());

        for (auto& fd : fields) {
            if (fd.kind == FieldKind::Scalar && fd.scalar.goType) {
                if (strcmp(fd.scalar.goType, "uint16") == 0 ||
                    strcmp(fd.scalar.goType, "int16") == 0 ||
                    strcmp(fd.scalar.goType, "uint32") == 0 ||
                    strcmp(fd.scalar.goType, "int32") == 0 ||
                    strcmp(fd.scalar.goType, "uint64") == 0 ||
                    strcmp(fd.scalar.goType, "int64") == 0 ||
                    strcmp(fd.scalar.goType, "float64") == 0)
                    needsBinary = true;
                if (strcmp(fd.scalar.goType, "float64") == 0)
                    needsMath = true;
            }
        }
        // allFieldsDynamicSize types use binary.LittleEndian in ParseXxxStringVector.
        if (allFieldsDynamicSize(fields))
            needsBinary = true;

        // Header.
        fprintf(f, "// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.\n\n");
        fprintf(f, "package types\n\n");

        if (needsBinary || needsMath) {
            fprintf(f, "import (\n");
            if (needsBinary) fprintf(f, "\t\"encoding/binary\"\n");
            if (needsMath) fprintf(f, "\t\"math\"\n");
            fprintf(f, "\n\t\"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire\"\n");
            fprintf(f, ")\n\n");
        } else {
            fprintf(f, "import \"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire\"\n\n");
        }

        // Slot constants.
        fprintf(f, "const (\n");
        for (auto& fd : fields) {
            auto gn = fieldGoName(fd);
            fprintf(f, "\t%sSlot%s = %d\n", typeName, gn.c_str(), fd.vtableSlot);
        }
        fprintf(f, ")\n\n");

        // VTable.
        fprintf(f, "var %sVTable = wire.VTable{", typeName);
        for (size_t i = 0; i < vt.size(); i++) {
            if (i) fprintf(f, ", ");
            fprintf(f, "%u", vt[i]);
        }
        fprintf(f, "}\n");

        // FileID.
        if (fileId > 0) fprintf(f, "const %sFileID uint32 = %u\n", typeName, fileId);

        // VTable closure.
        if (!closure.empty()) {
            fprintf(f, "var %sVTableClosure = []wire.VTable{\n", typeName);
            for (auto& cvt : closure) {
                fprintf(f, "\t{");
                for (size_t i = 0; i < cvt.size(); i++) {
                    if (i) fprintf(f, ", ");
                    fprintf(f, "%u", cvt[i]);
                }
                fprintf(f, "},\n");
            }
            fprintf(f, "}\n");
        }

        // MessageTemplate.
        int maxAlign = computeMaxAlign(fields);
        if (isTopLevel) {
            fprintf(f, "var %sTemplate = wire.NewMessageTemplate(\n", typeName);
            fprintf(f, "\t%sFileID, %sVTable, %d, %sVTableClosure,\n)\n",
                    typeName, typeName, maxAlign, typeName);
        }

        // MaxAlign constant.
        fprintf(f, "const %sMaxAlign = %d\n", typeName, maxAlign);

        fprintf(f, "\n");

        // Struct.
        fprintf(f, "type %s struct {\n", typeName);
        for (auto& fd : fields) {
            auto gn = fieldGoName(fd);
            switch (fd.kind) {
            case FieldKind::Scalar:
                fprintf(f, "\t%s %s // slot %d\n", gn.c_str(), fd.scalar.goType, fd.vtableSlot);
                break;
            case FieldKind::DynamicSize:
            case FieldKind::VectorLike:
                fprintf(f, "\t%s []byte // slot %d\n", gn.c_str(), fd.vtableSlot);
                break;
            case FieldKind::NestedStruct:
                if (fd.nestedGoType[0])
                    fprintf(f, "\t%s %s // slot %d, nested\n", gn.c_str(), fd.nestedGoType, fd.vtableSlot);
                else
                    fprintf(f, "\t// %s: unregistered nested struct at slot %d\n", gn.c_str(), fd.vtableSlot);
                break;
            case FieldKind::Optional:
                fprintf(f, "\tHas%s bool   // slot %d, optional tag\n", gn.c_str(), fd.vtableSlot);
                fprintf(f, "\t%s    []byte // slot %d, optional value\n", gn.c_str(), fd.vtableSlot + 1);
                break;
            case FieldKind::Variant:
                fprintf(f, "\t%sTag uint8 // slot %d, variant tag\n", gn.c_str(), fd.vtableSlot);
                for (size_t a = 0; a < fd.variantAlts.size(); a++) {
                    fprintf(f, "\t%sAlt%zu %s // tag=%zu\n",
                            gn.c_str(), a, fd.variantAlts[a].goType, a + 1);
                }
                break;
            }
        }
        fprintf(f, "}\n\n");

        // UnmarshalFromReader.
        fprintf(f, "func (m *%s) UnmarshalFromReader(r *wire.Reader) {\n", typeName);
        emitReads(typeName, fields, "r");
        fprintf(f, "}\n\n");

        // UnmarshalFDB.
        fprintf(f, "func (m *%s) UnmarshalFDB(data []byte) error {\n", typeName);
        fprintf(f, "\tr, err := wire.NewReader(data)\n");
        fprintf(f, "\tif err != nil { return err }\n");
        emitReads(typeName, fields, "r");
        fprintf(f, "\treturn nil\n}\n\n");

        // measureEndOff.
        emitMeasureEndOff(typeName, fields);

        // writeDirect.
        emitWriteDirect(typeName, fields);

        // MarshalFDB — two-pass, top-level only.
        if (isTopLevel) {
            emitMarshalFDB(typeName, fields, maxAlign);
        }

        // FlatBuffers vector parser.
        emitFBVectorParser(typeName);

        // String vector parser (sub-slice variant).
        if (allFieldsDynamicSize(fields)) {
            emitStringVectorParser(typeName, fields);
        }
    }

private:
    static int computeMaxAlign(const std::vector<FieldDesc>& fields) {
        for (auto& fd : fields)
            if (fd.kind == FieldKind::Scalar && fd.size >= 8)
                return 8;
        return 4;
    }

    // ---- UnmarshalFromReader / UnmarshalFDB read logic (same as v4) ----

    void emitReads(const char* typeName, const std::vector<FieldDesc>& fields, const char* rv) {
        for (auto& fd : fields) {
            auto gn = fieldGoName(fd);
            auto slot = std::string(typeName) + "Slot" + gn;
            switch (fd.kind) {
            case FieldKind::Scalar:
                fprintf(f, "\tif %s.FieldPresent(%s) {\n", rv, slot.c_str());
                fprintf(f, "\t\tm.%s = %s.%s(%s)\n", gn.c_str(), rv, fd.scalar.reader, slot.c_str());
                fprintf(f, "\t}\n");
                break;
            case FieldKind::DynamicSize:
            case FieldKind::VectorLike:
                fprintf(f, "\tif %s.FieldPresent(%s) {\n", rv, slot.c_str());
                fprintf(f, "\t\tm.%s = %s.ReadBytes(%s)\n", gn.c_str(), rv, slot.c_str());
                fprintf(f, "\t}\n");
                break;
            case FieldKind::NestedStruct:
                if (fd.nestedGoType[0]) {
                    fprintf(f, "\tif nr, err := %s.ReadNestedReader(%s); err == nil {\n", rv, slot.c_str());
                    fprintf(f, "\t\tm.%s.UnmarshalFromReader(nr)\n", gn.c_str());
                    fprintf(f, "\t}\n");
                }
                break;
            case FieldKind::Optional:
                fprintf(f, "\tif %s.FieldPresent(%s) && %s.ReadUint8(%s) > 0 {\n",
                        rv, slot.c_str(), rv, slot.c_str());
                fprintf(f, "\t\tm.%s = %s.ReadBytes(%s + 1)\n", gn.c_str(), rv, slot.c_str());
                fprintf(f, "\t\tm.Has%s = true\n", gn.c_str());
                fprintf(f, "\t}\n");
                break;
            case FieldKind::Variant:
                fprintf(f, "\tif %s.FieldPresent(%s) {\n", rv, slot.c_str());
                fprintf(f, "\t\tm.%sTag = %s.ReadUint8(%s)\n", gn.c_str(), rv, slot.c_str());
                fprintf(f, "\t\tswitch m.%sTag {\n", gn.c_str());
                for (size_t a = 0; a < fd.variantAlts.size(); a++) {
                    auto& alt = fd.variantAlts[a];
                    fprintf(f, "\t\tcase %zu:\n", a + 1);
                    if (alt.kind == FieldKind::Scalar && alt.size == 4) {
                        fprintf(f, "\t\t\tm.%sAlt%zu = %s.ReadRelOffUint32(%s + 1)\n",
                                gn.c_str(), a, rv, slot.c_str());
                    } else {
                        fprintf(f, "\t\t\tm.%sAlt%zu = %s.ReadRelOffRaw(%s + 1, %d)\n",
                                gn.c_str(), a, rv, slot.c_str(), alt.size);
                    }
                }
                fprintf(f, "\t\t}\n");
                fprintf(f, "\t}\n");
                break;
            }
        }
    }

    // ---- measureEndOff ----

    void emitMeasureEndOff(const char* typeName, const std::vector<FieldDesc>& fields) {
        fprintf(f, "func (m *%s) measureEndOff(endOff int) int {\n", typeName);

        bool hasBody = false;
        // Step 1: OOL fields (DynamicSize, VectorLike).
        for (auto& fd : fields) {
            if (fd.size == 0) continue;
            if (fd.kind != FieldKind::DynamicSize && fd.kind != FieldKind::VectorLike) continue;
            auto gn = fieldGoName(fd);
            if (fd.kind == FieldKind::DynamicSize) {
                fprintf(f, "\tendOff = wire.MeasureBytesOOL(endOff, m.%s)\n", gn.c_str());
            } else {
                fprintf(f, "\tendOff = wire.MeasureRawOOL(endOff, m.%s)\n", gn.c_str());
            }
            hasBody = true;
        }

        // Step 2: Nested structs in REVERSE order.
        std::vector<const FieldDesc*> nestedFields;
        for (auto& fd : fields) {
            if (fd.kind == FieldKind::NestedStruct && fd.nestedGoType && fd.nestedGoType[0])
                nestedFields.push_back(&fd);
        }
        for (auto it = nestedFields.rbegin(); it != nestedFields.rend(); ++it) {
            auto gn = fieldGoName(**it);
            fprintf(f, "\tendOff = m.%s.measureEndOff(endOff)\n", gn.c_str());
            hasBody = true;
        }

        // Step 3: Own object.
        fprintf(f, "\tendOff = wire.MeasureObject(endOff, %sVTable, %sMaxAlign)\n", typeName, typeName);
        hasBody = true;

        fprintf(f, "\treturn endOff\n");
        if (!hasBody) (void)hasBody; // suppress unused warning in generator
        fprintf(f, "}\n\n");
    }

    // ---- writeDirect ----

    void emitWriteDirect(const char* typeName, const std::vector<FieldDesc>& fields) {
        fprintf(f, "func (m *%s) writeDirect(dw *wire.DirectWriter) int {\n", typeName);

        // Collect fields by kind for ordered emission.
        std::vector<const FieldDesc*> oolFields;     // DynamicSize + VectorLike
        std::vector<const FieldDesc*> nestedFields;   // NestedStruct (registered only)
        std::vector<const FieldDesc*> scalarFields;   // Scalar
        for (auto& fd : fields) {
            if (fd.size == 0) continue; // Arena
            switch (fd.kind) {
            case FieldKind::DynamicSize:
            case FieldKind::VectorLike:
                oolFields.push_back(&fd);
                break;
            case FieldKind::NestedStruct:
                if (fd.nestedGoType && fd.nestedGoType[0])
                    nestedFields.push_back(&fd);
                break;
            case FieldKind::Scalar:
                scalarFields.push_back(&fd);
                break;
            default:
                break; // Optional, Variant: skip for now
            }
        }

        // Step 1: OOL writes.
        for (auto* fdp : oolFields) {
            auto gn = fieldGoName(*fdp);
            auto varName = safeParam(gn) + "OOL";
            if (fdp->kind == FieldKind::DynamicSize) {
                fprintf(f, "\tvar %s int\n", varName.c_str());
                fprintf(f, "\tif m.%s != nil {\n", gn.c_str());
                fprintf(f, "\t\t%s = dw.WriteBytesOOL(m.%s)\n", varName.c_str(), gn.c_str());
                fprintf(f, "\t}\n");
            } else { // VectorLike
                fprintf(f, "\tvar %s int\n", varName.c_str());
                fprintf(f, "\tif m.%s != nil {\n", gn.c_str());
                fprintf(f, "\t\t%s = dw.WriteRawOOL(m.%s)\n", varName.c_str(), gn.c_str());
                fprintf(f, "\t}\n");
            }
        }

        // Step 2: Nested structs in REVERSE order.
        for (auto it = nestedFields.rbegin(); it != nestedFields.rend(); ++it) {
            auto gn = fieldGoName(**it);
            auto varName = safeParam(gn) + "Pos";
            fprintf(f, "\t%s := m.%s.writeDirect(dw)\n", varName.c_str(), gn.c_str());
        }

        // Step 3: Write object.
        fprintf(f, "\tobjPos, obj := dw.WriteObject(%sVTable, %sMaxAlign)\n", typeName, typeName);

        // Declare vt local if any field references vtable offsets.
        bool needsVtLocal = !scalarFields.empty() || !oolFields.empty() || !nestedFields.empty();
        if (needsVtLocal) {
            fprintf(f, "\tvt := %sVTable\n", typeName);
        }

        // Step 3a: Inline scalars.
        for (auto* fdp : scalarFields) {
            auto gn = fieldGoName(*fdp);
            auto slot = std::string(typeName) + "Slot" + gn;
            const char* goType = fdp->scalar.goType;

            if (strcmp(goType, "bool") == 0) {
                fprintf(f, "\tif m.%s {\n", gn.c_str());
                fprintf(f, "\t\tobj[int(vt[%s+2])] = 1\n", slot.c_str());
                fprintf(f, "\t}\n");
            } else if (strcmp(goType, "uint8") == 0) {
                fprintf(f, "\tobj[int(vt[%s+2])] = m.%s\n", slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "int8") == 0) {
                fprintf(f, "\tobj[int(vt[%s+2])] = byte(m.%s)\n", slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "[16]byte") == 0) {
                fprintf(f, "\tcopy(obj[int(vt[%s+2]):], m.%s[:])\n", slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "uint16") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint16(obj[int(vt[%s+2]):], m.%s)\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "int16") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint16(obj[int(vt[%s+2]):], uint16(m.%s))\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "uint32") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint32(obj[int(vt[%s+2]):], m.%s)\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "int32") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint32(obj[int(vt[%s+2]):], uint32(m.%s))\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "uint64") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint64(obj[int(vt[%s+2]):], m.%s)\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "int64") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint64(obj[int(vt[%s+2]):], uint64(m.%s))\n",
                        slot.c_str(), gn.c_str());
            } else if (strcmp(goType, "float64") == 0) {
                fprintf(f, "\tbinary.LittleEndian.PutUint64(obj[int(vt[%s+2]):], math.Float64bits(m.%s))\n",
                        slot.c_str(), gn.c_str());
            }
        }

        // Step 3b: Patch OOL RelOffs.
        for (auto* fdp : oolFields) {
            auto gn = fieldGoName(*fdp);
            auto slot = std::string(typeName) + "Slot" + gn;
            auto varName = safeParam(gn) + "OOL";
            fprintf(f, "\tif m.%s != nil {\n", gn.c_str());
            fprintf(f, "\t\twire.PatchRelOff(obj, int(vt[%s+2]), objPos, %s)\n",
                    slot.c_str(), varName.c_str());
            fprintf(f, "\t}\n");
        }

        // Step 3c: Patch nested RelOffs.
        for (auto* fdp : nestedFields) {
            auto gn = fieldGoName(*fdp);
            auto slot = std::string(typeName) + "Slot" + gn;
            auto varName = safeParam(gn) + "Pos";
            fprintf(f, "\twire.PatchRelOff(obj, int(vt[%s+2]), objPos, %s)\n",
                    slot.c_str(), varName.c_str());
        }

        fprintf(f, "\treturn objPos\n");
        fprintf(f, "}\n\n");
    }

    // ---- MarshalFDB — two-pass direct-write (top-level only) ----

    void emitMarshalFDB(const char* typeName, const std::vector<FieldDesc>& fields, int maxAlign) {
        fprintf(f, "func (m *%s) MarshalFDB() []byte {\n", typeName);
        fprintf(f, "\tt := %sTemplate\n", typeName);

        // Pass 1: content-only measure (same as measureEndOff but WITHOUT final MeasureObject).
        fprintf(f, "\tendOff := 0\n");

        // OOL field measures.
        for (auto& fd : fields) {
            if (fd.size == 0) continue;
            if (fd.kind != FieldKind::DynamicSize && fd.kind != FieldKind::VectorLike) continue;
            auto gn = fieldGoName(fd);
            if (fd.kind == FieldKind::DynamicSize) {
                fprintf(f, "\tendOff = wire.MeasureBytesOOL(endOff, m.%s)\n", gn.c_str());
            } else {
                fprintf(f, "\tendOff = wire.MeasureRawOOL(endOff, m.%s)\n", gn.c_str());
            }
        }

        // Nested struct measures in REVERSE order.
        std::vector<const FieldDesc*> nestedFields;
        for (auto& fd : fields) {
            if (fd.kind == FieldKind::NestedStruct && fd.nestedGoType && fd.nestedGoType[0])
                nestedFields.push_back(&fd);
        }
        for (auto it = nestedFields.rbegin(); it != nestedFields.rend(); ++it) {
            auto gn = fieldGoName(**it);
            fprintf(f, "\tendOff = m.%s.measureEndOff(endOff)\n", gn.c_str());
        }

        // Layout calculation.
        fprintf(f, "\tbodySize := int(%sVTable[1]) - 4\n", typeName);
        fprintf(f, "\tmsgObjEnd := ((endOff + bodySize + %d - 1) &^ (%d - 1)) + 4\n", maxAlign, maxAlign);
        fprintf(f, "\tfakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4\n");
        fprintf(f, "\tvtableSize := t.PackedVTablesLen()\n");
        fprintf(f, "\tvtableEnd := fakeRootEnd + vtableSize\n");
        fprintf(f, "\ttotalSize := (vtableEnd + 8 + 7) &^ 7\n");
        fprintf(f, "\tvtablePos := totalSize - vtableEnd\n");
        fprintf(f, "\tfakeRootPos := totalSize - fakeRootEnd\n");
        fprintf(f, "\tmsgObjPos := totalSize - msgObjEnd\n");
        fprintf(f, "\t_ = msgObjPos\n");

        // Allocate and write.
        fprintf(f, "\tbuf := make([]byte, totalSize)\n");
        fprintf(f, "\tvar dw wire.DirectWriter\n");
        fprintf(f, "\tdw.Init(buf, totalSize, vtablePos, t)\n");
        fprintf(f, "\tm.writeDirect(&dw)\n");
        fprintf(f, "\tt.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)\n");
        fprintf(f, "\tt.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)\n");
        fprintf(f, "\treturn buf\n");
        fprintf(f, "}\n\n");
    }

    // ---- FlatBuffers vector parser (same as v4) ----

    void emitFBVectorParser(const char* typeName) {
        fprintf(f, "// Parse%sVectorFromReader reads a FlatBuffers vector of %s.\n", typeName, typeName);
        fprintf(f, "func Parse%sVectorFromReader(r *wire.Reader, slot int) []%s {\n", typeName, typeName);
        fprintf(f, "\tcount, err := r.ReadVectorCount(slot)\n");
        fprintf(f, "\tif err != nil || count == 0 { return nil }\n");
        fprintf(f, "\tresult := make([]%s, 0, count)\n", typeName);
        fprintf(f, "\tfor i := 0; i < count; i++ {\n");
        fprintf(f, "\t\telemR, err := r.ReadVectorElementReader(slot, i)\n");
        fprintf(f, "\t\tif err != nil { continue }\n");
        fprintf(f, "\t\tvar elem %s\n", typeName);
        fprintf(f, "\t\telem.UnmarshalFromReader(elemR)\n");
        fprintf(f, "\t\tresult = append(result, elem)\n");
        fprintf(f, "\t}\n");
        fprintf(f, "\treturn result\n");
        fprintf(f, "}\n\n");
    }

    // ---- String vector parser (sub-slice instead of make+copy) ----

    void emitStringVectorParser(const char* typeName, const std::vector<FieldDesc>& fields) {
        fprintf(f, "// Parse%sStringVector decodes a VectorRef<%s, VecSerStrategy::String>.\n", typeName, typeName);
        fprintf(f, "// Each element's DynamicSize fields are inline: [len(4)][data] per field.\n");
        fprintf(f, "func Parse%sStringVector(data []byte) []%s {\n", typeName, typeName);
        fprintf(f, "\tif len(data) < 4 { return nil }\n");
        fprintf(f, "\tcount := binary.LittleEndian.Uint32(data[0:4])\n");
        fprintf(f, "\tif count == 0 { return nil }\n");
        fprintf(f, "\tpos := 4\n");
        fprintf(f, "\tresult := make([]%s, 0, count)\n", typeName);
        fprintf(f, "\tfor i := uint32(0); i < count; i++ {\n");
        fprintf(f, "\t\tvar elem %s\n", typeName);
        for (auto& fd : fields) {
            if (fd.size == 0 || fd.kind != FieldKind::DynamicSize) continue;
            auto gn = fieldGoName(fd);
            fprintf(f, "\t\tif pos+4 > len(data) { break }\n");
            fprintf(f, "\t\t{\n");
            fprintf(f, "\t\t\tn := int(binary.LittleEndian.Uint32(data[pos:]))\n");
            fprintf(f, "\t\t\tpos += 4\n");
            fprintf(f, "\t\t\tif n < 0 || pos+n > len(data) { break }\n");
            fprintf(f, "\t\t\telem.%s = data[pos:pos+n:pos+n]\n", gn.c_str());
            fprintf(f, "\t\t\tpos += n\n");
            fprintf(f, "\t\t}\n");
        }
        fprintf(f, "\t\tresult = append(result, elem)\n");
        fprintf(f, "\t}\n");
        fprintf(f, "\treturn result\n");
        fprintf(f, "}\n\n");
    }
};

// ============================================================
// extractType — uses GoEmitterV5
// ============================================================

template <class T, bool SkipObjectWriter = false>
void extractType(const char* outDir, const char* name) {
    int pipefd[2];
    pipe(pipefd);
    pid_t pid = fork();
    if (pid == 0) {
        close(pipefd[0]);

        // Collect fields.
        FieldCollector<T> collector;
        T msg{};
        if constexpr (serializable_traits<T>::value)
            serializable_traits<T>::serialize(collector, msg);
        else
            msg.serialize(collector);

        // Get authoritative vtable from ObjectWriter (when possible).
        std::vector<std::vector<uint16_t>> closure;
        std::vector<uint16_t> rootVTable;
        if constexpr (!SkipObjectWriter && requires { T::file_identifier; }) {
            ObjectWriter wr(IncludeVersion(currentProtocolVersion()));
            wr.serialize(T::file_identifier, msg);
            auto bytes = wr.toStringRef();
            closure = extractVTableClosure(bytes.begin(), bytes.size());
            rootVTable = extractMessageVTable(bytes.begin(), bytes.size());
        }
        auto& vt = rootVTable.empty() ? collector.vtable : rootVTable;

        // Emit.
        FILE* pf = fdopen(pipefd[1], "w");
        GoEmitterV5 emitter{pf};
        emitter.emitFull(name, collector.fields, vt, getFileId<T>(), closure);
        fclose(pf);
        _exit(0);
    }

    close(pipefd[1]);
    std::string lowerName = toLower(name);
    std::string path = std::string(outDir) + "/" + lowerName + "_generated.go";
    FILE* out = fopen(path.c_str(), "w");
    if (!out) { perror(path.c_str()); goto wait; }
    {
        char buf[4096];
        ssize_t n;
        while ((n = read(pipefd[0], buf, sizeof(buf))) > 0)
            fwrite(buf, 1, n, out);
        fclose(out);
    }

wait:
    close(pipefd[0]);
    int status;
    waitpid(pid, &status, 0);
    if (WIFEXITED(status) && WEXITSTATUS(status) == 0)
        fprintf(stderr, "OK %s → %s_generated.go\n", name, lowerName.c_str());
    else
        fprintf(stderr, "SKIP %s\n", name);
}

// ============================================================
// Main
// ============================================================

int main(int argc, char** argv) {
    if (argc < 2) { fprintf(stderr, "Usage: %s <output-dir>\n", argv[0]); return 1; }
    const char* outDir = argv[1];

    TLSConfig tlsConfig;
    g_network = newNet2(tlsConfig, false, false);
    FlowTransport::createInstance(false, 1, WLTOKEN_FIRST_AVAILABLE, nullptr);

    // Extract ALL types.
    extractType<GetValueReply>(outDir, "GetValueReply");
    extractType<GetKeyValuesReply>(outDir, "GetKeyValuesReply");
    extractType<GetKeyReply>(outDir, "GetKeyReply");
    extractType<GetReadVersionReply>(outDir, "GetReadVersionReply");
    extractType<GetKeyServerLocationsReply>(outDir, "GetKeyServerLocationsReply");
    extractType<CommitID>(outDir, "CommitID");

    extractType<GetValueRequest>(outDir, "GetValueRequest");
    extractType<GetKeyValuesRequest>(outDir, "GetKeyValuesRequest");
    extractType<GetKeyRequest>(outDir, "GetKeyRequest");
    extractType<GetReadVersionRequest>(outDir, "GetReadVersionRequest");
    extractType<GetKeyServerLocationsRequest>(outDir, "GetKeyServerLocationsRequest");
    extractType<CommitTransactionRequest>(outDir, "CommitTransactionRequest");
    extractType<OpenDatabaseCoordRequest>(outDir, "OpenDatabaseCoordRequest");

    extractType<SpanContext>(outDir, "SpanContext");
    extractType<KeySelectorRef>(outDir, "KeySelectorRef");
    extractType<MutationRef>(outDir, "MutationRef");
    extractType<KeyRangeRef>(outDir, "KeyRangeRef");
    extractType<CommitTransactionRef>(outDir, "CommitTransactionRef");
    extractType<ReadOptions>(outDir, "ReadOptions");
    extractType<Error>(outDir, "Error");
    extractType<KeyValueRef>(outDir, "KeyValueRef");

    extractType<ClientDBInfo>(outDir, "ClientDBInfo");
    extractType<GrvProxyInterface, true>(outDir, "GrvProxyInterface");
    extractType<CommitProxyInterface, true>(outDir, "CommitProxyInterface");
    extractType<StorageServerInterface, true>(outDir, "StorageServerInterface");
    extractType<NetworkAddress>(outDir, "NetworkAddress");
    extractType<IPAddress>(outDir, "IPAddress");
    extractType<TenantInfo>(outDir, "TenantInfo");
    extractType<ReplyPromise<GetValueReply>>(outDir, "ReplyPromise");
    extractType<Endpoint>(outDir, "Endpoint");
    extractType<NetworkAddressList>(outDir, "NetworkAddressList");

    using LocationPair = std::pair<KeyRangeRef, std::vector<StorageServerInterface>>;
    extractType<LocationPair>(outDir, "LocationPair");

    fprintf(stderr, "Done.\n");
    return 0;
}
