load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "factory-migrate_lib",
    srcs = ["main.go"],
    importpath = "fdb.dev/cmd/factory-migrate",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/relational/conformance/factory",
        "//pkg/relational/conformance/factorycorpus",
        "//pkg/relational/conformance/yamsql",
        "//pkg/relational/sqldriver",
        "//pkg/testcontainers/foundationdb",
    ],
)

go_binary(
    name = "factory-migrate",
    embed = [":factory-migrate_lib"],
    visibility = ["//visibility:public"],
)
