load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "interleave",
    srcs = ["interleave.go"],
    importpath = "fdb.dev/pkg/simfdb/hunt/interleave",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fdbgo/fdb",
        "//pkg/fdbgo/fdb/subspace",
        "//pkg/fdbgo/fdb/tuple",
        "//pkg/simfdb",
        "//pkg/simfdb/hunt",
    ],
)

go_test(
    name = "interleave_test",
    srcs = ["interleave_test.go"],
    embed = [":interleave"],
    deps = [
        "//pkg/fdbgo/fdb/subspace",
        "//pkg/fdbgo/fdb/tuple",
        "//pkg/simfdb",
        "//pkg/simfdb/hunt",
    ],
)
