// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	ClientDBInfoSlotField_0  = 0
	ClientDBInfoSlotField_1  = 1
	ClientDBInfoSlotField_2  = 2
	ClientDBInfoSlotField_3  = 3
	ClientDBInfoSlotField_5  = 5
	ClientDBInfoSlotField_6  = 6
	ClientDBInfoSlotField_7  = 7
	ClientDBInfoSlotField_9  = 9
	ClientDBInfoSlotField_10 = 10
	ClientDBInfoSlotField_11 = 11
)

var ClientDBInfoVTable = wire.VTable{30, 71, 36, 40, 4, 68, 44, 48, 52, 69, 56, 20, 60, 70, 64}

const ClientDBInfoFileID uint32 = 5355080

var ClientDBInfoVTableClosure = []wire.VTable{
	{10, 28, 20, 4, 24},
	{8, 16, 12, 4},
	{8, 24, 20, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{12, 14, 12, 4, 13, 8},
	{30, 71, 36, 40, 4, 68, 44, 48, 52, 69, 56, 20, 60, 70, 64},
	{10, 13, 12, 4, 8},
	{10, 13, 4, 12, 8},
}
var ClientDBInfoTemplate = wire.NewMessageTemplate(
	ClientDBInfoFileID, ClientDBInfoVTable, 8, ClientDBInfoVTableClosure,
)

type ClientDBInfo struct {
	Field_0    []byte   // slot 0
	Field_1    []byte   // slot 1
	Field_2    [16]byte // slot 2
	HasField_3 bool     // slot 3, optional tag
	Field_3    []byte   // slot 4, optional value
	Field_5    []byte   // slot 5
	// Field_6: unregistered nested struct at slot 6
	HasField_7  bool     // slot 7, optional tag
	Field_7     []byte   // slot 8, optional value
	Field_9     [16]byte // slot 9
	Field_10    int32    // slot 10
	HasField_11 bool     // slot 11, optional tag
	Field_11    []byte   // slot 12, optional value
}

func (m *ClientDBInfo) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ClientDBInfoSlotField_0) {
		m.Field_0 = r.ReadBytes(ClientDBInfoSlotField_0)
	}
	if r.FieldPresent(ClientDBInfoSlotField_1) {
		m.Field_1 = r.ReadBytes(ClientDBInfoSlotField_1)
	}
	if r.FieldPresent(ClientDBInfoSlotField_2) {
		m.Field_2 = r.ReadUID(ClientDBInfoSlotField_2)
	}
	if r.FieldPresent(ClientDBInfoSlotField_3) && r.ReadUint8(ClientDBInfoSlotField_3) > 0 {
		m.Field_3 = r.ReadBytes(ClientDBInfoSlotField_3 + 1)
		m.HasField_3 = true
	}
	if r.FieldPresent(ClientDBInfoSlotField_5) {
		m.Field_5 = r.ReadBytes(ClientDBInfoSlotField_5)
	}
	if r.FieldPresent(ClientDBInfoSlotField_7) && r.ReadUint8(ClientDBInfoSlotField_7) > 0 {
		m.Field_7 = r.ReadBytes(ClientDBInfoSlotField_7 + 1)
		m.HasField_7 = true
	}
	if r.FieldPresent(ClientDBInfoSlotField_9) {
		m.Field_9 = r.ReadUID(ClientDBInfoSlotField_9)
	}
	if r.FieldPresent(ClientDBInfoSlotField_10) {
		m.Field_10 = r.ReadInt32(ClientDBInfoSlotField_10)
	}
	if r.FieldPresent(ClientDBInfoSlotField_11) && r.ReadUint8(ClientDBInfoSlotField_11) > 0 {
		m.Field_11 = r.ReadBytes(ClientDBInfoSlotField_11 + 1)
		m.HasField_11 = true
	}
}

func (m *ClientDBInfo) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ClientDBInfoSlotField_0) {
		m.Field_0 = r.ReadBytes(ClientDBInfoSlotField_0)
	}
	if r.FieldPresent(ClientDBInfoSlotField_1) {
		m.Field_1 = r.ReadBytes(ClientDBInfoSlotField_1)
	}
	if r.FieldPresent(ClientDBInfoSlotField_2) {
		m.Field_2 = r.ReadUID(ClientDBInfoSlotField_2)
	}
	if r.FieldPresent(ClientDBInfoSlotField_3) && r.ReadUint8(ClientDBInfoSlotField_3) > 0 {
		m.Field_3 = r.ReadBytes(ClientDBInfoSlotField_3 + 1)
		m.HasField_3 = true
	}
	if r.FieldPresent(ClientDBInfoSlotField_5) {
		m.Field_5 = r.ReadBytes(ClientDBInfoSlotField_5)
	}
	if r.FieldPresent(ClientDBInfoSlotField_7) && r.ReadUint8(ClientDBInfoSlotField_7) > 0 {
		m.Field_7 = r.ReadBytes(ClientDBInfoSlotField_7 + 1)
		m.HasField_7 = true
	}
	if r.FieldPresent(ClientDBInfoSlotField_9) {
		m.Field_9 = r.ReadUID(ClientDBInfoSlotField_9)
	}
	if r.FieldPresent(ClientDBInfoSlotField_10) {
		m.Field_10 = r.ReadInt32(ClientDBInfoSlotField_10)
	}
	if r.FieldPresent(ClientDBInfoSlotField_11) && r.ReadUint8(ClientDBInfoSlotField_11) > 0 {
		m.Field_11 = r.ReadBytes(ClientDBInfoSlotField_11 + 1)
		m.HasField_11 = true
	}
	return nil
}

func (m *ClientDBInfo) MarshalInto(obj *wire.ObjectWriter) {
	vt := ClientDBInfoVTable
	if m.Field_0 != nil {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotField_0+2]), m.Field_0)
	}
	if m.Field_1 != nil {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotField_1+2]), m.Field_1)
	}
	obj.WriteUID(int(vt[ClientDBInfoSlotField_2+2]), m.Field_2)
	if m.Field_5 != nil {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotField_5+2]), m.Field_5)
	}
	obj.WriteUID(int(vt[ClientDBInfoSlotField_9+2]), m.Field_9)
	obj.WriteInt32(int(vt[ClientDBInfoSlotField_10+2]), m.Field_10)
}

func (m *ClientDBInfo) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(ClientDBInfoTemplate, m.MarshalInto)
}

func WriteClientDBInfo(obj *wire.ObjectWriter, parentOffset int, field_0 []byte, field_1 []byte, field_2 [16]byte, field_5 []byte, field_9 [16]byte, field_10 int32) {
	m := ClientDBInfo{Field_0: field_0, Field_1: field_1, Field_2: field_2, Field_5: field_5, Field_9: field_9, Field_10: field_10}
	obj.WriteStruct(parentOffset, ClientDBInfoVTable, 8, m.MarshalInto)
}
