// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	CommitProxyInterfaceSlotField_0 = 0
	CommitProxyInterfaceSlotField_2 = 2
	CommitProxyInterfaceSlotField_3 = 3
)

var CommitProxyInterfaceVTable = wire.VTable{12, 14, 12, 4, 13, 8}

const CommitProxyInterfaceFileID uint32 = 8954922

type CommitProxyInterface struct {
	HasField_0 bool   // slot 0, optional tag
	Field_0    []byte // slot 1, optional value
	Field_2    bool   // slot 2
	// Field_3: unregistered nested struct at slot 3
}

func (m *CommitProxyInterface) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(CommitProxyInterfaceSlotField_0) && r.ReadUint8(CommitProxyInterfaceSlotField_0) > 0 {
		m.Field_0 = r.ReadBytes(CommitProxyInterfaceSlotField_0 + 1)
		m.HasField_0 = true
	}
	if r.FieldPresent(CommitProxyInterfaceSlotField_2) {
		m.Field_2 = r.ReadBool(CommitProxyInterfaceSlotField_2)
	}
}

func (m *CommitProxyInterface) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(CommitProxyInterfaceSlotField_0) && r.ReadUint8(CommitProxyInterfaceSlotField_0) > 0 {
		m.Field_0 = r.ReadBytes(CommitProxyInterfaceSlotField_0 + 1)
		m.HasField_0 = true
	}
	if r.FieldPresent(CommitProxyInterfaceSlotField_2) {
		m.Field_2 = r.ReadBool(CommitProxyInterfaceSlotField_2)
	}
	return nil
}

func (m *CommitProxyInterface) MarshalInto(obj *wire.ObjectWriter) {
	vt := CommitProxyInterfaceVTable
	obj.WriteBool(int(vt[CommitProxyInterfaceSlotField_2+2]), m.Field_2)
}

func WriteCommitProxyInterface(obj *wire.ObjectWriter, parentOffset int, field_2 bool) {
	m := CommitProxyInterface{Field_2: field_2}
	obj.WriteStruct(parentOffset, CommitProxyInterfaceVTable, 4, m.MarshalInto)
}
