// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	ErrorSlotErrorCode = 0
)

var ErrorVTable = wire.VTable{6, 6, 4}

const ErrorFileID uint32 = 14065384

var ErrorVTableClosure = []wire.VTable{
	{6, 8, 4},
	{6, 6, 4},
}
var ErrorTemplate = wire.NewMessageTemplate(
	ErrorFileID, ErrorVTable, 4, ErrorVTableClosure,
)

type Error struct {
	ErrorCode uint16 // slot 0
}

func (m *Error) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
}

func (m *Error) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
	return nil
}

func (m *Error) MarshalInto(obj *wire.ObjectWriter) {
	vt := ErrorVTable
	obj.WriteUint16(int(vt[ErrorSlotErrorCode+2]), m.ErrorCode)
}

func (m *Error) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(ErrorTemplate, m.MarshalInto)
}

func WriteError(obj *wire.ObjectWriter, parentOffset int, errorCode uint16) {
	m := Error{ErrorCode: errorCode}
	obj.WriteStruct(parentOffset, ErrorVTable, 4, m.MarshalInto)
}
