// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	GetReadVersionReplySlotProcessBusyTime           = 0
	GetReadVersionReplySlotVersion                   = 1
	GetReadVersionReplySlotLocked                    = 2
	GetReadVersionReplySlotMetadataVersion           = 3
	GetReadVersionReplySlotTagThrottleInfo           = 5
	GetReadVersionReplySlotMidShardSize              = 6
	GetReadVersionReplySlotRkDefaultThrottled        = 7
	GetReadVersionReplySlotRkBatchThrottled          = 8
	GetReadVersionReplySlotSsVersionVectorDelta      = 9
	GetReadVersionReplySlotProxyId                   = 10
	GetReadVersionReplySlotProxyTagThrottledDuration = 11
)

var GetReadVersionReplyVTable = wire.VTable{28, 64, 44, 20, 60, 61, 48, 52, 28, 62, 63, 56, 4, 36}

const GetReadVersionReplyFileID uint32 = 15709388

var GetReadVersionReplyVTableClosure = []wire.VTable{
	{8, 20, 4, 12},
	{6, 8, 4},
	{8, 12, 4, 8},
	{28, 64, 44, 20, 60, 61, 48, 52, 28, 62, 63, 56, 4, 36},
}
var GetReadVersionReplyTemplate = wire.NewMessageTemplate(
	GetReadVersionReplyFileID, GetReadVersionReplyVTable, 8, GetReadVersionReplyVTableClosure,
)

type GetReadVersionReply struct {
	ProcessBusyTime           int32    // slot 0
	Version                   int64    // slot 1
	Locked                    bool     // slot 2
	HasMetadataVersion        bool     // slot 3, optional tag
	MetadataVersion           []byte   // slot 4, optional value
	TagThrottleInfo           []byte   // slot 5
	MidShardSize              int64    // slot 6
	RkDefaultThrottled        bool     // slot 7
	RkBatchThrottled          bool     // slot 8
	SsVersionVectorDelta      []byte   // slot 9
	ProxyId                   [16]byte // slot 10
	ProxyTagThrottledDuration float64  // slot 11
}

func (m *GetReadVersionReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetReadVersionReplySlotProcessBusyTime) {
		m.ProcessBusyTime = r.ReadInt32(GetReadVersionReplySlotProcessBusyTime)
	}
	if r.FieldPresent(GetReadVersionReplySlotVersion) {
		m.Version = r.ReadInt64(GetReadVersionReplySlotVersion)
	}
	if r.FieldPresent(GetReadVersionReplySlotLocked) {
		m.Locked = r.ReadBool(GetReadVersionReplySlotLocked)
	}
	if r.FieldPresent(GetReadVersionReplySlotMetadataVersion) && r.ReadUint8(GetReadVersionReplySlotMetadataVersion) > 0 {
		m.MetadataVersion = r.ReadBytes(GetReadVersionReplySlotMetadataVersion + 1)
		m.HasMetadataVersion = true
	}
	if r.FieldPresent(GetReadVersionReplySlotTagThrottleInfo) {
		m.TagThrottleInfo = r.ReadBytes(GetReadVersionReplySlotTagThrottleInfo)
	}
	if r.FieldPresent(GetReadVersionReplySlotMidShardSize) {
		m.MidShardSize = r.ReadInt64(GetReadVersionReplySlotMidShardSize)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkDefaultThrottled) {
		m.RkDefaultThrottled = r.ReadBool(GetReadVersionReplySlotRkDefaultThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkBatchThrottled) {
		m.RkBatchThrottled = r.ReadBool(GetReadVersionReplySlotRkBatchThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotSsVersionVectorDelta) {
		m.SsVersionVectorDelta = r.ReadBytes(GetReadVersionReplySlotSsVersionVectorDelta)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyId) {
		m.ProxyId = r.ReadUID(GetReadVersionReplySlotProxyId)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyTagThrottledDuration) {
		m.ProxyTagThrottledDuration = r.ReadFloat64(GetReadVersionReplySlotProxyTagThrottledDuration)
	}
}

func (m *GetReadVersionReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetReadVersionReplySlotProcessBusyTime) {
		m.ProcessBusyTime = r.ReadInt32(GetReadVersionReplySlotProcessBusyTime)
	}
	if r.FieldPresent(GetReadVersionReplySlotVersion) {
		m.Version = r.ReadInt64(GetReadVersionReplySlotVersion)
	}
	if r.FieldPresent(GetReadVersionReplySlotLocked) {
		m.Locked = r.ReadBool(GetReadVersionReplySlotLocked)
	}
	if r.FieldPresent(GetReadVersionReplySlotMetadataVersion) && r.ReadUint8(GetReadVersionReplySlotMetadataVersion) > 0 {
		m.MetadataVersion = r.ReadBytes(GetReadVersionReplySlotMetadataVersion + 1)
		m.HasMetadataVersion = true
	}
	if r.FieldPresent(GetReadVersionReplySlotTagThrottleInfo) {
		m.TagThrottleInfo = r.ReadBytes(GetReadVersionReplySlotTagThrottleInfo)
	}
	if r.FieldPresent(GetReadVersionReplySlotMidShardSize) {
		m.MidShardSize = r.ReadInt64(GetReadVersionReplySlotMidShardSize)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkDefaultThrottled) {
		m.RkDefaultThrottled = r.ReadBool(GetReadVersionReplySlotRkDefaultThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkBatchThrottled) {
		m.RkBatchThrottled = r.ReadBool(GetReadVersionReplySlotRkBatchThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotSsVersionVectorDelta) {
		m.SsVersionVectorDelta = r.ReadBytes(GetReadVersionReplySlotSsVersionVectorDelta)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyId) {
		m.ProxyId = r.ReadUID(GetReadVersionReplySlotProxyId)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyTagThrottledDuration) {
		m.ProxyTagThrottledDuration = r.ReadFloat64(GetReadVersionReplySlotProxyTagThrottledDuration)
	}
	return nil
}

func (m *GetReadVersionReply) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetReadVersionReplyVTable
	obj.WriteInt32(int(vt[GetReadVersionReplySlotProcessBusyTime+2]), m.ProcessBusyTime)
	obj.WriteInt64(int(vt[GetReadVersionReplySlotVersion+2]), m.Version)
	obj.WriteBool(int(vt[GetReadVersionReplySlotLocked+2]), m.Locked)
	if m.TagThrottleInfo != nil {
		obj.WriteRawOOL(int(vt[GetReadVersionReplySlotTagThrottleInfo+2]), m.TagThrottleInfo)
	}
	obj.WriteInt64(int(vt[GetReadVersionReplySlotMidShardSize+2]), m.MidShardSize)
	obj.WriteBool(int(vt[GetReadVersionReplySlotRkDefaultThrottled+2]), m.RkDefaultThrottled)
	obj.WriteBool(int(vt[GetReadVersionReplySlotRkBatchThrottled+2]), m.RkBatchThrottled)
	if m.SsVersionVectorDelta != nil {
		obj.WriteBytes(int(vt[GetReadVersionReplySlotSsVersionVectorDelta+2]), m.SsVersionVectorDelta)
	}
	obj.WriteUID(int(vt[GetReadVersionReplySlotProxyId+2]), m.ProxyId)
	obj.WriteFloat64(int(vt[GetReadVersionReplySlotProxyTagThrottledDuration+2]), m.ProxyTagThrottledDuration)
}

func (m *GetReadVersionReply) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(GetReadVersionReplyTemplate, m.MarshalInto)
}

func WriteGetReadVersionReply(obj *wire.ObjectWriter, parentOffset int, processBusyTime int32, version int64, locked bool, tagThrottleInfo []byte, midShardSize int64, rkDefaultThrottled bool, rkBatchThrottled bool, ssVersionVectorDelta []byte, proxyId [16]byte, proxyTagThrottledDuration float64) {
	m := GetReadVersionReply{ProcessBusyTime: processBusyTime, Version: version, Locked: locked, TagThrottleInfo: tagThrottleInfo, MidShardSize: midShardSize, RkDefaultThrottled: rkDefaultThrottled, RkBatchThrottled: rkBatchThrottled, SsVersionVectorDelta: ssVersionVectorDelta, ProxyId: proxyId, ProxyTagThrottledDuration: proxyTagThrottledDuration}
	obj.WriteStruct(parentOffset, GetReadVersionReplyVTable, 8, m.MarshalInto)
}
