// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	KeyValueRefSlotKey   = 0
	KeyValueRefSlotValue = 1
)

var KeyValueRefVTable = wire.VTable{8, 12, 4, 8}

type KeyValueRef struct {
	Key   []byte // slot 0
	Value []byte // slot 1
}

func (m *KeyValueRef) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(KeyValueRefSlotKey) {
		m.Key = r.ReadBytes(KeyValueRefSlotKey)
	}
	if r.FieldPresent(KeyValueRefSlotValue) {
		m.Value = r.ReadBytes(KeyValueRefSlotValue)
	}
}

func (m *KeyValueRef) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(KeyValueRefSlotKey) {
		m.Key = r.ReadBytes(KeyValueRefSlotKey)
	}
	if r.FieldPresent(KeyValueRefSlotValue) {
		m.Value = r.ReadBytes(KeyValueRefSlotValue)
	}
	return nil
}

func (m *KeyValueRef) MarshalInto(obj *wire.ObjectWriter) {
	vt := KeyValueRefVTable
	if m.Key != nil {
		obj.WriteBytes(int(vt[KeyValueRefSlotKey+2]), m.Key)
	}
	if m.Value != nil {
		obj.WriteBytes(int(vt[KeyValueRefSlotValue+2]), m.Value)
	}
}

func WriteKeyValueRef(obj *wire.ObjectWriter, parentOffset int, key []byte, value []byte) {
	m := KeyValueRef{Key: key, Value: value}
	obj.WriteStruct(parentOffset, KeyValueRefVTable, 4, m.MarshalInto)
}

// ParseKeyValueRefVectorFromReader reads a FlatBuffers vector of KeyValueRef.
func ParseKeyValueRefVectorFromReader(r *wire.Reader, slot int) []KeyValueRef {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]KeyValueRef, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem KeyValueRef
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

// ParseKeyValueRefStringVector decodes a VectorRef<KeyValueRef, VecSerStrategy::String>.
// Each element's DynamicSize fields are inline: [len(4)][data] per field.
func ParseKeyValueRefStringVector(data []byte) []KeyValueRef {
	if len(data) < 4 {
		return nil
	}
	count := binary.LittleEndian.Uint32(data[0:4])
	if count == 0 {
		return nil
	}
	pos := 4
	result := make([]KeyValueRef, 0, count)
	for i := uint32(0); i < count; i++ {
		var elem KeyValueRef
		if pos+4 > len(data) {
			break
		}
		{
			n := int(binary.LittleEndian.Uint32(data[pos:]))
			pos += 4
			if n < 0 || pos+n > len(data) {
				break
			}
			elem.Key = make([]byte, n)
			copy(elem.Key, data[pos:pos+n])
			pos += n
		}
		if pos+4 > len(data) {
			break
		}
		{
			n := int(binary.LittleEndian.Uint32(data[pos:]))
			pos += 4
			if n < 0 || pos+n > len(data) {
				break
			}
			elem.Value = make([]byte, n)
			copy(elem.Value, data[pos:pos+n])
			pos += n
		}
		result = append(result, elem)
	}
	return result
}
