// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	MutationRefSlotMutType = 0
	MutationRefSlotParam1  = 1
	MutationRefSlotParam2  = 2
)

var MutationRefVTable = wire.VTable{10, 13, 12, 4, 8}

type MutationRef struct {
	MutType uint8  // slot 0
	Param1  []byte // slot 1
	Param2  []byte // slot 2
}

func (m *MutationRef) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(MutationRefSlotMutType) {
		m.MutType = r.ReadUint8(MutationRefSlotMutType)
	}
	if r.FieldPresent(MutationRefSlotParam1) {
		m.Param1 = r.ReadBytes(MutationRefSlotParam1)
	}
	if r.FieldPresent(MutationRefSlotParam2) {
		m.Param2 = r.ReadBytes(MutationRefSlotParam2)
	}
}

func (m *MutationRef) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(MutationRefSlotMutType) {
		m.MutType = r.ReadUint8(MutationRefSlotMutType)
	}
	if r.FieldPresent(MutationRefSlotParam1) {
		m.Param1 = r.ReadBytes(MutationRefSlotParam1)
	}
	if r.FieldPresent(MutationRefSlotParam2) {
		m.Param2 = r.ReadBytes(MutationRefSlotParam2)
	}
	return nil
}

func (m *MutationRef) MarshalInto(obj *wire.ObjectWriter) {
	vt := MutationRefVTable
	obj.WriteUint8(int(vt[MutationRefSlotMutType+2]), m.MutType)
	if m.Param1 != nil {
		obj.WriteBytes(int(vt[MutationRefSlotParam1+2]), m.Param1)
	}
	if m.Param2 != nil {
		obj.WriteBytes(int(vt[MutationRefSlotParam2+2]), m.Param2)
	}
}

func WriteMutationRef(obj *wire.ObjectWriter, parentOffset int, mutType uint8, param1 []byte, param2 []byte) {
	m := MutationRef{MutType: mutType, Param1: param1, Param2: param2}
	obj.WriteStruct(parentOffset, MutationRefVTable, 4, m.MarshalInto)
}
