// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	NetworkAddressListSlotField_0 = 0
	NetworkAddressListSlotField_1 = 1
)

var NetworkAddressListVTable = wire.VTable{10, 13, 4, 12, 8}

type NetworkAddressList struct {
	Field_0    NetworkAddress // slot 0, nested
	HasField_1 bool           // slot 1, optional tag
	Field_1    []byte         // slot 2, optional value
}

func (m *NetworkAddressList) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(NetworkAddressListSlotField_0); err == nil {
		m.Field_0.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(NetworkAddressListSlotField_1) && r.ReadUint8(NetworkAddressListSlotField_1) > 0 {
		m.Field_1 = r.ReadBytes(NetworkAddressListSlotField_1 + 1)
		m.HasField_1 = true
	}
}

func (m *NetworkAddressList) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(NetworkAddressListSlotField_0); err == nil {
		m.Field_0.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(NetworkAddressListSlotField_1) && r.ReadUint8(NetworkAddressListSlotField_1) > 0 {
		m.Field_1 = r.ReadBytes(NetworkAddressListSlotField_1 + 1)
		m.HasField_1 = true
	}
	return nil
}

func (m *NetworkAddressList) MarshalInto(obj *wire.ObjectWriter) {
	vt := NetworkAddressListVTable
	obj.WriteStruct(int(vt[NetworkAddressListSlotField_0+2]), NetworkAddressVTable, 8, m.Field_0.MarshalInto)
}

func WriteNetworkAddressList(obj *wire.ObjectWriter, parentOffset int) {
	m := NetworkAddressList{}
	obj.WriteStruct(parentOffset, NetworkAddressListVTable, 4, m.MarshalInto)
}

// ParseNetworkAddressListVectorFromReader reads a FlatBuffers vector of NetworkAddressList.
func ParseNetworkAddressListVectorFromReader(r *wire.Reader, slot int) []NetworkAddressList {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]NetworkAddressList, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem NetworkAddressList
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
