// Code generated by poc_generator from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	ReplyPromiseSlotToken = 0
)

var ReplyPromiseVTable = wire.VTable{6, 20, 4}

const ReplyPromiseFileID uint32 = 18156145

var ReplyPromiseVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
}
var ReplyPromiseTemplate = wire.NewMessageTemplate(
	ReplyPromiseFileID, ReplyPromiseVTable, 8, ReplyPromiseVTableClosure,
)

type ReplyPromise struct {
	Token [16]byte // slot 0
}

func (m *ReplyPromise) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ReplyPromiseSlotToken) {
		m.Token = r.ReadUID(ReplyPromiseSlotToken)
	}
}

func (m *ReplyPromise) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ReplyPromiseSlotToken) {
		m.Token = r.ReadUID(ReplyPromiseSlotToken)
	}
	return nil
}

func (m *ReplyPromise) MarshalInto(obj *wire.ObjectWriter) {
	vt := ReplyPromiseVTable
	obj.WriteUID(int(vt[ReplyPromiseSlotToken+2]), m.Token)
}

func (m *ReplyPromise) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(ReplyPromiseTemplate, m.MarshalInto)
}

func WriteReplyPromise(obj *wire.ObjectWriter, parentOffset int, token [16]byte) {
	m := ReplyPromise{Token: token}
	obj.WriteStruct(parentOffset, ReplyPromiseVTable, 8, m.MarshalInto)
}
