load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "rywlocal_test",
    srcs = [
        "cache_test.go",
        "fallback_test.go",
        "local_test.go",
        "range_test.go",
    ],
    deps = [
        "//pkg/fdbgo/client",
        "//pkg/fdbgo/transport",
        "//pkg/fdbgo/wire",
        "//pkg/testcontainers/foundationdb",
    ],
)
