// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// ClientDBInfo fields:
//
//	slot 0: grvProxies — vector_like, size=4, align=4, indirection
//	slot 1: commitProxies — vector_like, size=4, align=4, indirection
//	slot 2: id — scalar, size=16, align=8
//	slot 3: forward — union_like, size=4, align=4, indirection
//	slot 5: history — vector_like, size=4, align=4, indirection
//	slot 6: tenantMode — serialize_member, size=4, align=4, indirection
//	slot 7: encryptKeyProxy — union_like, size=4, align=4, indirection
//	slot 9: clusterId — scalar, size=16, align=8
//	slot 10: clusterType — scalar, size=4, align=4
//	slot 11: metaclusterName — union_like, size=4, align=4, indirection
const (
	ClientDBInfoSlotGrvProxies      = 0
	ClientDBInfoSlotCommitProxies   = 1
	ClientDBInfoSlotId              = 2
	ClientDBInfoSlotForward         = 3
	ClientDBInfoSlotHistory         = 5
	ClientDBInfoSlotTenantMode      = 6
	ClientDBInfoSlotEncryptKeyProxy = 7
	ClientDBInfoSlotClusterId       = 9
	ClientDBInfoSlotClusterType     = 10
	ClientDBInfoSlotMetaclusterName = 11
)

var ClientDBInfoVTable = wire.VTable{30, 71, 36, 40, 4, 68, 44, 48, 52, 69, 56, 20, 60, 70, 64}

const ClientDBInfoFileID uint32 = 5355080

var ClientDBInfoVTableClosure = []wire.VTable{
	{8, 24, 20, 4},
	{10, 28, 20, 4, 24},
	{8, 16, 12, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{12, 14, 12, 4, 13, 8},
	{30, 71, 36, 40, 4, 68, 44, 48, 52, 69, 56, 20, 60, 70, 64},
	{10, 13, 12, 4, 8},
	{10, 13, 4, 12, 8},
}

type ClientDBInfo struct {
	GrvProxies    []byte   // slot 0, ReadBytes
	CommitProxies []byte   // slot 1, ReadBytes
	Id            [16]byte // slot 2, ReadUID
	HasForward    bool     // slot 3, Optional, presence flag
	Forward       []byte   // slot 4, Optional, ReadBytes
	History       []byte   // slot 5, ReadBytes
	// TenantMode: nested struct at slot 6 — use ReadNestedReader(ClientDBInfoSlotTenantMode)
	HasEncryptKeyProxy bool     // slot 7, Optional, presence flag
	EncryptKeyProxy    []byte   // slot 8, Optional, ReadBytes
	ClusterId          [16]byte // slot 9, ReadUID
	ClusterType        uint32   // slot 10, ReadUint32
	HasMetaclusterName bool     // slot 11, Optional, presence flag
	MetaclusterName    []byte   // slot 12, Optional, ReadBytes
}

func (m *ClientDBInfo) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ClientDBInfoSlotGrvProxies) {
		m.GrvProxies = r.ReadBytes(ClientDBInfoSlotGrvProxies)
	}
	if r.FieldPresent(ClientDBInfoSlotCommitProxies) {
		m.CommitProxies = r.ReadBytes(ClientDBInfoSlotCommitProxies)
	}
	if r.FieldPresent(ClientDBInfoSlotId) {
		m.Id = r.ReadUID(ClientDBInfoSlotId)
	}
	if r.FieldPresent(ClientDBInfoSlotForward) && r.ReadUint8(ClientDBInfoSlotForward) > 0 {
		m.Forward = r.ReadBytes(ClientDBInfoSlotForward + 1)
		m.HasForward = true
	}
	if r.FieldPresent(ClientDBInfoSlotHistory) {
		m.History = r.ReadBytes(ClientDBInfoSlotHistory)
	}
	// TenantMode (slot 6): unknown nested struct
	if r.FieldPresent(ClientDBInfoSlotEncryptKeyProxy) && r.ReadUint8(ClientDBInfoSlotEncryptKeyProxy) > 0 {
		m.EncryptKeyProxy = r.ReadBytes(ClientDBInfoSlotEncryptKeyProxy + 1)
		m.HasEncryptKeyProxy = true
	}
	if r.FieldPresent(ClientDBInfoSlotClusterId) {
		m.ClusterId = r.ReadUID(ClientDBInfoSlotClusterId)
	}
	if r.FieldPresent(ClientDBInfoSlotClusterType) {
		m.ClusterType = r.ReadUint32(ClientDBInfoSlotClusterType)
	}
	if r.FieldPresent(ClientDBInfoSlotMetaclusterName) && r.ReadUint8(ClientDBInfoSlotMetaclusterName) > 0 {
		m.MetaclusterName = r.ReadBytes(ClientDBInfoSlotMetaclusterName + 1)
		m.HasMetaclusterName = true
	}
	return nil
}

func (m *ClientDBInfo) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ClientDBInfoSlotGrvProxies) {
		m.GrvProxies = r.ReadBytes(ClientDBInfoSlotGrvProxies)
	}
	if r.FieldPresent(ClientDBInfoSlotCommitProxies) {
		m.CommitProxies = r.ReadBytes(ClientDBInfoSlotCommitProxies)
	}
	if r.FieldPresent(ClientDBInfoSlotId) {
		m.Id = r.ReadUID(ClientDBInfoSlotId)
	}
	if r.FieldPresent(ClientDBInfoSlotForward) && r.ReadUint8(ClientDBInfoSlotForward) > 0 {
		m.Forward = r.ReadBytes(ClientDBInfoSlotForward + 1)
		m.HasForward = true
	}
	if r.FieldPresent(ClientDBInfoSlotHistory) {
		m.History = r.ReadBytes(ClientDBInfoSlotHistory)
	}
	// TenantMode (slot 6): unknown nested struct
	if r.FieldPresent(ClientDBInfoSlotEncryptKeyProxy) && r.ReadUint8(ClientDBInfoSlotEncryptKeyProxy) > 0 {
		m.EncryptKeyProxy = r.ReadBytes(ClientDBInfoSlotEncryptKeyProxy + 1)
		m.HasEncryptKeyProxy = true
	}
	if r.FieldPresent(ClientDBInfoSlotClusterId) {
		m.ClusterId = r.ReadUID(ClientDBInfoSlotClusterId)
	}
	if r.FieldPresent(ClientDBInfoSlotClusterType) {
		m.ClusterType = r.ReadUint32(ClientDBInfoSlotClusterType)
	}
	if r.FieldPresent(ClientDBInfoSlotMetaclusterName) && r.ReadUint8(ClientDBInfoSlotMetaclusterName) > 0 {
		m.MetaclusterName = r.ReadBytes(ClientDBInfoSlotMetaclusterName + 1)
		m.HasMetaclusterName = true
	}
}

func (m *ClientDBInfo) MarshalInto(obj *wire.ObjectWriter) {
	vt := ClientDBInfoVTable
	if len(m.GrvProxies) > 0 {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotGrvProxies+2]), m.GrvProxies)
	}
	if len(m.CommitProxies) > 0 {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotCommitProxies+2]), m.CommitProxies)
	}
	obj.WriteUID(int(vt[ClientDBInfoSlotId+2]), m.Id)
	if len(m.History) > 0 {
		obj.WriteRawOOL(int(vt[ClientDBInfoSlotHistory+2]), m.History)
	}
	obj.WriteUID(int(vt[ClientDBInfoSlotClusterId+2]), m.ClusterId)
	obj.WriteUint32(int(vt[ClientDBInfoSlotClusterType+2]), m.ClusterType)
}

func WriteClientDBInfo(obj *wire.ObjectWriter, parentOffset int, grvProxies []byte, commitProxies []byte, id [16]byte, history []byte, clusterId [16]byte, clusterType uint32) {
	m := ClientDBInfo{GrvProxies: grvProxies, CommitProxies: commitProxies, Id: id, History: history, ClusterId: clusterId, ClusterType: clusterType}
	obj.WriteStruct(parentOffset, ClientDBInfoVTable, 8, m.MarshalInto)
}

var ClientDBInfoTemplate = wire.NewMessageTemplate(
	ClientDBInfoFileID, ClientDBInfoVTable, 8, ClientDBInfoVTableClosure,
)
