// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"
	"math"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	ClientTagThrottleLimitsSlotTpsRate  = 0
	ClientTagThrottleLimitsSlotDuration = 1
)

var ClientTagThrottleLimitsVTable = wire.VTable{8, 20, 4, 12}

const ClientTagThrottleLimitsMaxAlign = 8

type ClientTagThrottleLimits struct {
	TpsRate  float64 // slot 0
	Duration float64 // slot 1
}

func (m *ClientTagThrottleLimits) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ClientTagThrottleLimitsSlotTpsRate) {
		m.TpsRate = r.ReadFloat64(ClientTagThrottleLimitsSlotTpsRate)
	}
	if r.FieldPresent(ClientTagThrottleLimitsSlotDuration) {
		m.Duration = r.ReadFloat64(ClientTagThrottleLimitsSlotDuration)
	}
}

func (m *ClientTagThrottleLimits) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ClientTagThrottleLimitsSlotTpsRate) {
		m.TpsRate = r.ReadFloat64(ClientTagThrottleLimitsSlotTpsRate)
	}
	if r.FieldPresent(ClientTagThrottleLimitsSlotDuration) {
		m.Duration = r.ReadFloat64(ClientTagThrottleLimitsSlotDuration)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *ClientTagThrottleLimits) precomputeSize(ps *wire.PrecomputeSize) int {
	{
		n := ps.GetMessageWriter(int(ClientTagThrottleLimitsVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ClientTagThrottleLimitsVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *ClientTagThrottleLimits) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	selfW := wb.GetMessageWriter(int(ClientTagThrottleLimitsVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := ClientTagThrottleLimitsVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(ClientTagThrottleLimitsVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], math.Float64bits(m.TpsRate))
		selfW.WriteScalar(b[:], int(vt[ClientTagThrottleLimitsSlotTpsRate+2]))
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], math.Float64bits(m.Duration))
		selfW.WriteScalar(b[:], int(vt[ClientTagThrottleLimitsSlotDuration+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

// ParseClientTagThrottleLimitsVectorFromReader reads a FlatBuffers vector of ClientTagThrottleLimits.
func ParseClientTagThrottleLimitsVectorFromReader(r *wire.Reader, slot int) []ClientTagThrottleLimits {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]ClientTagThrottleLimits, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem ClientTagThrottleLimits
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
