// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	CommitTransactionRequestSlotTransaction          = 0
	CommitTransactionRequestSlotReply                = 1
	CommitTransactionRequestSlotFlags                = 2
	CommitTransactionRequestSlotDebugID              = 3
	CommitTransactionRequestSlotCommitCostEstimation = 5
	CommitTransactionRequestSlotTagSet               = 7
	CommitTransactionRequestSlotSpanContext          = 9
	CommitTransactionRequestSlotTenantInfo           = 10
	CommitTransactionRequestSlotIdempotencyId        = 11
	CommitTransactionRequestSlotArena                = 12
)

var CommitTransactionRequestVTable = wire.VTable{28, 43, 4, 8, 12, 40, 16, 41, 20, 42, 24, 28, 32, 36}

const CommitTransactionRequestFileID uint32 = 93948

var CommitTransactionRequestVTableClosure = []wire.VTable{
	{8, 16, 12, 4},
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{12, 24, 12, 4, 16, 20},
	{24, 36, 12, 16, 20, 4, 32, 33, 34, 24, 35, 28},
	{8, 12, 4, 8},
	{10, 13, 12, 4, 8},
	{10, 29, 4, 20, 28},
	{28, 43, 4, 8, 12, 40, 16, 41, 20, 42, 24, 28, 32, 36},
}

var CommitTransactionRequestTemplate = wire.NewMessageTemplate(
	CommitTransactionRequestFileID, CommitTransactionRequestVTable, 4, CommitTransactionRequestVTableClosure,
)

const CommitTransactionRequestMaxAlign = 4

type CommitTransactionRequest struct {
	Transaction             CommitTransactionRef // slot 0, nested
	Reply                   ReplyPromise         // slot 1, nested
	Flags                   uint32               // slot 2
	HasDebugID              bool                 // slot 3, optional tag
	DebugID                 [16]byte             // slot 4, optional scalar value
	HasCommitCostEstimation bool                 // slot 5, optional tag
	CommitCostEstimation    []byte               // slot 6, optional value
	HasTagSet               bool                 // slot 7, optional tag
	TagSet                  []byte               // slot 8, optional value
	SpanContext             SpanContext          // slot 9, nested
	TenantInfo              TenantInfo           // slot 10, nested
	IdempotencyId           []byte               // slot 11
	Arena                   []byte               // slot 12
}

func (m *CommitTransactionRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotTransaction); err == nil {
		m.Transaction.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(CommitTransactionRequestSlotFlags) {
		m.Flags = r.ReadUint32(CommitTransactionRequestSlotFlags)
	}
	if r.FieldPresent(CommitTransactionRequestSlotDebugID) && r.ReadUint8(CommitTransactionRequestSlotDebugID) > 0 {
		copy(m.DebugID[:], r.ReadRelOffRaw(CommitTransactionRequestSlotDebugID+1, 16))
		m.HasDebugID = true
	}
	if r.FieldPresent(CommitTransactionRequestSlotCommitCostEstimation) && r.ReadUint8(CommitTransactionRequestSlotCommitCostEstimation) > 0 {
		m.CommitCostEstimation = r.ReadBytes(CommitTransactionRequestSlotCommitCostEstimation + 1)
		m.HasCommitCostEstimation = true
	}
	if r.FieldPresent(CommitTransactionRequestSlotTagSet) && r.ReadUint8(CommitTransactionRequestSlotTagSet) > 0 {
		m.TagSet = r.ReadBytes(CommitTransactionRequestSlotTagSet + 1)
		m.HasTagSet = true
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(CommitTransactionRequestSlotIdempotencyId) {
		m.IdempotencyId = r.ReadBytes(CommitTransactionRequestSlotIdempotencyId)
	}
	if r.FieldPresent(CommitTransactionRequestSlotArena) {
		m.Arena = r.ReadBytes(CommitTransactionRequestSlotArena)
	}
}

func (m *CommitTransactionRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotTransaction); err == nil {
		m.Transaction.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(CommitTransactionRequestSlotFlags) {
		m.Flags = r.ReadUint32(CommitTransactionRequestSlotFlags)
	}
	if r.FieldPresent(CommitTransactionRequestSlotDebugID) && r.ReadUint8(CommitTransactionRequestSlotDebugID) > 0 {
		copy(m.DebugID[:], r.ReadRelOffRaw(CommitTransactionRequestSlotDebugID+1, 16))
		m.HasDebugID = true
	}
	if r.FieldPresent(CommitTransactionRequestSlotCommitCostEstimation) && r.ReadUint8(CommitTransactionRequestSlotCommitCostEstimation) > 0 {
		m.CommitCostEstimation = r.ReadBytes(CommitTransactionRequestSlotCommitCostEstimation + 1)
		m.HasCommitCostEstimation = true
	}
	if r.FieldPresent(CommitTransactionRequestSlotTagSet) && r.ReadUint8(CommitTransactionRequestSlotTagSet) > 0 {
		m.TagSet = r.ReadBytes(CommitTransactionRequestSlotTagSet + 1)
		m.HasTagSet = true
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(CommitTransactionRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(CommitTransactionRequestSlotIdempotencyId) {
		m.IdempotencyId = r.ReadBytes(CommitTransactionRequestSlotIdempotencyId)
	}
	if r.FieldPresent(CommitTransactionRequestSlotArena) {
		m.Arena = r.ReadBytes(CommitTransactionRequestSlotArena)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *CommitTransactionRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Transaction.precomputeSize(ps)
	m.Reply.precomputeSize(ps)
	if m.HasDebugID {
		ps.Write(ps.CurrentBufferSize + 16)
	}
	if m.HasCommitCostEstimation {
		ps.VisitDynamicSize(len(m.CommitCostEstimation))
	}
	if m.HasTagSet {
		ps.VisitDynamicSize(len(m.TagSet))
	}
	m.SpanContext.precomputeSize(ps)
	m.TenantInfo.precomputeSize(ps)
	ps.VisitDynamicSize(len(m.IdempotencyId))
	{
		n := ps.GetMessageWriter(int(CommitTransactionRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(CommitTransactionRequestVTable[1])-4, 4)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *CommitTransactionRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var transactionStart int
	var replyStart int
	var debugIDOff int
	var commitCostEstimationOff int
	var tagSetOff int
	var spanContextStart int
	var tenantInfoStart int
	var idempotencyIdOff int
	transactionStart = m.Transaction.writeToBuffer(wb, vtableStart, tmpl)
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasDebugID {
		wb.Write(m.DebugID[:], wb.CurrentBufferSize+16)
		debugIDOff = wb.CurrentBufferSize
	}
	if m.HasCommitCostEstimation {
		commitCostEstimationOff, _ = wb.VisitDynamicSize(m.CommitCostEstimation)
	}
	if m.HasTagSet {
		tagSetOff, _ = wb.VisitDynamicSize(m.TagSet)
	}
	spanContextStart = m.SpanContext.writeToBuffer(wb, vtableStart, tmpl)
	tenantInfoStart = m.TenantInfo.writeToBuffer(wb, vtableStart, tmpl)
	idempotencyIdOff, _ = wb.VisitDynamicSize(m.IdempotencyId)
	selfW := wb.GetMessageWriter(int(CommitTransactionRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := CommitTransactionRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(CommitTransactionRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(m.Flags))
		selfW.WriteScalar(b[:], int(vt[CommitTransactionRequestSlotFlags+2]))
	}
	selfW.WriteRelativeOffset(transactionStart, int(vt[CommitTransactionRequestSlotTransaction+2]))
	selfW.WriteRelativeOffset(replyStart, int(vt[CommitTransactionRequestSlotReply+2]))
	if m.HasDebugID {
		selfW.WriteScalar([]byte{1}, int(vt[CommitTransactionRequestSlotDebugID+2]))
		selfW.WriteRelativeOffset(debugIDOff, int(vt[CommitTransactionRequestSlotDebugID+1+2]))
	}
	if m.HasCommitCostEstimation {
		selfW.WriteScalar([]byte{1}, int(vt[CommitTransactionRequestSlotCommitCostEstimation+2]))
		selfW.WriteRelativeOffset(commitCostEstimationOff, int(vt[CommitTransactionRequestSlotCommitCostEstimation+1+2]))
	}
	if m.HasTagSet {
		selfW.WriteScalar([]byte{1}, int(vt[CommitTransactionRequestSlotTagSet+2]))
		selfW.WriteRelativeOffset(tagSetOff, int(vt[CommitTransactionRequestSlotTagSet+1+2]))
	}
	selfW.WriteRelativeOffset(spanContextStart, int(vt[CommitTransactionRequestSlotSpanContext+2]))
	selfW.WriteRelativeOffset(tenantInfoStart, int(vt[CommitTransactionRequestSlotTenantInfo+2]))
	selfW.WriteRelativeOffset(idempotencyIdOff, int(vt[CommitTransactionRequestSlotIdempotencyId+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *CommitTransactionRequest) MarshalFDB() []byte {
	t := CommitTransactionRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], CommitTransactionRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *CommitTransactionRequest) MarshalFDBPooled(dst []byte) []byte {
	t := CommitTransactionRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], CommitTransactionRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseCommitTransactionRequestVectorFromReader reads a FlatBuffers vector of CommitTransactionRequest.
func ParseCommitTransactionRequestVectorFromReader(r *wire.Reader, slot int) []CommitTransactionRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]CommitTransactionRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem CommitTransactionRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
