// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	EndpointSlotAddresses = 0
	EndpointSlotToken     = 1
)

var EndpointVTable = wire.VTable{8, 24, 20, 4}

const EndpointFileID uint32 = 10618805

var EndpointVTableClosure = []wire.VTable{
	{8, 24, 20, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{10, 13, 4, 12, 8},
}
var EndpointTemplate = wire.NewMessageTemplate(
	EndpointFileID, EndpointVTable, 8, EndpointVTableClosure,
)

const EndpointMaxAlign = 8

type Endpoint struct {
	Addresses NetworkAddressList // slot 0, nested
	Token     [16]byte           // slot 1
}

func (m *Endpoint) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(EndpointSlotAddresses); err == nil {
		m.Addresses.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(EndpointSlotToken) {
		m.Token = r.ReadUID(EndpointSlotToken)
	}
}

func (m *Endpoint) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(EndpointSlotAddresses); err == nil {
		m.Addresses.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(EndpointSlotToken) {
		m.Token = r.ReadUID(EndpointSlotToken)
	}
	return nil
}

func (m *Endpoint) blobSize() int {
	vt := EndpointVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	return (oolPos + oolSize + 3) &^ 3
}

func (m *Endpoint) writeBlob(buf []byte, pos int) int {
	vt := EndpointVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	copy(obj[int(vt[EndpointSlotToken+2]):], m.Token[:])
	return curOOL - pos
}

func (m *Endpoint) measureEndOff(endOff int) int {
	endOff = m.Addresses.measureEndOff(endOff)
	endOff = wire.MeasureObject(endOff, EndpointVTable, EndpointMaxAlign)
	return endOff
}

func (m *Endpoint) writeDirect(dw *wire.DirectWriter) int {
	addressesPos := m.Addresses.writeDirect(dw)
	objPos, obj := dw.WriteObject(EndpointVTable, EndpointMaxAlign)
	vt := EndpointVTable
	copy(obj[int(vt[EndpointSlotToken+2]):], m.Token[:])
	wire.PatchRelOff(obj, int(vt[EndpointSlotAddresses+2]), objPos, addressesPos)
	return objPos
}

func (m *Endpoint) MarshalFDB() []byte {
	t := EndpointTemplate
	endOff := 0
	endOff = m.Addresses.measureEndOff(endOff)
	bodySize := int(EndpointVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 8 - 1) &^ (8 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseEndpointVectorFromReader reads a FlatBuffers vector of Endpoint.
func ParseEndpointVectorFromReader(r *wire.Reader, slot int) []Endpoint {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]Endpoint, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem Endpoint
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
