// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	ErrorSlotErrorCode = 0
)

var ErrorVTable = wire.VTable{6, 6, 4}

const ErrorFileID uint32 = 14065384

var ErrorVTableClosure = []wire.VTable{
	{6, 6, 4},
	{6, 8, 4},
}

var ErrorTemplate = wire.NewMessageTemplate(
	ErrorFileID, ErrorVTable, 4, ErrorVTableClosure,
)

const ErrorMaxAlign = 4

type Error struct {
	ErrorCode uint16 // slot 0
}

func (m *Error) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
}

func (m *Error) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *Error) precomputeSize(ps *wire.PrecomputeSize) int {
	{
		n := ps.GetMessageWriter(int(ErrorVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ErrorVTable[1])-4, 4)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *Error) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	selfW := wb.GetMessageWriter(int(ErrorVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := ErrorVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(ErrorVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [2]byte
		binary.LittleEndian.PutUint16(b[:], uint16(m.ErrorCode))
		selfW.WriteScalar(b[:], int(vt[ErrorSlotErrorCode+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *Error) MarshalFDB() []byte {
	t := ErrorTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], ErrorFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *Error) MarshalFDBPooled(dst []byte) []byte {
	t := ErrorTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], ErrorFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseErrorVectorFromReader reads a FlatBuffers vector of Error.
func ParseErrorVectorFromReader(r *wire.Reader, slot int) []Error {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]Error, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem Error
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
