// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetKeyValuesRequestSlotBegin                  = 0
	GetKeyValuesRequestSlotEnd                    = 1
	GetKeyValuesRequestSlotVersion                = 2
	GetKeyValuesRequestSlotLimit                  = 3
	GetKeyValuesRequestSlotLimitBytes             = 4
	GetKeyValuesRequestSlotTags                   = 5
	GetKeyValuesRequestSlotReply                  = 7
	GetKeyValuesRequestSlotSpanContext            = 8
	GetKeyValuesRequestSlotTenantInfo             = 9
	GetKeyValuesRequestSlotOptions                = 10
	GetKeyValuesRequestSlotSsLatestCommitVersions = 12
	GetKeyValuesRequestSlotArena                  = 13
)

var GetKeyValuesRequestVTable = wire.VTable{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48}

const GetKeyValuesRequestFileID uint32 = 6795746

var GetKeyValuesRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 13, 4, 12, 8},
	{10, 29, 4, 20, 28},
	{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48},
}

var GetKeyValuesRequestTemplate = wire.NewMessageTemplate(
	GetKeyValuesRequestFileID, GetKeyValuesRequestVTable, 8, GetKeyValuesRequestVTableClosure,
)

const GetKeyValuesRequestMaxAlign = 8

type GetKeyValuesRequest struct {
	Begin                  KeySelectorRef // slot 0, nested
	End                    KeySelectorRef // slot 1, nested
	Version                int64          // slot 2
	Limit                  int32          // slot 3
	LimitBytes             int32          // slot 4
	HasTags                bool           // slot 5, optional tag
	Tags                   []byte         // slot 6, optional value
	Reply                  ReplyPromise   // slot 7, nested
	SpanContext            SpanContext    // slot 8, nested
	TenantInfo             TenantInfo     // slot 9, nested
	HasOptions             bool           // slot 10, optional tag
	Options                ReadOptions    // slot 11, optional nested value
	SsLatestCommitVersions []byte         // slot 12
	Arena                  []byte         // slot 13
}

func (m *GetKeyValuesRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyValuesRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimitBytes) {
		m.LimitBytes = r.ReadInt32(GetKeyValuesRequestSlotLimitBytes)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotTags) && r.ReadUint8(GetKeyValuesRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyValuesRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotOptions) && r.ReadUint8(GetKeyValuesRequestSlotOptions) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotOptions + 1); err == nil {
			m.Options.UnmarshalFromReader(nr)
		}
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyValuesRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyValuesRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesRequestSlotArena)
	}
}

func (m *GetKeyValuesRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyValuesRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimitBytes) {
		m.LimitBytes = r.ReadInt32(GetKeyValuesRequestSlotLimitBytes)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotTags) && r.ReadUint8(GetKeyValuesRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyValuesRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotOptions) && r.ReadUint8(GetKeyValuesRequestSlotOptions) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotOptions + 1); err == nil {
			m.Options.UnmarshalFromReader(nr)
		}
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyValuesRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyValuesRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesRequestSlotArena)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetKeyValuesRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Begin.precomputeSize(ps)
	m.End.precomputeSize(ps)
	if m.HasTags {
		ps.VisitDynamicSize(len(m.Tags))
	}
	m.Reply.precomputeSize(ps)
	m.SpanContext.precomputeSize(ps)
	m.TenantInfo.precomputeSize(ps)
	if m.HasOptions {
		m.Options.precomputeSize(ps)
	}
	ps.VisitDynamicSize(len(m.SsLatestCommitVersions))
	{
		n := ps.GetMessageWriter(int(GetKeyValuesRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetKeyValuesRequestVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetKeyValuesRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var beginStart int
	var endStart int
	var tagsOff int
	var replyStart int
	var spanContextStart int
	var tenantInfoStart int
	var optionsOff int
	var ssLatestCommitVersionsOff int
	beginStart = m.Begin.writeToBuffer(wb, vtableStart, tmpl)
	endStart = m.End.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasTags {
		tagsOff, _ = wb.VisitDynamicSize(m.Tags)
	}
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	spanContextStart = m.SpanContext.writeToBuffer(wb, vtableStart, tmpl)
	tenantInfoStart = m.TenantInfo.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasOptions {
		optionsOff = m.Options.writeToBuffer(wb, vtableStart, tmpl)
	}
	ssLatestCommitVersionsOff, _ = wb.VisitDynamicSize(m.SsLatestCommitVersions)
	selfW := wb.GetMessageWriter(int(GetKeyValuesRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetKeyValuesRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetKeyValuesRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.Version))
		selfW.WriteScalar(b[:], int(vt[GetKeyValuesRequestSlotVersion+2]))
	}
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(m.Limit))
		selfW.WriteScalar(b[:], int(vt[GetKeyValuesRequestSlotLimit+2]))
	}
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(m.LimitBytes))
		selfW.WriteScalar(b[:], int(vt[GetKeyValuesRequestSlotLimitBytes+2]))
	}
	selfW.WriteRelativeOffset(beginStart, int(vt[GetKeyValuesRequestSlotBegin+2]))
	selfW.WriteRelativeOffset(endStart, int(vt[GetKeyValuesRequestSlotEnd+2]))
	if m.HasTags {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyValuesRequestSlotTags+2]))
		selfW.WriteRelativeOffset(tagsOff, int(vt[GetKeyValuesRequestSlotTags+1+2]))
	}
	selfW.WriteRelativeOffset(replyStart, int(vt[GetKeyValuesRequestSlotReply+2]))
	selfW.WriteRelativeOffset(spanContextStart, int(vt[GetKeyValuesRequestSlotSpanContext+2]))
	selfW.WriteRelativeOffset(tenantInfoStart, int(vt[GetKeyValuesRequestSlotTenantInfo+2]))
	if m.HasOptions {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyValuesRequestSlotOptions+2]))
		selfW.WriteRelativeOffset(optionsOff, int(vt[GetKeyValuesRequestSlotOptions+1+2]))
	}
	selfW.WriteRelativeOffset(ssLatestCommitVersionsOff, int(vt[GetKeyValuesRequestSlotSsLatestCommitVersions+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *GetKeyValuesRequest) MarshalFDB() []byte {
	t := GetKeyValuesRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyValuesRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *GetKeyValuesRequest) MarshalFDBPooled(dst []byte) []byte {
	t := GetKeyValuesRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyValuesRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseGetKeyValuesRequestVectorFromReader reads a FlatBuffers vector of GetKeyValuesRequest.
func ParseGetKeyValuesRequestVectorFromReader(r *wire.Reader, slot int) []GetKeyValuesRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetKeyValuesRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetKeyValuesRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
