// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"
	"math"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetKeyReplySlotPenalty = 0
	GetKeyReplySlotError = 1
	GetKeyReplySlotSel = 3
	GetKeyReplySlotCached = 4
)

var GetKeyReplyVTable = wire.VTable{14, 22, 4, 20, 12, 16, 21}
const GetKeyReplyFileID uint32 = 11226513
var GetKeyReplyVTableClosure = []wire.VTable{
	{6, 8, 4},
	{6, 6, 4},
	{10, 13, 4, 12, 8},
	{14, 22, 4, 20, 12, 16, 21},
}
var GetKeyReplyTemplate = wire.NewMessageTemplate(
	GetKeyReplyFileID, GetKeyReplyVTable, 8, GetKeyReplyVTableClosure,
)
const GetKeyReplyMaxAlign = 8

type GetKeyReply struct {
	Penalty float64 // slot 0
	HasError bool   // slot 1, optional tag
	Error    []byte // slot 2, optional value
	// Sel: unregistered nested struct at slot 3
	Cached bool // slot 4
}

func (m *GetKeyReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
}

func (m *GetKeyReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
	return nil
}

func (m *GetKeyReply) blobSize() int {
	vt := GetKeyReplyVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetKeyReply) writeBlob(buf []byte, pos int) int {
	vt := GetKeyReplyVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyReplySlotPenalty+2]):], math.Float64bits(m.Penalty))
	if m.Cached { obj[int(vt[GetKeyReplySlotCached+2])] = 1 }
	return curOOL - pos
}

func (m *GetKeyReply) measureEndOff(endOff int) int {
	if m.HasError {
		endOff = wire.MeasureBytesOOL(endOff, m.Error)
	}
	endOff = wire.MeasureObject(endOff, GetKeyReplyVTable, GetKeyReplyMaxAlign)
	return endOff
}

func (m *GetKeyReply) writeDirect(dw *wire.DirectWriter) int {
	var error_OOL int
	if m.HasError {
		error_OOL = dw.WriteBytesOOL(m.Error)
	}
	objPos, obj := dw.WriteObject(GetKeyReplyVTable, GetKeyReplyMaxAlign)
	vt := GetKeyReplyVTable
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyReplySlotPenalty+2]):], math.Float64bits(m.Penalty))
	if m.Cached {
		obj[int(vt[GetKeyReplySlotCached+2])] = 1
	}
	if m.HasError {
		obj[int(vt[GetKeyReplySlotError+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetKeyReplySlotError+1+2]), objPos, error_OOL)
	}
	return objPos
}

func (m *GetKeyReply) MarshalFDB() []byte {
	t := GetKeyReplyTemplate
	endOff := 0
	if m.HasError {
		endOff = wire.MeasureBytesOOL(endOff, m.Error)
	}
	bodySize := int(GetKeyReplyVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 8 - 1) &^ (8 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseGetKeyReplyVectorFromReader reads a FlatBuffers vector of GetKeyReply.
func ParseGetKeyReplyVectorFromReader(r *wire.Reader, slot int) []GetKeyReply {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]GetKeyReply, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem GetKeyReply
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

