// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// GetKeyValuesReply fields:
//
//	slot 0: LoadBalancedReply::penalty — scalar, size=8, align=8
//	slot 1: LoadBalancedReply::error — union_like, size=4, align=4, indirection
//	slot 3: data — dynamic_size, size=4, align=4, indirection
//	slot 4: version — scalar, size=8, align=8
//	slot 5: more — scalar, size=1, align=1
//	slot 6: cached — scalar, size=1, align=1
//	slot 7: arena — scalar, size=0, align=1
const (
	GetKeyValuesReplySlotPenalty = 0
	GetKeyValuesReplySlotError   = 1
	GetKeyValuesReplySlotData    = 3
	GetKeyValuesReplySlotVersion = 4
	GetKeyValuesReplySlotMore    = 5
	GetKeyValuesReplySlotCached  = 6
	GetKeyValuesReplySlotArena   = 7
)

var GetKeyValuesReplyVTable = wire.VTable{18, 31, 4, 28, 20, 24, 12, 29, 30}

const GetKeyValuesReplyFileID uint32 = 1783066

var GetKeyValuesReplyVTableClosure = []wire.VTable{
	{6, 8, 4},
	{6, 6, 4},
	{18, 31, 4, 28, 20, 24, 12, 29, 30},
}

type GetKeyValuesReply struct {
	Penalty  float64 // slot 0, ReadFloat64
	HasError bool    // slot 1, Optional, presence flag
	Error    []byte  // slot 2, Optional, ReadBytes
	Data     []byte  // slot 3, ReadBytes
	Version  int64   // slot 4, ReadInt64
	More     bool    // slot 5, ReadBool
	Cached   bool    // slot 6, ReadBool
	Arena    []byte  // slot 7, ReadBytes
}

func (m *GetKeyValuesReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetKeyValuesReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyValuesReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyValuesReplySlotError) && r.ReadUint8(GetKeyValuesReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyValuesReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyValuesReplySlotData) {
		m.Data = r.ReadBytes(GetKeyValuesReplySlotData)
	}
	if r.FieldPresent(GetKeyValuesReplySlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesReplySlotVersion)
	}
	if r.FieldPresent(GetKeyValuesReplySlotMore) {
		m.More = r.ReadBool(GetKeyValuesReplySlotMore)
	}
	if r.FieldPresent(GetKeyValuesReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyValuesReplySlotCached)
	}
	if r.FieldPresent(GetKeyValuesReplySlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesReplySlotArena)
	}
	return nil
}

func (m *GetKeyValuesReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetKeyValuesReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyValuesReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyValuesReplySlotError) && r.ReadUint8(GetKeyValuesReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyValuesReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyValuesReplySlotData) {
		m.Data = r.ReadBytes(GetKeyValuesReplySlotData)
	}
	if r.FieldPresent(GetKeyValuesReplySlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesReplySlotVersion)
	}
	if r.FieldPresent(GetKeyValuesReplySlotMore) {
		m.More = r.ReadBool(GetKeyValuesReplySlotMore)
	}
	if r.FieldPresent(GetKeyValuesReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyValuesReplySlotCached)
	}
	if r.FieldPresent(GetKeyValuesReplySlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesReplySlotArena)
	}
}

func (m *GetKeyValuesReply) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetKeyValuesReplyVTable
	obj.WriteFloat64(int(vt[GetKeyValuesReplySlotPenalty+2]), m.Penalty)
	if len(m.Data) > 0 {
		obj.WriteBytes(int(vt[GetKeyValuesReplySlotData+2]), m.Data)
	}
	obj.WriteInt64(int(vt[GetKeyValuesReplySlotVersion+2]), m.Version)
	obj.WriteBool(int(vt[GetKeyValuesReplySlotMore+2]), m.More)
	obj.WriteBool(int(vt[GetKeyValuesReplySlotCached+2]), m.Cached)
}

func WriteGetKeyValuesReply(obj *wire.ObjectWriter, parentOffset int, penalty float64, data []byte, version int64, more bool, cached bool) {
	m := GetKeyValuesReply{Penalty: penalty, Data: data, Version: version, More: more, Cached: cached}
	obj.WriteStruct(parentOffset, GetKeyValuesReplyVTable, 8, m.MarshalInto)
}

func MarshalGetKeyValuesReply(penalty float64, data []byte, version int64, more bool, cached bool) []byte {
	m := GetKeyValuesReply{Penalty: penalty, Data: data, Version: version, More: more, Cached: cached}
	return wire.MarshalStructBlob(GetKeyValuesReplyVTable, m.MarshalInto)
}

func (m *GetKeyValuesReply) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(GetKeyValuesReplyTemplate, func(obj *wire.ObjectWriter) {
		obj.WriteFloat64(int(GetKeyValuesReplyVTable[GetKeyValuesReplySlotPenalty+2]), m.Penalty)
		if len(m.Data) > 0 {
			obj.WriteBytes(int(GetKeyValuesReplyVTable[GetKeyValuesReplySlotData+2]), m.Data)
		}
		obj.WriteInt64(int(GetKeyValuesReplyVTable[GetKeyValuesReplySlotVersion+2]), m.Version)
		obj.WriteBool(int(GetKeyValuesReplyVTable[GetKeyValuesReplySlotMore+2]), m.More)
		obj.WriteBool(int(GetKeyValuesReplyVTable[GetKeyValuesReplySlotCached+2]), m.Cached)
	})
}

var GetKeyValuesReplyTemplate = wire.NewMessageTemplate(
	GetKeyValuesReplyFileID, GetKeyValuesReplyVTable, 8, GetKeyValuesReplyVTableClosure,
)
