// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	GetKeyServerLocationsRequestSlotBegin            = 0
	GetKeyServerLocationsRequestSlotEnd              = 1
	GetKeyServerLocationsRequestSlotLimit            = 3
	GetKeyServerLocationsRequestSlotReverse          = 4
	GetKeyServerLocationsRequestSlotReply            = 5
	GetKeyServerLocationsRequestSlotSpanContext      = 6
	GetKeyServerLocationsRequestSlotTenant           = 7
	GetKeyServerLocationsRequestSlotMinTenantVersion = 8
	GetKeyServerLocationsRequestSlotArena            = 9
)

var GetKeyServerLocationsRequestVTable = wire.VTable{22, 38, 12, 36, 16, 20, 37, 24, 28, 32, 4}

const GetKeyServerLocationsRequestFileID uint32 = 9144680

var GetKeyServerLocationsRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{10, 29, 4, 20, 28},
	{22, 38, 12, 36, 16, 20, 37, 24, 28, 32, 4},
}
var GetKeyServerLocationsRequestTemplate = wire.NewMessageTemplate(
	GetKeyServerLocationsRequestFileID, GetKeyServerLocationsRequestVTable, 8, GetKeyServerLocationsRequestVTableClosure,
)

type GetKeyServerLocationsRequest struct {
	Begin            []byte       // slot 0
	HasEnd           bool         // slot 1, optional tag
	End              []byte       // slot 2, optional value
	Limit            int32        // slot 3
	Reverse          bool         // slot 4
	Reply            ReplyPromise // slot 5, nested
	SpanContext      SpanContext  // slot 6, nested
	Tenant           TenantInfo   // slot 7, nested
	MinTenantVersion int64        // slot 8
	Arena            []byte       // slot 9
}

func (m *GetKeyServerLocationsRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetKeyServerLocationsRequestSlotBegin) {
		m.Begin = r.ReadBytes(GetKeyServerLocationsRequestSlotBegin)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotEnd) && r.ReadUint8(GetKeyServerLocationsRequestSlotEnd) > 0 {
		m.End = r.ReadBytes(GetKeyServerLocationsRequestSlotEnd + 1)
		m.HasEnd = true
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyServerLocationsRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotReverse) {
		m.Reverse = r.ReadBool(GetKeyServerLocationsRequestSlotReverse)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotTenant); err == nil {
		m.Tenant.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotMinTenantVersion) {
		m.MinTenantVersion = r.ReadInt64(GetKeyServerLocationsRequestSlotMinTenantVersion)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyServerLocationsRequestSlotArena)
	}
}

func (m *GetKeyServerLocationsRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotBegin) {
		m.Begin = r.ReadBytes(GetKeyServerLocationsRequestSlotBegin)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotEnd) && r.ReadUint8(GetKeyServerLocationsRequestSlotEnd) > 0 {
		m.End = r.ReadBytes(GetKeyServerLocationsRequestSlotEnd + 1)
		m.HasEnd = true
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyServerLocationsRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotReverse) {
		m.Reverse = r.ReadBool(GetKeyServerLocationsRequestSlotReverse)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyServerLocationsRequestSlotTenant); err == nil {
		m.Tenant.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotMinTenantVersion) {
		m.MinTenantVersion = r.ReadInt64(GetKeyServerLocationsRequestSlotMinTenantVersion)
	}
	if r.FieldPresent(GetKeyServerLocationsRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyServerLocationsRequestSlotArena)
	}
	return nil
}

func (m *GetKeyServerLocationsRequest) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetKeyServerLocationsRequestVTable
	if m.Begin != nil {
		obj.WriteBytes(int(vt[GetKeyServerLocationsRequestSlotBegin+2]), m.Begin)
	}
	obj.WriteInt32(int(vt[GetKeyServerLocationsRequestSlotLimit+2]), m.Limit)
	obj.WriteBool(int(vt[GetKeyServerLocationsRequestSlotReverse+2]), m.Reverse)
	obj.WriteStruct(int(vt[GetKeyServerLocationsRequestSlotReply+2]), ReplyPromiseVTable, 8, m.Reply.MarshalInto)
	obj.WriteStruct(int(vt[GetKeyServerLocationsRequestSlotSpanContext+2]), SpanContextVTable, 8, m.SpanContext.MarshalInto)
	obj.WriteStruct(int(vt[GetKeyServerLocationsRequestSlotTenant+2]), TenantInfoVTable, 8, m.Tenant.MarshalInto)
	obj.WriteInt64(int(vt[GetKeyServerLocationsRequestSlotMinTenantVersion+2]), m.MinTenantVersion)
}

func (m *GetKeyServerLocationsRequest) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(GetKeyServerLocationsRequestTemplate, m.MarshalInto)
}

func WriteGetKeyServerLocationsRequest(obj *wire.ObjectWriter, parentOffset int, begin []byte, limit int32, reverse bool, minTenantVersion int64) {
	m := GetKeyServerLocationsRequest{Begin: begin, Limit: limit, Reverse: reverse, MinTenantVersion: minTenantVersion}
	obj.WriteStruct(parentOffset, GetKeyServerLocationsRequestVTable, 8, m.MarshalInto)
}

func MarshalGetKeyServerLocationsRequest(begin []byte, limit int32, reverse bool, minTenantVersion int64) []byte {
	m := GetKeyServerLocationsRequest{Begin: begin, Limit: limit, Reverse: reverse, MinTenantVersion: minTenantVersion}
	return wire.MarshalStructBlob(GetKeyServerLocationsRequestVTable, m.MarshalInto)
}

// ParseGetKeyServerLocationsRequestVectorFromReader reads a FlatBuffers vector of GetKeyServerLocationsRequest.
func ParseGetKeyServerLocationsRequestVectorFromReader(r *wire.Reader, slot int) []GetKeyServerLocationsRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetKeyServerLocationsRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetKeyServerLocationsRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
