// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// GetKeyServerLocationsReply fields:
//
//	slot 0: results — vector_like, size=4, align=4, indirection
//	slot 1: resultsTssMapping — vector_like, size=4, align=4, indirection
//	slot 2: resultsTagMapping — vector_like, size=4, align=4, indirection
//	slot 3: arena — scalar, size=0, align=1
const (
	GetKeyServerLocationsReplySlotResults           = 0
	GetKeyServerLocationsReplySlotResultsTssMapping = 1
	GetKeyServerLocationsReplySlotResultsTagMapping = 2
	GetKeyServerLocationsReplySlotArena             = 3
)

var GetKeyServerLocationsReplyVTable = wire.VTable{10, 16, 4, 8, 12}

const GetKeyServerLocationsReplyFileID uint32 = 10636023

var GetKeyServerLocationsReplyVTableClosure = []wire.VTable{
	{8, 24, 20, 4},
	{8, 24, 4, 20},
	{8, 24, 4, 20},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{16, 34, 4, 20, 24, 32, 28, 33},
	{8, 12, 4, 8},
	{10, 13, 4, 12, 8},
	{10, 16, 4, 8, 12},
}

type GetKeyServerLocationsReply struct {
	Results           []byte // slot 0, ReadBytes
	ResultsTssMapping []byte // slot 1, ReadBytes
	ResultsTagMapping []byte // slot 2, ReadBytes
	Arena             []byte // slot 3, ReadBytes
}

func (m *GetKeyServerLocationsReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetKeyServerLocationsReplySlotResults) {
		m.Results = r.ReadBytes(GetKeyServerLocationsReplySlotResults)
	}
	if r.FieldPresent(GetKeyServerLocationsReplySlotResultsTssMapping) {
		m.ResultsTssMapping = r.ReadBytes(GetKeyServerLocationsReplySlotResultsTssMapping)
	}
	if r.FieldPresent(GetKeyServerLocationsReplySlotResultsTagMapping) {
		m.ResultsTagMapping = r.ReadBytes(GetKeyServerLocationsReplySlotResultsTagMapping)
	}
	if r.FieldPresent(GetKeyServerLocationsReplySlotArena) {
		m.Arena = r.ReadBytes(GetKeyServerLocationsReplySlotArena)
	}
	return nil
}

func (m *GetKeyServerLocationsReply) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetKeyServerLocationsReplyVTable
	obj.WriteBytes(int(vt[GetKeyServerLocationsReplySlotResults+2]), m.Results)
	obj.WriteBytes(int(vt[GetKeyServerLocationsReplySlotResultsTssMapping+2]), m.ResultsTssMapping)
	obj.WriteBytes(int(vt[GetKeyServerLocationsReplySlotResultsTagMapping+2]), m.ResultsTagMapping)
	obj.WriteBytes(int(vt[GetKeyServerLocationsReplySlotArena+2]), m.Arena)
}

func (m *GetKeyServerLocationsReply) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(GetKeyServerLocationsReplyTemplate, func(obj *wire.ObjectWriter) {
		obj.WriteBytes(int(GetKeyServerLocationsReplyVTable[GetKeyServerLocationsReplySlotResults+2]), m.Results)
		obj.WriteBytes(int(GetKeyServerLocationsReplyVTable[GetKeyServerLocationsReplySlotResultsTssMapping+2]), m.ResultsTssMapping)
		obj.WriteBytes(int(GetKeyServerLocationsReplyVTable[GetKeyServerLocationsReplySlotResultsTagMapping+2]), m.ResultsTagMapping)
		obj.WriteBytes(int(GetKeyServerLocationsReplyVTable[GetKeyServerLocationsReplySlotArena+2]), m.Arena)
	})
}

var GetKeyServerLocationsReplyTemplate = wire.NewMessageTemplate(
	GetKeyServerLocationsReplyFileID, GetKeyServerLocationsReplyVTable, 4, GetKeyServerLocationsReplyVTableClosure,
)
