// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetKeyRequestSlotSel = 0
	GetKeyRequestSlotVersion = 1
	GetKeyRequestSlotTags = 2
	GetKeyRequestSlotReply = 4
	GetKeyRequestSlotSpanContext = 5
	GetKeyRequestSlotTenantInfo = 6
	GetKeyRequestSlotOptions = 7
	GetKeyRequestSlotSsLatestCommitVersions = 9
	GetKeyRequestSlotField_10 = 10
)

var GetKeyRequestVTable = wire.VTable{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36}
const GetKeyRequestFileID uint32 = 10457870
var GetKeyRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 13, 4, 12, 8},
	{10, 29, 4, 20, 28},
	{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36},
}
var GetKeyRequestTemplate = wire.NewMessageTemplate(
	GetKeyRequestFileID, GetKeyRequestVTable, 8, GetKeyRequestVTableClosure,
)
const GetKeyRequestMaxAlign = 8

type GetKeyRequest struct {
	Sel KeySelectorRef // slot 0, nested
	Version int64 // slot 1
	HasTags bool   // slot 2, optional tag
	Tags    []byte // slot 3, optional value
	Reply ReplyPromise // slot 4, nested
	SpanContext SpanContext // slot 5, nested
	TenantInfo TenantInfo // slot 6, nested
	HasOptions bool   // slot 7, optional tag
	Options    []byte // slot 8, optional value
	SsLatestCommitVersions []byte // slot 9
	Field_10 []byte // slot 10
}

func (m *GetKeyRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSel); err == nil {
		m.Sel.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyRequestSlotTags) && r.ReadUint8(GetKeyRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotOptions) && r.ReadUint8(GetKeyRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetKeyRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyRequestSlotField_10) {
		m.Field_10 = r.ReadBytes(GetKeyRequestSlotField_10)
	}
}

func (m *GetKeyRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSel); err == nil {
		m.Sel.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyRequestSlotTags) && r.ReadUint8(GetKeyRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotOptions) && r.ReadUint8(GetKeyRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetKeyRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyRequestSlotField_10) {
		m.Field_10 = r.ReadBytes(GetKeyRequestSlotField_10)
	}
	return nil
}

func (m *GetKeyRequest) blobSize() int {
	vt := GetKeyRequestVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.SsLatestCommitVersions != nil { oolSize += (4 + len(m.SsLatestCommitVersions) + 3) &^ 3 }
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetKeyRequest) writeBlob(buf []byte, pos int) int {
	vt := GetKeyRequestVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyRequestSlotVersion+2]):], uint64(m.Version))
	if m.SsLatestCommitVersions != nil {
		binary.LittleEndian.PutUint32(buf[curOOL:], uint32(len(m.SsLatestCommitVersions)))
		copy(buf[curOOL+4:], m.SsLatestCommitVersions)
		wire.PatchBlobRelOff(obj, int(vt[GetKeyRequestSlotSsLatestCommitVersions+2]), objPos, curOOL)
		curOOL += (4 + len(m.SsLatestCommitVersions) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *GetKeyRequest) measureEndOff(endOff int) int {
	if m.HasTags {
		endOff = wire.MeasureBytesOOL(endOff, m.Tags)
	}
	if m.HasOptions {
		endOff = wire.MeasureBytesOOL(endOff, m.Options)
	}
	endOff = wire.MeasureBytesOOL(endOff, m.SsLatestCommitVersions)
	endOff = m.Sel.measureEndOff(endOff)
	endOff = m.Reply.measureEndOff(endOff)
	endOff = m.SpanContext.measureEndOff(endOff)
	endOff = m.TenantInfo.measureEndOff(endOff)
	endOff = wire.MeasureObject(endOff, GetKeyRequestVTable, GetKeyRequestMaxAlign)
	return endOff
}

func (m *GetKeyRequest) writeDirect(dw *wire.DirectWriter) int {
	var tagsOOL int
	if m.HasTags {
		tagsOOL = dw.WriteBytesOOL(m.Tags)
	}
	var optionsOOL int
	if m.HasOptions {
		optionsOOL = dw.WriteBytesOOL(m.Options)
	}
	ssLatestCommitVersionsOOL := dw.WriteBytesOOL(m.SsLatestCommitVersions)
	selPos := m.Sel.writeDirect(dw)
	replyPos := m.Reply.writeDirect(dw)
	spanContextPos := m.SpanContext.writeDirect(dw)
	tenantInfoPos := m.TenantInfo.writeDirect(dw)
	objPos, obj := dw.WriteObject(GetKeyRequestVTable, GetKeyRequestMaxAlign)
	vt := GetKeyRequestVTable
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyRequestSlotVersion+2]):], uint64(m.Version))
	if m.HasTags {
		obj[int(vt[GetKeyRequestSlotTags+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotTags+1+2]), objPos, tagsOOL)
	}
	if m.HasOptions {
		obj[int(vt[GetKeyRequestSlotOptions+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotOptions+1+2]), objPos, optionsOOL)
	}
	wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotSsLatestCommitVersions+2]), objPos, ssLatestCommitVersionsOOL)
	wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotSel+2]), objPos, selPos)
	wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotReply+2]), objPos, replyPos)
	wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotSpanContext+2]), objPos, spanContextPos)
	wire.PatchRelOff(obj, int(vt[GetKeyRequestSlotTenantInfo+2]), objPos, tenantInfoPos)
	return objPos
}

func (m *GetKeyRequest) MarshalFDB() []byte {
	t := GetKeyRequestTemplate
	packedVT := t.PackedVTables()
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	if m.HasTags { ps.VisitDynamicSize(len(m.Tags)) }
	if m.HasOptions { ps.VisitDynamicSize(len(m.Options)) }
	ps.VisitDynamicSize(len(m.SsLatestCommitVersions))
	{ n := ps.GetMessageWriter(int(KeySelectorRefVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(KeySelectorRefVTable[1])-4, KeySelectorRefMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(ReplyPromiseVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ReplyPromiseVTable[1])-4, ReplyPromiseMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(SpanContextVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(SpanContextVTable[1])-4, SpanContextMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(TenantInfoVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(TenantInfoVTable[1])-4, TenantInfoMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(GetKeyRequestVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetKeyRequestVTable[1])-4, 8)+4) }
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4) }
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8)) }
	totalSize := ps.CurrentBufferSize
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	var tagsOff int
	if m.HasTags { tagsOff, _ = wb.VisitDynamicSize(m.Tags) }
	var optionsOff int
	if m.HasOptions { optionsOff, _ = wb.VisitDynamicSize(m.Options) }
	ssLatestCommitVersionsOff, _ := wb.VisitDynamicSize(m.SsLatestCommitVersions)
	selW := wb.GetMessageWriter(int(KeySelectorRefVTable[1]), true)
	selStart := selW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(KeySelectorRefVTable) - selStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selW.WriteScalar(b[:], 0)
	}
	selW.WriteToAt(selStart)
	replyW := wb.GetMessageWriter(int(ReplyPromiseVTable[1]), true)
	replyStart := replyW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(ReplyPromiseVTable) - replyStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		replyW.WriteScalar(b[:], 0)
	}
	replyW.WriteToAt(replyStart)
	spanContextW := wb.GetMessageWriter(int(SpanContextVTable[1]), true)
	spanContextStart := spanContextW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(SpanContextVTable) - spanContextStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		spanContextW.WriteScalar(b[:], 0)
	}
	spanContextW.WriteToAt(spanContextStart)
	tenantInfoW := wb.GetMessageWriter(int(TenantInfoVTable[1]), true)
	tenantInfoStart := tenantInfoW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(TenantInfoVTable) - tenantInfoStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		tenantInfoW.WriteScalar(b[:], 0)
	}
	tenantInfoW.WriteToAt(tenantInfoStart)
	rootW := wb.GetMessageWriter(int(GetKeyRequestVTable[1]), true)
	rootStart := rootW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(GetKeyRequestVTable) - rootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		rootW.WriteScalar(b[:], 0)
	}
	{ var b [8]byte; binary.LittleEndian.PutUint64(b[:], uint64(m.Version)); rootW.WriteScalar(b[:], int(GetKeyRequestVTable[GetKeyRequestSlotVersion+2])) }
	if m.HasTags {
		rootW.WriteScalar([]byte{1}, int(GetKeyRequestVTable[GetKeyRequestSlotTags+2]))
		rootW.WriteRelativeOffset(tagsOff, int(GetKeyRequestVTable[GetKeyRequestSlotTags+1+2]))
	}
	if m.HasOptions {
		rootW.WriteScalar([]byte{1}, int(GetKeyRequestVTable[GetKeyRequestSlotOptions+2]))
		rootW.WriteRelativeOffset(optionsOff, int(GetKeyRequestVTable[GetKeyRequestSlotOptions+1+2]))
	}
	rootW.WriteRelativeOffset(ssLatestCommitVersionsOff, int(GetKeyRequestVTable[GetKeyRequestSlotSsLatestCommitVersions+2]))
	rootW.WriteRelativeOffset(selStart, int(GetKeyRequestVTable[GetKeyRequestSlotSel+2]))
	rootW.WriteRelativeOffset(replyStart, int(GetKeyRequestVTable[GetKeyRequestSlotReply+2]))
	rootW.WriteRelativeOffset(spanContextStart, int(GetKeyRequestVTable[GetKeyRequestSlotSpanContext+2]))
	rootW.WriteRelativeOffset(tenantInfoStart, int(GetKeyRequestVTable[GetKeyRequestSlotTenantInfo+2]))
	rootW.WriteToAt(rootStart)
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)
	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], GetKeyRequestFileID); footerW.WriteScalar(b[:], 4) }
	footerW.WriteToAt(wb.CurrentBufferSize)
	return buf
}

// ParseGetKeyRequestVectorFromReader reads a FlatBuffers vector of GetKeyRequest.
func ParseGetKeyRequestVectorFromReader(r *wire.Reader, slot int) []GetKeyRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]GetKeyRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem GetKeyRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

