// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	GetKeyReplySlotPenalty = 0
	GetKeyReplySlotError   = 1
	GetKeyReplySlotSel     = 3
	GetKeyReplySlotCached  = 4
)

var GetKeyReplyVTable = wire.VTable{14, 22, 4, 20, 12, 16, 21}

const GetKeyReplyFileID uint32 = 11226513

var GetKeyReplyVTableClosure = []wire.VTable{
	{6, 8, 4},
	{6, 6, 4},
	{10, 13, 4, 12, 8},
	{14, 22, 4, 20, 12, 16, 21},
}
var GetKeyReplyTemplate = wire.NewMessageTemplate(
	GetKeyReplyFileID, GetKeyReplyVTable, 8, GetKeyReplyVTableClosure,
)

type GetKeyReply struct {
	Penalty  float64 // slot 0
	HasError bool    // slot 1, optional tag
	Error    []byte  // slot 2, optional value
	// Sel: unregistered nested struct at slot 3
	Cached bool // slot 4
}

func (m *GetKeyReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
}

func (m *GetKeyReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		m.Error = r.ReadBytes(GetKeyReplySlotError + 1)
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
	return nil
}

func (m *GetKeyReply) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetKeyReplyVTable
	obj.WriteFloat64(int(vt[GetKeyReplySlotPenalty+2]), m.Penalty)
	obj.WriteBool(int(vt[GetKeyReplySlotCached+2]), m.Cached)
}

func (m *GetKeyReply) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(GetKeyReplyTemplate, m.MarshalInto)
}

func WriteGetKeyReply(obj *wire.ObjectWriter, parentOffset int, penalty float64, cached bool) {
	m := GetKeyReply{Penalty: penalty, Cached: cached}
	obj.WriteStruct(parentOffset, GetKeyReplyVTable, 8, m.MarshalInto)
}

func MarshalGetKeyReply(penalty float64, cached bool) []byte {
	m := GetKeyReply{Penalty: penalty, Cached: cached}
	return wire.MarshalStructBlob(GetKeyReplyVTable, m.MarshalInto)
}

// ParseGetKeyReplyVectorFromReader reads a FlatBuffers vector of GetKeyReply.
func ParseGetKeyReplyVectorFromReader(r *wire.Reader, slot int) []GetKeyReply {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetKeyReply, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetKeyReply
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
