// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetKeyValuesRequestSlotBegin = 0
	GetKeyValuesRequestSlotEnd = 1
	GetKeyValuesRequestSlotVersion = 2
	GetKeyValuesRequestSlotLimit = 3
	GetKeyValuesRequestSlotLimitBytes = 4
	GetKeyValuesRequestSlotTags = 5
	GetKeyValuesRequestSlotReply = 7
	GetKeyValuesRequestSlotSpanContext = 8
	GetKeyValuesRequestSlotTenantInfo = 9
	GetKeyValuesRequestSlotOptions = 10
	GetKeyValuesRequestSlotSsLatestCommitVersions = 12
	GetKeyValuesRequestSlotArena = 13
)

var GetKeyValuesRequestVTable = wire.VTable{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48}
const GetKeyValuesRequestFileID uint32 = 6795746
var GetKeyValuesRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 13, 4, 12, 8},
	{10, 29, 4, 20, 28},
	{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48},
}
var GetKeyValuesRequestTemplate = wire.NewMessageTemplate(
	GetKeyValuesRequestFileID, GetKeyValuesRequestVTable, 8, GetKeyValuesRequestVTableClosure,
)
const GetKeyValuesRequestMaxAlign = 8

type GetKeyValuesRequest struct {
	Begin KeySelectorRef // slot 0, nested
	End KeySelectorRef // slot 1, nested
	Version int64 // slot 2
	Limit int32 // slot 3
	LimitBytes int32 // slot 4
	HasTags bool   // slot 5, optional tag
	Tags    []byte // slot 6, optional value
	Reply ReplyPromise // slot 7, nested
	SpanContext SpanContext // slot 8, nested
	TenantInfo TenantInfo // slot 9, nested
	HasOptions bool   // slot 10, optional tag
	Options    []byte // slot 11, optional value
	SsLatestCommitVersions []byte // slot 12
	Arena []byte // slot 13
}

func (m *GetKeyValuesRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyValuesRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimitBytes) {
		m.LimitBytes = r.ReadInt32(GetKeyValuesRequestSlotLimitBytes)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotTags) && r.ReadUint8(GetKeyValuesRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyValuesRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotOptions) && r.ReadUint8(GetKeyValuesRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetKeyValuesRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyValuesRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyValuesRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesRequestSlotArena)
	}
}

func (m *GetKeyValuesRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyValuesRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimitBytes) {
		m.LimitBytes = r.ReadInt32(GetKeyValuesRequestSlotLimitBytes)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotTags) && r.ReadUint8(GetKeyValuesRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyValuesRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyValuesRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotOptions) && r.ReadUint8(GetKeyValuesRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetKeyValuesRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyValuesRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyValuesRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesRequestSlotArena)
	}
	return nil
}

func (m *GetKeyValuesRequest) blobSize() int {
	vt := GetKeyValuesRequestVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.SsLatestCommitVersions != nil { oolSize += (4 + len(m.SsLatestCommitVersions) + 3) &^ 3 }
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetKeyValuesRequest) writeBlob(buf []byte, pos int) int {
	vt := GetKeyValuesRequestVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyValuesRequestSlotVersion+2]):], uint64(m.Version))
	binary.LittleEndian.PutUint32(obj[int(vt[GetKeyValuesRequestSlotLimit+2]):], uint32(m.Limit))
	binary.LittleEndian.PutUint32(obj[int(vt[GetKeyValuesRequestSlotLimitBytes+2]):], uint32(m.LimitBytes))
	if m.SsLatestCommitVersions != nil {
		binary.LittleEndian.PutUint32(buf[curOOL:], uint32(len(m.SsLatestCommitVersions)))
		copy(buf[curOOL+4:], m.SsLatestCommitVersions)
		wire.PatchBlobRelOff(obj, int(vt[GetKeyValuesRequestSlotSsLatestCommitVersions+2]), objPos, curOOL)
		curOOL += (4 + len(m.SsLatestCommitVersions) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *GetKeyValuesRequest) measureEndOff(endOff int) int {
	if m.HasTags {
		endOff = wire.MeasureBytesOOL(endOff, m.Tags)
	}
	if m.HasOptions {
		endOff = wire.MeasureBytesOOL(endOff, m.Options)
	}
	endOff = wire.MeasureBytesOOL(endOff, m.SsLatestCommitVersions)
	endOff = m.Begin.measureEndOff(endOff)
	endOff = m.End.measureEndOff(endOff)
	endOff = m.Reply.measureEndOff(endOff)
	endOff = m.SpanContext.measureEndOff(endOff)
	endOff = m.TenantInfo.measureEndOff(endOff)
	endOff = wire.MeasureObject(endOff, GetKeyValuesRequestVTable, GetKeyValuesRequestMaxAlign)
	return endOff
}

func (m *GetKeyValuesRequest) writeDirect(dw *wire.DirectWriter) int {
	var tagsOOL int
	if m.HasTags {
		tagsOOL = dw.WriteBytesOOL(m.Tags)
	}
	var optionsOOL int
	if m.HasOptions {
		optionsOOL = dw.WriteBytesOOL(m.Options)
	}
	ssLatestCommitVersionsOOL := dw.WriteBytesOOL(m.SsLatestCommitVersions)
	beginPos := m.Begin.writeDirect(dw)
	endPos := m.End.writeDirect(dw)
	replyPos := m.Reply.writeDirect(dw)
	spanContextPos := m.SpanContext.writeDirect(dw)
	tenantInfoPos := m.TenantInfo.writeDirect(dw)
	objPos, obj := dw.WriteObject(GetKeyValuesRequestVTable, GetKeyValuesRequestMaxAlign)
	vt := GetKeyValuesRequestVTable
	binary.LittleEndian.PutUint64(obj[int(vt[GetKeyValuesRequestSlotVersion+2]):], uint64(m.Version))
	binary.LittleEndian.PutUint32(obj[int(vt[GetKeyValuesRequestSlotLimit+2]):], uint32(m.Limit))
	binary.LittleEndian.PutUint32(obj[int(vt[GetKeyValuesRequestSlotLimitBytes+2]):], uint32(m.LimitBytes))
	if m.HasTags {
		obj[int(vt[GetKeyValuesRequestSlotTags+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotTags+1+2]), objPos, tagsOOL)
	}
	if m.HasOptions {
		obj[int(vt[GetKeyValuesRequestSlotOptions+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotOptions+1+2]), objPos, optionsOOL)
	}
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotSsLatestCommitVersions+2]), objPos, ssLatestCommitVersionsOOL)
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotBegin+2]), objPos, beginPos)
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotEnd+2]), objPos, endPos)
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotReply+2]), objPos, replyPos)
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotSpanContext+2]), objPos, spanContextPos)
	wire.PatchRelOff(obj, int(vt[GetKeyValuesRequestSlotTenantInfo+2]), objPos, tenantInfoPos)
	return objPos
}

func (m *GetKeyValuesRequest) MarshalFDB() []byte {
	t := GetKeyValuesRequestTemplate
	packedVT := t.PackedVTables()
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	if m.HasTags { ps.VisitDynamicSize(len(m.Tags)) }
	if m.HasOptions { ps.VisitDynamicSize(len(m.Options)) }
	ps.VisitDynamicSize(len(m.SsLatestCommitVersions))
	{ n := ps.GetMessageWriter(int(KeySelectorRefVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(KeySelectorRefVTable[1])-4, KeySelectorRefMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(KeySelectorRefVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(KeySelectorRefVTable[1])-4, KeySelectorRefMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(ReplyPromiseVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ReplyPromiseVTable[1])-4, ReplyPromiseMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(SpanContextVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(SpanContextVTable[1])-4, SpanContextMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(TenantInfoVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(TenantInfoVTable[1])-4, TenantInfoMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(GetKeyValuesRequestVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetKeyValuesRequestVTable[1])-4, 8)+4) }
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4) }
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8)) }
	totalSize := ps.CurrentBufferSize
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	var tagsOff int
	if m.HasTags { tagsOff, _ = wb.VisitDynamicSize(m.Tags) }
	var optionsOff int
	if m.HasOptions { optionsOff, _ = wb.VisitDynamicSize(m.Options) }
	ssLatestCommitVersionsOff, _ := wb.VisitDynamicSize(m.SsLatestCommitVersions)
	beginW := wb.GetMessageWriter(int(KeySelectorRefVTable[1]), true)
	beginStart := beginW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(KeySelectorRefVTable) - beginStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		beginW.WriteScalar(b[:], 0)
	}
	beginW.WriteToAt(beginStart)
	endW := wb.GetMessageWriter(int(KeySelectorRefVTable[1]), true)
	endStart := endW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(KeySelectorRefVTable) - endStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		endW.WriteScalar(b[:], 0)
	}
	endW.WriteToAt(endStart)
	replyW := wb.GetMessageWriter(int(ReplyPromiseVTable[1]), true)
	replyStart := replyW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(ReplyPromiseVTable) - replyStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		replyW.WriteScalar(b[:], 0)
	}
	replyW.WriteToAt(replyStart)
	spanContextW := wb.GetMessageWriter(int(SpanContextVTable[1]), true)
	spanContextStart := spanContextW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(SpanContextVTable) - spanContextStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		spanContextW.WriteScalar(b[:], 0)
	}
	spanContextW.WriteToAt(spanContextStart)
	tenantInfoW := wb.GetMessageWriter(int(TenantInfoVTable[1]), true)
	tenantInfoStart := tenantInfoW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(TenantInfoVTable) - tenantInfoStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		tenantInfoW.WriteScalar(b[:], 0)
	}
	tenantInfoW.WriteToAt(tenantInfoStart)
	rootW := wb.GetMessageWriter(int(GetKeyValuesRequestVTable[1]), true)
	rootStart := rootW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(GetKeyValuesRequestVTable) - rootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		rootW.WriteScalar(b[:], 0)
	}
	{ var b [8]byte; binary.LittleEndian.PutUint64(b[:], uint64(m.Version)); rootW.WriteScalar(b[:], int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotVersion+2])) }
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(m.Limit)); rootW.WriteScalar(b[:], int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotLimit+2])) }
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(m.LimitBytes)); rootW.WriteScalar(b[:], int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotLimitBytes+2])) }
	if m.HasTags {
		rootW.WriteScalar([]byte{1}, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotTags+2]))
		rootW.WriteRelativeOffset(tagsOff, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotTags+1+2]))
	}
	if m.HasOptions {
		rootW.WriteScalar([]byte{1}, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotOptions+2]))
		rootW.WriteRelativeOffset(optionsOff, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotOptions+1+2]))
	}
	rootW.WriteRelativeOffset(ssLatestCommitVersionsOff, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotSsLatestCommitVersions+2]))
	rootW.WriteRelativeOffset(beginStart, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotBegin+2]))
	rootW.WriteRelativeOffset(endStart, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotEnd+2]))
	rootW.WriteRelativeOffset(replyStart, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotReply+2]))
	rootW.WriteRelativeOffset(spanContextStart, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotSpanContext+2]))
	rootW.WriteRelativeOffset(tenantInfoStart, int(GetKeyValuesRequestVTable[GetKeyValuesRequestSlotTenantInfo+2]))
	rootW.WriteToAt(rootStart)
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)
	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], GetKeyValuesRequestFileID); footerW.WriteScalar(b[:], 4) }
	footerW.WriteToAt(wb.CurrentBufferSize)
	return buf
}

// ParseGetKeyValuesRequestVectorFromReader reads a FlatBuffers vector of GetKeyValuesRequest.
func ParseGetKeyValuesRequestVectorFromReader(r *wire.Reader, slot int) []GetKeyValuesRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]GetKeyValuesRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem GetKeyValuesRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

