// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"
	"math"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	GetKeyReplySlotPenalty = 0
	GetKeyReplySlotError   = 1
	GetKeyReplySlotSel     = 3
	GetKeyReplySlotCached  = 4
)

var GetKeyReplyVTable = wire.VTable{14, 22, 4, 20, 12, 16, 21}

const GetKeyReplyFileID uint32 = 11226513

var GetKeyReplyVTableClosure = []wire.VTable{
	{6, 6, 4},
	{6, 8, 4},
	{10, 13, 4, 12, 8},
	{14, 22, 4, 20, 12, 16, 21},
}

var GetKeyReplyTemplate = wire.NewMessageTemplate(
	GetKeyReplyFileID, GetKeyReplyVTable, 8, GetKeyReplyVTableClosure,
)

const GetKeyReplyMaxAlign = 8

type GetKeyReply struct {
	Penalty  float64 // slot 0
	HasError bool    // slot 1, optional tag
	Error    Error   // slot 2, optional nested value
	// Sel: unregistered nested struct at slot 3
	Cached bool // slot 4
}

func (m *GetKeyReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyReplySlotError + 1); err == nil {
			m.Error.UnmarshalFromReader(nr)
		}
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
}

func (m *GetKeyReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetKeyReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetKeyReplySlotPenalty)
	}
	if r.FieldPresent(GetKeyReplySlotError) && r.ReadUint8(GetKeyReplySlotError) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyReplySlotError + 1); err == nil {
			m.Error.UnmarshalFromReader(nr)
		}
		m.HasError = true
	}
	if r.FieldPresent(GetKeyReplySlotCached) {
		m.Cached = r.ReadBool(GetKeyReplySlotCached)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetKeyReply) precomputeSize(ps *wire.PrecomputeSize) int {
	if m.HasError {
		m.Error.precomputeSize(ps)
	}
	{
		n := ps.GetMessageWriter(int(GetKeyReplyVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetKeyReplyVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetKeyReply) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var error_Off int
	if m.HasError {
		error_Off = m.Error.writeToBuffer(wb, vtableStart, tmpl)
	}
	selfW := wb.GetMessageWriter(int(GetKeyReplyVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetKeyReplyVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetKeyReplyVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], math.Float64bits(m.Penalty))
		selfW.WriteScalar(b[:], int(vt[GetKeyReplySlotPenalty+2]))
	}
	if m.Cached {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyReplySlotCached+2]))
	}
	if m.HasError {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyReplySlotError+2]))
		selfW.WriteRelativeOffset(error_Off, int(vt[GetKeyReplySlotError+1+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *GetKeyReply) MarshalFDB() []byte {
	t := GetKeyReplyTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyReplyFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *GetKeyReply) MarshalFDBPooled(dst []byte) []byte {
	t := GetKeyReplyTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyReplyFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseGetKeyReplyVectorFromReader reads a FlatBuffers vector of GetKeyReply.
func ParseGetKeyReplyVectorFromReader(r *wire.Reader, slot int) []GetKeyReply {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetKeyReply, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetKeyReply
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
