// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetKeyRequestSlotSel                    = 0
	GetKeyRequestSlotVersion                = 1
	GetKeyRequestSlotTags                   = 2
	GetKeyRequestSlotReply                  = 4
	GetKeyRequestSlotSpanContext            = 5
	GetKeyRequestSlotTenantInfo             = 6
	GetKeyRequestSlotOptions                = 7
	GetKeyRequestSlotSsLatestCommitVersions = 9
	GetKeyRequestSlotField_10               = 10
)

var GetKeyRequestVTable = wire.VTable{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36}

const GetKeyRequestFileID uint32 = 10457870

var GetKeyRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 13, 4, 12, 8},
	{10, 29, 4, 20, 28},
	{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36},
}

var GetKeyRequestTemplate = wire.NewMessageTemplate(
	GetKeyRequestFileID, GetKeyRequestVTable, 8, GetKeyRequestVTableClosure,
)

const GetKeyRequestMaxAlign = 8

type GetKeyRequest struct {
	Sel                    KeySelectorRef // slot 0, nested
	Version                int64          // slot 1
	HasTags                bool           // slot 2, optional tag
	Tags                   []byte         // slot 3, optional value
	Reply                  ReplyPromise   // slot 4, nested
	SpanContext            SpanContext    // slot 5, nested
	TenantInfo             TenantInfo     // slot 6, nested
	HasOptions             bool           // slot 7, optional tag
	Options                ReadOptions    // slot 8, optional nested value
	SsLatestCommitVersions []byte         // slot 9
	Field_10               []byte         // slot 10
}

func (m *GetKeyRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSel); err == nil {
		m.Sel.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyRequestSlotTags) && r.ReadUint8(GetKeyRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotOptions) && r.ReadUint8(GetKeyRequestSlotOptions) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyRequestSlotOptions + 1); err == nil {
			m.Options.UnmarshalFromReader(nr)
		}
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyRequestSlotField_10) {
		m.Field_10 = r.ReadBytes(GetKeyRequestSlotField_10)
	}
}

func (m *GetKeyRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSel); err == nil {
		m.Sel.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyRequestSlotTags) && r.ReadUint8(GetKeyRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyRequestSlotTags + 1)
		m.HasTags = true
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetKeyRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetKeyRequestSlotOptions) && r.ReadUint8(GetKeyRequestSlotOptions) > 0 {
		if nr, err := r.ReadNestedReader(GetKeyRequestSlotOptions + 1); err == nil {
			m.Options.UnmarshalFromReader(nr)
		}
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyRequestSlotField_10) {
		m.Field_10 = r.ReadBytes(GetKeyRequestSlotField_10)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetKeyRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Sel.precomputeSize(ps)
	if m.HasTags {
		ps.VisitDynamicSize(len(m.Tags))
	}
	m.Reply.precomputeSize(ps)
	m.SpanContext.precomputeSize(ps)
	m.TenantInfo.precomputeSize(ps)
	if m.HasOptions {
		m.Options.precomputeSize(ps)
	}
	ps.VisitDynamicSize(len(m.SsLatestCommitVersions))
	{
		n := ps.GetMessageWriter(int(GetKeyRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetKeyRequestVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetKeyRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var selStart int
	var tagsOff int
	var replyStart int
	var spanContextStart int
	var tenantInfoStart int
	var optionsOff int
	var ssLatestCommitVersionsOff int
	selStart = m.Sel.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasTags {
		tagsOff, _ = wb.VisitDynamicSize(m.Tags)
	}
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	spanContextStart = m.SpanContext.writeToBuffer(wb, vtableStart, tmpl)
	tenantInfoStart = m.TenantInfo.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasOptions {
		optionsOff = m.Options.writeToBuffer(wb, vtableStart, tmpl)
	}
	ssLatestCommitVersionsOff, _ = wb.VisitDynamicSize(m.SsLatestCommitVersions)
	selfW := wb.GetMessageWriter(int(GetKeyRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetKeyRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetKeyRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.Version))
		selfW.WriteScalar(b[:], int(vt[GetKeyRequestSlotVersion+2]))
	}
	selfW.WriteRelativeOffset(selStart, int(vt[GetKeyRequestSlotSel+2]))
	if m.HasTags {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyRequestSlotTags+2]))
		selfW.WriteRelativeOffset(tagsOff, int(vt[GetKeyRequestSlotTags+1+2]))
	}
	selfW.WriteRelativeOffset(replyStart, int(vt[GetKeyRequestSlotReply+2]))
	selfW.WriteRelativeOffset(spanContextStart, int(vt[GetKeyRequestSlotSpanContext+2]))
	selfW.WriteRelativeOffset(tenantInfoStart, int(vt[GetKeyRequestSlotTenantInfo+2]))
	if m.HasOptions {
		selfW.WriteScalar([]byte{1}, int(vt[GetKeyRequestSlotOptions+2]))
		selfW.WriteRelativeOffset(optionsOff, int(vt[GetKeyRequestSlotOptions+1+2]))
	}
	selfW.WriteRelativeOffset(ssLatestCommitVersionsOff, int(vt[GetKeyRequestSlotSsLatestCommitVersions+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *GetKeyRequest) MarshalFDB() []byte {
	t := GetKeyRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *GetKeyRequest) MarshalFDBPooled(dst []byte) []byte {
	t := GetKeyRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetKeyRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseGetKeyRequestVectorFromReader reads a FlatBuffers vector of GetKeyRequest.
func ParseGetKeyRequestVectorFromReader(r *wire.Reader, slot int) []GetKeyRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetKeyRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetKeyRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
