// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// GetKeyValuesRequest fields:
//
//	slot 0: begin — serialize_member, size=4, align=4, indirection
//	slot 1: end — serialize_member, size=4, align=4, indirection
//	slot 2: version — scalar, size=8, align=8
//	slot 3: limit — scalar, size=4, align=4
//	slot 4: limitBytes — scalar, size=4, align=4
//	slot 5: tags — union_like, size=4, align=4, indirection
//	slot 7: reply — serialize_member, size=4, align=4, indirection
//	slot 8: spanContext — serialize_member, size=4, align=4, indirection
//	slot 9: tenantInfo — serialize_member, size=4, align=4, indirection
//	slot 10: options — union_like, size=4, align=4, indirection
//	slot 12: ssLatestCommitVersions — dynamic_size, size=4, align=4, indirection
//	slot 13: arena — scalar, size=0, align=1
const (
	GetKeyValuesRequestSlotBegin                  = 0
	GetKeyValuesRequestSlotEnd                    = 1
	GetKeyValuesRequestSlotVersion                = 2
	GetKeyValuesRequestSlotLimit                  = 3
	GetKeyValuesRequestSlotLimitBytes             = 4
	GetKeyValuesRequestSlotTags                   = 5
	GetKeyValuesRequestSlotReply                  = 7
	GetKeyValuesRequestSlotSpanContext            = 8
	GetKeyValuesRequestSlotTenantInfo             = 9
	GetKeyValuesRequestSlotOptions                = 10
	GetKeyValuesRequestSlotSsLatestCommitVersions = 12
	GetKeyValuesRequestSlotArena                  = 13
)

var GetKeyValuesRequestVTable = wire.VTable{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48}

const GetKeyValuesRequestFileID uint32 = 6795746

var GetKeyValuesRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 13, 4, 12, 8},
	{10, 29, 4, 20, 28},
	{30, 54, 12, 16, 4, 20, 24, 52, 28, 32, 36, 40, 53, 44, 48},
}

type GetKeyValuesRequest struct {
	Begin                  KeySelectorRef // slot 0, nested
	End                    KeySelectorRef // slot 1, nested
	Version                int64          // slot 2, ReadInt64
	Limit                  int32          // slot 3, ReadInt32
	LimitBytes             int32          // slot 4, ReadInt32
	HasTags                bool           // slot 5, Optional, presence flag
	Tags                   []byte         // slot 6, Optional, ReadBytes
	Reply                  ReplyPromise   // slot 7, nested
	SpanContext            SpanContext    // slot 8, nested
	TenantInfo             TenantInfo     // slot 9, nested
	HasOptions             bool           // slot 10, Optional, presence flag
	Options                []byte         // slot 11, Optional, ReadBytes
	SsLatestCommitVersions []byte         // slot 12, ReadBytes
	Arena                  []byte         // slot 13, ReadBytes
}

func (m *GetKeyValuesRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	// Begin (slot 0): nested struct — use r.ReadNestedReader(GetKeyValuesRequestSlotBegin)
	// End (slot 1): nested struct — use r.ReadNestedReader(GetKeyValuesRequestSlotEnd)
	if r.FieldPresent(GetKeyValuesRequestSlotVersion) {
		m.Version = r.ReadInt64(GetKeyValuesRequestSlotVersion)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimit) {
		m.Limit = r.ReadInt32(GetKeyValuesRequestSlotLimit)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotLimitBytes) {
		m.LimitBytes = r.ReadInt32(GetKeyValuesRequestSlotLimitBytes)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotTags) && r.ReadUint8(GetKeyValuesRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetKeyValuesRequestSlotTags + 1)
		m.HasTags = true
	}
	// Reply (slot 7): nested struct — use r.ReadNestedReader(GetKeyValuesRequestSlotReply)
	// SpanContext (slot 8): nested struct — use r.ReadNestedReader(GetKeyValuesRequestSlotSpanContext)
	// TenantInfo (slot 9): nested struct — use r.ReadNestedReader(GetKeyValuesRequestSlotTenantInfo)
	if r.FieldPresent(GetKeyValuesRequestSlotOptions) && r.ReadUint8(GetKeyValuesRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetKeyValuesRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetKeyValuesRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetKeyValuesRequestSlotSsLatestCommitVersions)
	}
	if r.FieldPresent(GetKeyValuesRequestSlotArena) {
		m.Arena = r.ReadBytes(GetKeyValuesRequestSlotArena)
	}
	return nil
}

func (m *GetKeyValuesRequest) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetKeyValuesRequestVTable
	obj.WriteInt64(int(vt[GetKeyValuesRequestSlotVersion+2]), m.Version)
	obj.WriteInt32(int(vt[GetKeyValuesRequestSlotLimit+2]), m.Limit)
	obj.WriteInt32(int(vt[GetKeyValuesRequestSlotLimitBytes+2]), m.LimitBytes)
	obj.WriteBytes(int(vt[GetKeyValuesRequestSlotSsLatestCommitVersions+2]), m.SsLatestCommitVersions)
}

func WriteGetKeyValuesRequest(obj *wire.ObjectWriter, parentOffset int, version int64, limit int32, limitBytes int32, ssLatestCommitVersions []byte) {
	m := GetKeyValuesRequest{Version: version, Limit: limit, LimitBytes: limitBytes, SsLatestCommitVersions: ssLatestCommitVersions}
	obj.WriteStruct(parentOffset, GetKeyValuesRequestVTable, 8, m.MarshalInto)
}

var GetKeyValuesRequestTemplate = wire.NewMessageTemplate(
	GetKeyValuesRequestFileID, GetKeyValuesRequestVTable, 8, GetKeyValuesRequestVTableClosure,
)
