// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"
	"math"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	GetMappedKeyValuesReplySlotPenalty = 0
	GetMappedKeyValuesReplySlotError   = 1
	GetMappedKeyValuesReplySlotData    = 3
	GetMappedKeyValuesReplySlotVersion = 4
	GetMappedKeyValuesReplySlotMore    = 5
	GetMappedKeyValuesReplySlotCached  = 6
	GetMappedKeyValuesReplySlotArena   = 7
)

var GetMappedKeyValuesReplyVTable = wire.VTable{18, 31, 4, 28, 20, 24, 12, 29, 30}

const GetMappedKeyValuesReplyFileID uint32 = 1783067

var GetMappedKeyValuesReplyVTableClosure = []wire.VTable{
	{16, 16, 4, 12, 13, 8, 14, 15},
	{6, 6, 4},
	{6, 8, 4},
	{8, 12, 4, 8},
	{10, 13, 4, 12, 8},
	{10, 16, 4, 8, 12},
	{18, 31, 4, 28, 20, 24, 12, 29, 30},
}

var GetMappedKeyValuesReplyTemplate = wire.NewMessageTemplate(
	GetMappedKeyValuesReplyFileID, GetMappedKeyValuesReplyVTable, 8, GetMappedKeyValuesReplyVTableClosure,
)

const GetMappedKeyValuesReplyMaxAlign = 8

type GetMappedKeyValuesReply struct {
	Penalty  float64             // slot 0
	HasError bool                // slot 1, optional tag
	Error    Error               // slot 2, optional nested value
	Data     []MappedKeyValueRef // slot 3, vector of struct
	Version  int64               // slot 4
	More     bool                // slot 5
	Cached   bool                // slot 6
	Arena    []byte              // slot 7
}

func (m *GetMappedKeyValuesReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetMappedKeyValuesReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetMappedKeyValuesReplySlotPenalty)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotError) && r.ReadUint8(GetMappedKeyValuesReplySlotError) > 0 {
		if nr, err := r.ReadNestedReader(GetMappedKeyValuesReplySlotError + 1); err == nil {
			m.Error.UnmarshalFromReader(nr)
		}
		m.HasError = true
	}
	if count, err := r.ReadVectorCount(GetMappedKeyValuesReplySlotData); err == nil && count > 0 {
		m.Data = make([]MappedKeyValueRef, 0, count)
		for i := 0; i < count; i++ {
			if elemR, err := r.ReadVectorElementReader(GetMappedKeyValuesReplySlotData, i); err == nil {
				var elem MappedKeyValueRef
				elem.UnmarshalFromReader(elemR)
				m.Data = append(m.Data, elem)
			}
		}
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotVersion) {
		m.Version = r.ReadInt64(GetMappedKeyValuesReplySlotVersion)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotMore) {
		m.More = r.ReadBool(GetMappedKeyValuesReplySlotMore)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotCached) {
		m.Cached = r.ReadBool(GetMappedKeyValuesReplySlotCached)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotArena) {
		m.Arena = r.ReadBytes(GetMappedKeyValuesReplySlotArena)
	}
}

func (m *GetMappedKeyValuesReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotPenalty) {
		m.Penalty = r.ReadFloat64(GetMappedKeyValuesReplySlotPenalty)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotError) && r.ReadUint8(GetMappedKeyValuesReplySlotError) > 0 {
		if nr, err := r.ReadNestedReader(GetMappedKeyValuesReplySlotError + 1); err == nil {
			m.Error.UnmarshalFromReader(nr)
		}
		m.HasError = true
	}
	if count, err := r.ReadVectorCount(GetMappedKeyValuesReplySlotData); err == nil && count > 0 {
		m.Data = make([]MappedKeyValueRef, 0, count)
		for i := 0; i < count; i++ {
			if elemR, err := r.ReadVectorElementReader(GetMappedKeyValuesReplySlotData, i); err == nil {
				var elem MappedKeyValueRef
				elem.UnmarshalFromReader(elemR)
				m.Data = append(m.Data, elem)
			}
		}
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotVersion) {
		m.Version = r.ReadInt64(GetMappedKeyValuesReplySlotVersion)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotMore) {
		m.More = r.ReadBool(GetMappedKeyValuesReplySlotMore)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotCached) {
		m.Cached = r.ReadBool(GetMappedKeyValuesReplySlotCached)
	}
	if r.FieldPresent(GetMappedKeyValuesReplySlotArena) {
		m.Arena = r.ReadBytes(GetMappedKeyValuesReplySlotArena)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetMappedKeyValuesReply) precomputeSize(ps *wire.PrecomputeSize) int {
	if m.HasError {
		m.Error.precomputeSize(ps)
	}
	{
		n := len(m.Data)
		if n > 0 {
			self := ps.GetMessageWriter(n * 4)
			for i := 0; i < n; i++ {
				m.Data[i].precomputeSize(ps)
			}
			start := wire.RightAlign(ps.CurrentBufferSize+n*4, 4) + 4
			ps.Write(start)             // count at start (4 bytes)
			self.WriteToAt(ps, start-4) // reloff array at start-4
		} else {
			ps.VisitDynamicSize(0)
		}
	}
	{
		n := ps.GetMessageWriter(int(GetMappedKeyValuesReplyVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetMappedKeyValuesReplyVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetMappedKeyValuesReply) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var error_Off int
	var dataOff int
	if m.HasError {
		error_Off = m.Error.writeToBuffer(wb, vtableStart, tmpl)
	}
	{
		n := len(m.Data)
		if n > 0 {
			self := wb.GetMessageWriter(n*4, false)
			for i := 0; i < n; i++ {
				elemStart := m.Data[i].writeToBuffer(wb, vtableStart, tmpl)
				self.WriteRelativeOffset(elemStart, i*4)
			}
			wb.WriteUint32(uint32(n), self.FinalLocation+4)
			self.WriteToAt(self.FinalLocation)
			dataOff = wb.CurrentBufferSize
		} else {
			dataOff, _ = wb.VisitDynamicSize(nil)
		}
	}
	selfW := wb.GetMessageWriter(int(GetMappedKeyValuesReplyVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetMappedKeyValuesReplyVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetMappedKeyValuesReplyVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], math.Float64bits(m.Penalty))
		selfW.WriteScalar(b[:], int(vt[GetMappedKeyValuesReplySlotPenalty+2]))
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.Version))
		selfW.WriteScalar(b[:], int(vt[GetMappedKeyValuesReplySlotVersion+2]))
	}
	if m.More {
		selfW.WriteScalar([]byte{1}, int(vt[GetMappedKeyValuesReplySlotMore+2]))
	}
	if m.Cached {
		selfW.WriteScalar([]byte{1}, int(vt[GetMappedKeyValuesReplySlotCached+2]))
	}
	if m.HasError {
		selfW.WriteScalar([]byte{1}, int(vt[GetMappedKeyValuesReplySlotError+2]))
		selfW.WriteRelativeOffset(error_Off, int(vt[GetMappedKeyValuesReplySlotError+1+2]))
	}
	selfW.WriteRelativeOffset(dataOff, int(vt[GetMappedKeyValuesReplySlotData+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *GetMappedKeyValuesReply) MarshalFDB() []byte {
	t := GetMappedKeyValuesReplyTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetMappedKeyValuesReplyFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *GetMappedKeyValuesReply) MarshalFDBPooled(dst []byte) []byte {
	t := GetMappedKeyValuesReplyTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetMappedKeyValuesReplyFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseGetMappedKeyValuesReplyVectorFromReader reads a FlatBuffers vector of GetMappedKeyValuesReply.
func ParseGetMappedKeyValuesReplyVectorFromReader(r *wire.Reader, slot int) []GetMappedKeyValuesReply {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetMappedKeyValuesReply, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetMappedKeyValuesReply
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
