// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetReadVersionRequestSlotTransactionCount = 0
	GetReadVersionRequestSlotFlags = 1
	GetReadVersionRequestSlotTags = 2
	GetReadVersionRequestSlotDebugID = 3
	GetReadVersionRequestSlotReply = 5
	GetReadVersionRequestSlotSpanContext = 6
	GetReadVersionRequestSlotMaxVersion = 7
)

var GetReadVersionRequestVTable = wire.VTable{20, 37, 12, 16, 20, 36, 24, 28, 32, 4}
const GetReadVersionRequestFileID uint32 = 838566
var GetReadVersionRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
	{8, 12, 4, 8},
	{10, 29, 4, 20, 28},
	{20, 37, 12, 16, 20, 36, 24, 28, 32, 4},
}
var GetReadVersionRequestTemplate = wire.NewMessageTemplate(
	GetReadVersionRequestFileID, GetReadVersionRequestVTable, 8, GetReadVersionRequestVTableClosure,
)
const GetReadVersionRequestMaxAlign = 8

type GetReadVersionRequest struct {
	TransactionCount uint32 // slot 0
	Flags uint32 // slot 1
	Tags []byte // slot 2
	HasDebugID bool   // slot 3, optional tag
	DebugID    []byte // slot 4, optional value
	Reply ReplyPromise // slot 5, nested
	SpanContext SpanContext // slot 6, nested
	MaxVersion int64 // slot 7
}

func (m *GetReadVersionRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		m.DebugID = r.ReadBytes(GetReadVersionRequestSlotDebugID + 1)
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
}

func (m *GetReadVersionRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		m.DebugID = r.ReadBytes(GetReadVersionRequestSlotDebugID + 1)
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
	return nil
}

func (m *GetReadVersionRequest) blobSize() int {
	vt := GetReadVersionRequestVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.Tags != nil { oolSize += (len(m.Tags) + 3) &^ 3 }
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetReadVersionRequest) writeBlob(buf []byte, pos int) int {
	vt := GetReadVersionRequestVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotTransactionCount+2]):], m.TransactionCount)
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotFlags+2]):], m.Flags)
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionRequestSlotMaxVersion+2]):], uint64(m.MaxVersion))
	if m.Tags != nil {
		copy(buf[curOOL:], m.Tags)
		wire.PatchBlobRelOff(obj, int(vt[GetReadVersionRequestSlotTags+2]), objPos, curOOL)
		curOOL += (len(m.Tags) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *GetReadVersionRequest) measureEndOff(endOff int) int {
	endOff = wire.MeasureBytesOOL(endOff, m.Tags)
	if m.HasDebugID {
		endOff = wire.MeasureBytesOOL(endOff, m.DebugID)
	}
	endOff = m.Reply.measureEndOff(endOff)
	endOff = m.SpanContext.measureEndOff(endOff)
	endOff = wire.MeasureObject(endOff, GetReadVersionRequestVTable, GetReadVersionRequestMaxAlign)
	return endOff
}

func (m *GetReadVersionRequest) writeDirect(dw *wire.DirectWriter) int {
	tagsOOL := dw.WriteBytesOOL(m.Tags)
	var debugIDOOL int
	if m.HasDebugID {
		debugIDOOL = dw.WriteBytesOOL(m.DebugID)
	}
	replyPos := m.Reply.writeDirect(dw)
	spanContextPos := m.SpanContext.writeDirect(dw)
	objPos, obj := dw.WriteObject(GetReadVersionRequestVTable, GetReadVersionRequestMaxAlign)
	vt := GetReadVersionRequestVTable
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotTransactionCount+2]):], m.TransactionCount)
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotFlags+2]):], m.Flags)
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionRequestSlotMaxVersion+2]):], uint64(m.MaxVersion))
	wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotTags+2]), objPos, tagsOOL)
	if m.HasDebugID {
		obj[int(vt[GetReadVersionRequestSlotDebugID+2])] = 1
		wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotDebugID+1+2]), objPos, debugIDOOL)
	}
	wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotReply+2]), objPos, replyPos)
	wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotSpanContext+2]), objPos, spanContextPos)
	return objPos
}

func (m *GetReadVersionRequest) MarshalFDB() []byte {
	t := GetReadVersionRequestTemplate
	packedVT := t.PackedVTables()
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	ps.VisitDynamicSize(len(m.Tags))
	if m.HasDebugID { ps.VisitDynamicSize(len(m.DebugID)) }
	{ n := ps.GetMessageWriter(int(ReplyPromiseVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ReplyPromiseVTable[1])-4, ReplyPromiseMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(SpanContextVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(SpanContextVTable[1])-4, SpanContextMaxAlign)+4) }
	{ n := ps.GetMessageWriter(int(GetReadVersionRequestVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetReadVersionRequestVTable[1])-4, 8)+4) }
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4) }
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{ n := ps.GetMessageWriter(8); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8)) }
	totalSize := ps.CurrentBufferSize
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	tagsOff, _ := wb.VisitDynamicSize(m.Tags)
	var debugIDOff int
	if m.HasDebugID { debugIDOff, _ = wb.VisitDynamicSize(m.DebugID) }
	replyW := wb.GetMessageWriter(int(ReplyPromiseVTable[1]), true)
	replyStart := replyW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(ReplyPromiseVTable) - replyStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		replyW.WriteScalar(b[:], 0)
	}
	replyW.WriteToAt(replyStart)
	spanContextW := wb.GetMessageWriter(int(SpanContextVTable[1]), true)
	spanContextStart := spanContextW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(SpanContextVTable) - spanContextStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		spanContextW.WriteScalar(b[:], 0)
	}
	spanContextW.WriteToAt(spanContextStart)
	rootW := wb.GetMessageWriter(int(GetReadVersionRequestVTable[1]), true)
	rootStart := rootW.FinalLocation
	{
		soff := int32(vtableStart - t.VTableOffset(GetReadVersionRequestVTable) - rootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		rootW.WriteScalar(b[:], 0)
	}
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(m.TransactionCount)); rootW.WriteScalar(b[:], int(GetReadVersionRequestVTable[GetReadVersionRequestSlotTransactionCount+2])) }
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(m.Flags)); rootW.WriteScalar(b[:], int(GetReadVersionRequestVTable[GetReadVersionRequestSlotFlags+2])) }
	{ var b [8]byte; binary.LittleEndian.PutUint64(b[:], uint64(m.MaxVersion)); rootW.WriteScalar(b[:], int(GetReadVersionRequestVTable[GetReadVersionRequestSlotMaxVersion+2])) }
	rootW.WriteRelativeOffset(tagsOff, int(GetReadVersionRequestVTable[GetReadVersionRequestSlotTags+2]))
	if m.HasDebugID {
		rootW.WriteScalar([]byte{1}, int(GetReadVersionRequestVTable[GetReadVersionRequestSlotDebugID+2]))
		rootW.WriteRelativeOffset(debugIDOff, int(GetReadVersionRequestVTable[GetReadVersionRequestSlotDebugID+1+2]))
	}
	rootW.WriteRelativeOffset(replyStart, int(GetReadVersionRequestVTable[GetReadVersionRequestSlotReply+2]))
	rootW.WriteRelativeOffset(spanContextStart, int(GetReadVersionRequestVTable[GetReadVersionRequestSlotSpanContext+2]))
	rootW.WriteToAt(rootStart)
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)
	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], GetReadVersionRequestFileID); footerW.WriteScalar(b[:], 4) }
	footerW.WriteToAt(wb.CurrentBufferSize)
	return buf
}

// ParseGetReadVersionRequestVectorFromReader reads a FlatBuffers vector of GetReadVersionRequest.
func ParseGetReadVersionRequestVectorFromReader(r *wire.Reader, slot int) []GetReadVersionRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]GetReadVersionRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem GetReadVersionRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

