// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetReadVersionRequestSlotTransactionCount = 0
	GetReadVersionRequestSlotFlags            = 1
	GetReadVersionRequestSlotTags             = 2
	GetReadVersionRequestSlotDebugID          = 3
	GetReadVersionRequestSlotReply            = 5
	GetReadVersionRequestSlotSpanContext      = 6
	GetReadVersionRequestSlotMaxVersion       = 7
)

var GetReadVersionRequestVTable = wire.VTable{20, 37, 12, 16, 20, 36, 24, 28, 32, 4}

const GetReadVersionRequestFileID uint32 = 838566

var GetReadVersionRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
	{8, 12, 4, 8},
	{10, 29, 4, 20, 28},
	{20, 37, 12, 16, 20, 36, 24, 28, 32, 4},
}
var GetReadVersionRequestTemplate = wire.NewMessageTemplate(
	GetReadVersionRequestFileID, GetReadVersionRequestVTable, 8, GetReadVersionRequestVTableClosure,
)

const GetReadVersionRequestMaxAlign = 8

type GetReadVersionRequest struct {
	TransactionCount uint32       // slot 0
	Flags            uint32       // slot 1
	Tags             []byte       // slot 2
	HasDebugID       bool         // slot 3, optional tag
	DebugID          []byte       // slot 4, optional value
	Reply            ReplyPromise // slot 5, nested
	SpanContext      SpanContext  // slot 6, nested
	MaxVersion       int64        // slot 7
}

func (m *GetReadVersionRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		m.DebugID = r.ReadBytes(GetReadVersionRequestSlotDebugID + 1)
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
}

func (m *GetReadVersionRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		m.DebugID = r.ReadBytes(GetReadVersionRequestSlotDebugID + 1)
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
	return nil
}

func (m *GetReadVersionRequest) blobSize() int {
	vt := GetReadVersionRequestVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.Tags != nil {
		oolSize += (len(m.Tags) + 3) &^ 3
	}
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetReadVersionRequest) writeBlob(buf []byte, pos int) int {
	vt := GetReadVersionRequestVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotTransactionCount+2]):], m.TransactionCount)
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotFlags+2]):], m.Flags)
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionRequestSlotMaxVersion+2]):], uint64(m.MaxVersion))
	if m.Tags != nil {
		copy(buf[curOOL:], m.Tags)
		wire.PatchBlobRelOff(obj, int(vt[GetReadVersionRequestSlotTags+2]), objPos, curOOL)
		curOOL += (len(m.Tags) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *GetReadVersionRequest) measureEndOff(endOff int) int {
	endOff = wire.MeasureRawOOL(endOff, m.Tags)
	endOff = m.SpanContext.measureEndOff(endOff)
	endOff = m.Reply.measureEndOff(endOff)
	endOff = wire.MeasureObject(endOff, GetReadVersionRequestVTable, GetReadVersionRequestMaxAlign)
	return endOff
}

func (m *GetReadVersionRequest) writeDirect(dw *wire.DirectWriter) int {
	var tagsOOL int
	if m.Tags != nil {
		tagsOOL = dw.WriteRawOOL(m.Tags)
	}
	spanContextPos := m.SpanContext.writeDirect(dw)
	replyPos := m.Reply.writeDirect(dw)
	objPos, obj := dw.WriteObject(GetReadVersionRequestVTable, GetReadVersionRequestMaxAlign)
	vt := GetReadVersionRequestVTable
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotTransactionCount+2]):], m.TransactionCount)
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionRequestSlotFlags+2]):], m.Flags)
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionRequestSlotMaxVersion+2]):], uint64(m.MaxVersion))
	if m.Tags != nil {
		wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotTags+2]), objPos, tagsOOL)
	}
	wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotReply+2]), objPos, replyPos)
	wire.PatchRelOff(obj, int(vt[GetReadVersionRequestSlotSpanContext+2]), objPos, spanContextPos)
	return objPos
}

func (m *GetReadVersionRequest) MarshalFDB() []byte {
	t := GetReadVersionRequestTemplate
	endOff := 0
	endOff = wire.MeasureRawOOL(endOff, m.Tags)
	endOff = m.SpanContext.measureEndOff(endOff)
	endOff = m.Reply.measureEndOff(endOff)
	bodySize := int(GetReadVersionRequestVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 8 - 1) &^ (8 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseGetReadVersionRequestVectorFromReader reads a FlatBuffers vector of GetReadVersionRequest.
func ParseGetReadVersionRequestVectorFromReader(r *wire.Reader, slot int) []GetReadVersionRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetReadVersionRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetReadVersionRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
