// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	GetRangeReqAndResultSlotBegin  = 0
	GetRangeReqAndResultSlotEnd    = 1
	GetRangeReqAndResultSlotResult = 2
)

var GetRangeReqAndResultVTable = wire.VTable{10, 16, 4, 8, 12}

const GetRangeReqAndResultMaxAlign = 4

type GetRangeReqAndResult struct {
	Begin  KeySelectorRef // slot 0, nested
	End    KeySelectorRef // slot 1, nested
	Result RangeResultRef // slot 2, nested
}

func (m *GetRangeReqAndResult) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotResult); err == nil {
		m.Result.UnmarshalFromReader(nr)
	}
}

func (m *GetRangeReqAndResult) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotBegin); err == nil {
		m.Begin.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotEnd); err == nil {
		m.End.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetRangeReqAndResultSlotResult); err == nil {
		m.Result.UnmarshalFromReader(nr)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetRangeReqAndResult) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Begin.precomputeSize(ps)
	m.End.precomputeSize(ps)
	m.Result.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(int(GetRangeReqAndResultVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetRangeReqAndResultVTable[1])-4, 4)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetRangeReqAndResult) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var beginStart int
	var endStart int
	var resultStart int
	beginStart = m.Begin.writeToBuffer(wb, vtableStart, tmpl)
	endStart = m.End.writeToBuffer(wb, vtableStart, tmpl)
	resultStart = m.Result.writeToBuffer(wb, vtableStart, tmpl)
	selfW := wb.GetMessageWriter(int(GetRangeReqAndResultVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetRangeReqAndResultVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetRangeReqAndResultVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	selfW.WriteRelativeOffset(beginStart, int(vt[GetRangeReqAndResultSlotBegin+2]))
	selfW.WriteRelativeOffset(endStart, int(vt[GetRangeReqAndResultSlotEnd+2]))
	selfW.WriteRelativeOffset(resultStart, int(vt[GetRangeReqAndResultSlotResult+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

// ParseGetRangeReqAndResultVectorFromReader reads a FlatBuffers vector of GetRangeReqAndResult.
func ParseGetRangeReqAndResultVectorFromReader(r *wire.Reader, slot int) []GetRangeReqAndResult {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetRangeReqAndResult, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetRangeReqAndResult
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
