// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"
	"math"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetReadVersionReplySlotProcessBusyTime           = 0
	GetReadVersionReplySlotVersion                   = 1
	GetReadVersionReplySlotLocked                    = 2
	GetReadVersionReplySlotMetadataVersion           = 3
	GetReadVersionReplySlotTagThrottleInfo           = 5
	GetReadVersionReplySlotMidShardSize              = 6
	GetReadVersionReplySlotRkDefaultThrottled        = 7
	GetReadVersionReplySlotRkBatchThrottled          = 8
	GetReadVersionReplySlotSsVersionVectorDelta      = 9
	GetReadVersionReplySlotProxyId                   = 10
	GetReadVersionReplySlotProxyTagThrottledDuration = 11
)

var GetReadVersionReplyVTable = wire.VTable{28, 64, 44, 20, 60, 61, 48, 52, 28, 62, 63, 56, 4, 36}

const GetReadVersionReplyFileID uint32 = 15709388

var GetReadVersionReplyVTableClosure = []wire.VTable{
	{8, 20, 4, 12},
	{6, 8, 4},
	{8, 12, 4, 8},
	{28, 64, 44, 20, 60, 61, 48, 52, 28, 62, 63, 56, 4, 36},
}
var GetReadVersionReplyTemplate = wire.NewMessageTemplate(
	GetReadVersionReplyFileID, GetReadVersionReplyVTable, 8, GetReadVersionReplyVTableClosure,
)

const GetReadVersionReplyMaxAlign = 8

type GetReadVersionReply struct {
	ProcessBusyTime           int32    // slot 0
	Version                   int64    // slot 1
	Locked                    bool     // slot 2
	HasMetadataVersion        bool     // slot 3, optional tag
	MetadataVersion           []byte   // slot 4, optional value
	TagThrottleInfo           []byte   // slot 5
	MidShardSize              int64    // slot 6
	RkDefaultThrottled        bool     // slot 7
	RkBatchThrottled          bool     // slot 8
	SsVersionVectorDelta      []byte   // slot 9
	ProxyId                   [16]byte // slot 10
	ProxyTagThrottledDuration float64  // slot 11
}

func (m *GetReadVersionReply) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetReadVersionReplySlotProcessBusyTime) {
		m.ProcessBusyTime = r.ReadInt32(GetReadVersionReplySlotProcessBusyTime)
	}
	if r.FieldPresent(GetReadVersionReplySlotVersion) {
		m.Version = r.ReadInt64(GetReadVersionReplySlotVersion)
	}
	if r.FieldPresent(GetReadVersionReplySlotLocked) {
		m.Locked = r.ReadBool(GetReadVersionReplySlotLocked)
	}
	if r.FieldPresent(GetReadVersionReplySlotMetadataVersion) && r.ReadUint8(GetReadVersionReplySlotMetadataVersion) > 0 {
		m.MetadataVersion = r.ReadBytes(GetReadVersionReplySlotMetadataVersion + 1)
		m.HasMetadataVersion = true
	}
	if r.FieldPresent(GetReadVersionReplySlotTagThrottleInfo) {
		m.TagThrottleInfo = r.ReadBytes(GetReadVersionReplySlotTagThrottleInfo)
	}
	if r.FieldPresent(GetReadVersionReplySlotMidShardSize) {
		m.MidShardSize = r.ReadInt64(GetReadVersionReplySlotMidShardSize)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkDefaultThrottled) {
		m.RkDefaultThrottled = r.ReadBool(GetReadVersionReplySlotRkDefaultThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkBatchThrottled) {
		m.RkBatchThrottled = r.ReadBool(GetReadVersionReplySlotRkBatchThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotSsVersionVectorDelta) {
		m.SsVersionVectorDelta = r.ReadBytes(GetReadVersionReplySlotSsVersionVectorDelta)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyId) {
		m.ProxyId = r.ReadUID(GetReadVersionReplySlotProxyId)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyTagThrottledDuration) {
		m.ProxyTagThrottledDuration = r.ReadFloat64(GetReadVersionReplySlotProxyTagThrottledDuration)
	}
}

func (m *GetReadVersionReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetReadVersionReplySlotProcessBusyTime) {
		m.ProcessBusyTime = r.ReadInt32(GetReadVersionReplySlotProcessBusyTime)
	}
	if r.FieldPresent(GetReadVersionReplySlotVersion) {
		m.Version = r.ReadInt64(GetReadVersionReplySlotVersion)
	}
	if r.FieldPresent(GetReadVersionReplySlotLocked) {
		m.Locked = r.ReadBool(GetReadVersionReplySlotLocked)
	}
	if r.FieldPresent(GetReadVersionReplySlotMetadataVersion) && r.ReadUint8(GetReadVersionReplySlotMetadataVersion) > 0 {
		m.MetadataVersion = r.ReadBytes(GetReadVersionReplySlotMetadataVersion + 1)
		m.HasMetadataVersion = true
	}
	if r.FieldPresent(GetReadVersionReplySlotTagThrottleInfo) {
		m.TagThrottleInfo = r.ReadBytes(GetReadVersionReplySlotTagThrottleInfo)
	}
	if r.FieldPresent(GetReadVersionReplySlotMidShardSize) {
		m.MidShardSize = r.ReadInt64(GetReadVersionReplySlotMidShardSize)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkDefaultThrottled) {
		m.RkDefaultThrottled = r.ReadBool(GetReadVersionReplySlotRkDefaultThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotRkBatchThrottled) {
		m.RkBatchThrottled = r.ReadBool(GetReadVersionReplySlotRkBatchThrottled)
	}
	if r.FieldPresent(GetReadVersionReplySlotSsVersionVectorDelta) {
		m.SsVersionVectorDelta = r.ReadBytes(GetReadVersionReplySlotSsVersionVectorDelta)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyId) {
		m.ProxyId = r.ReadUID(GetReadVersionReplySlotProxyId)
	}
	if r.FieldPresent(GetReadVersionReplySlotProxyTagThrottledDuration) {
		m.ProxyTagThrottledDuration = r.ReadFloat64(GetReadVersionReplySlotProxyTagThrottledDuration)
	}
	return nil
}

func (m *GetReadVersionReply) blobSize() int {
	vt := GetReadVersionReplyVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.TagThrottleInfo != nil {
		oolSize += (len(m.TagThrottleInfo) + 3) &^ 3
	}
	if m.SsVersionVectorDelta != nil {
		oolSize += (4 + len(m.SsVersionVectorDelta) + 3) &^ 3
	}
	return (oolPos + oolSize + 3) &^ 3
}

func (m *GetReadVersionReply) writeBlob(buf []byte, pos int) int {
	vt := GetReadVersionReplyVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionReplySlotProcessBusyTime+2]):], uint32(m.ProcessBusyTime))
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotVersion+2]):], uint64(m.Version))
	if m.Locked {
		obj[int(vt[GetReadVersionReplySlotLocked+2])] = 1
	}
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotMidShardSize+2]):], uint64(m.MidShardSize))
	if m.RkDefaultThrottled {
		obj[int(vt[GetReadVersionReplySlotRkDefaultThrottled+2])] = 1
	}
	if m.RkBatchThrottled {
		obj[int(vt[GetReadVersionReplySlotRkBatchThrottled+2])] = 1
	}
	copy(obj[int(vt[GetReadVersionReplySlotProxyId+2]):], m.ProxyId[:])
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotProxyTagThrottledDuration+2]):], math.Float64bits(m.ProxyTagThrottledDuration))
	if m.TagThrottleInfo != nil {
		copy(buf[curOOL:], m.TagThrottleInfo)
		wire.PatchBlobRelOff(obj, int(vt[GetReadVersionReplySlotTagThrottleInfo+2]), objPos, curOOL)
		curOOL += (len(m.TagThrottleInfo) + 3) &^ 3
	}
	if m.SsVersionVectorDelta != nil {
		binary.LittleEndian.PutUint32(buf[curOOL:], uint32(len(m.SsVersionVectorDelta)))
		copy(buf[curOOL+4:], m.SsVersionVectorDelta)
		wire.PatchBlobRelOff(obj, int(vt[GetReadVersionReplySlotSsVersionVectorDelta+2]), objPos, curOOL)
		curOOL += (4 + len(m.SsVersionVectorDelta) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *GetReadVersionReply) measureEndOff(endOff int) int {
	endOff = wire.MeasureRawOOL(endOff, m.TagThrottleInfo)
	endOff = wire.MeasureBytesOOL(endOff, m.SsVersionVectorDelta)
	endOff = wire.MeasureObject(endOff, GetReadVersionReplyVTable, GetReadVersionReplyMaxAlign)
	return endOff
}

func (m *GetReadVersionReply) writeDirect(dw *wire.DirectWriter) int {
	var tagThrottleInfoOOL int
	if m.TagThrottleInfo != nil {
		tagThrottleInfoOOL = dw.WriteRawOOL(m.TagThrottleInfo)
	}
	var ssVersionVectorDeltaOOL int
	if m.SsVersionVectorDelta != nil {
		ssVersionVectorDeltaOOL = dw.WriteBytesOOL(m.SsVersionVectorDelta)
	}
	objPos, obj := dw.WriteObject(GetReadVersionReplyVTable, GetReadVersionReplyMaxAlign)
	vt := GetReadVersionReplyVTable
	binary.LittleEndian.PutUint32(obj[int(vt[GetReadVersionReplySlotProcessBusyTime+2]):], uint32(m.ProcessBusyTime))
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotVersion+2]):], uint64(m.Version))
	if m.Locked {
		obj[int(vt[GetReadVersionReplySlotLocked+2])] = 1
	}
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotMidShardSize+2]):], uint64(m.MidShardSize))
	if m.RkDefaultThrottled {
		obj[int(vt[GetReadVersionReplySlotRkDefaultThrottled+2])] = 1
	}
	if m.RkBatchThrottled {
		obj[int(vt[GetReadVersionReplySlotRkBatchThrottled+2])] = 1
	}
	copy(obj[int(vt[GetReadVersionReplySlotProxyId+2]):], m.ProxyId[:])
	binary.LittleEndian.PutUint64(obj[int(vt[GetReadVersionReplySlotProxyTagThrottledDuration+2]):], math.Float64bits(m.ProxyTagThrottledDuration))
	if m.TagThrottleInfo != nil {
		wire.PatchRelOff(obj, int(vt[GetReadVersionReplySlotTagThrottleInfo+2]), objPos, tagThrottleInfoOOL)
	}
	if m.SsVersionVectorDelta != nil {
		wire.PatchRelOff(obj, int(vt[GetReadVersionReplySlotSsVersionVectorDelta+2]), objPos, ssVersionVectorDeltaOOL)
	}
	return objPos
}

func (m *GetReadVersionReply) MarshalFDB() []byte {
	t := GetReadVersionReplyTemplate
	endOff := 0
	endOff = wire.MeasureRawOOL(endOff, m.TagThrottleInfo)
	endOff = wire.MeasureBytesOOL(endOff, m.SsVersionVectorDelta)
	bodySize := int(GetReadVersionReplyVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 8 - 1) &^ (8 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseGetReadVersionReplyVectorFromReader reads a FlatBuffers vector of GetReadVersionReply.
func ParseGetReadVersionReplyVectorFromReader(r *wire.Reader, slot int) []GetReadVersionReply {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetReadVersionReply, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetReadVersionReply
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
