// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	GetReadVersionRequestSlotTransactionCount = 0
	GetReadVersionRequestSlotFlags            = 1
	GetReadVersionRequestSlotTags             = 2
	GetReadVersionRequestSlotDebugID          = 3
	GetReadVersionRequestSlotReply            = 5
	GetReadVersionRequestSlotSpanContext      = 6
	GetReadVersionRequestSlotMaxVersion       = 7
)

var GetReadVersionRequestVTable = wire.VTable{20, 37, 12, 16, 20, 36, 24, 28, 32, 4}

const GetReadVersionRequestFileID uint32 = 838566

var GetReadVersionRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
	{8, 12, 4, 8},
	{10, 29, 4, 20, 28},
	{20, 37, 12, 16, 20, 36, 24, 28, 32, 4},
}

var GetReadVersionRequestTemplate = wire.NewMessageTemplate(
	GetReadVersionRequestFileID, GetReadVersionRequestVTable, 8, GetReadVersionRequestVTableClosure,
)

const GetReadVersionRequestMaxAlign = 8

type GetReadVersionRequest struct {
	TransactionCount uint32       // slot 0
	Flags            uint32       // slot 1
	Tags             []byte       // slot 2
	HasDebugID       bool         // slot 3, optional tag
	DebugID          [16]byte     // slot 4, optional scalar value
	Reply            ReplyPromise // slot 5, nested
	SpanContext      SpanContext  // slot 6, nested
	MaxVersion       int64        // slot 7
}

func (m *GetReadVersionRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		copy(m.DebugID[:], r.ReadRelOffRaw(GetReadVersionRequestSlotDebugID+1, 16))
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
}

func (m *GetReadVersionRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GetReadVersionRequestSlotTransactionCount) {
		m.TransactionCount = r.ReadUint32(GetReadVersionRequestSlotTransactionCount)
	}
	if r.FieldPresent(GetReadVersionRequestSlotFlags) {
		m.Flags = r.ReadUint32(GetReadVersionRequestSlotFlags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotTags) {
		m.Tags = r.ReadBytes(GetReadVersionRequestSlotTags)
	}
	if r.FieldPresent(GetReadVersionRequestSlotDebugID) && r.ReadUint8(GetReadVersionRequestSlotDebugID) > 0 {
		copy(m.DebugID[:], r.ReadRelOffRaw(GetReadVersionRequestSlotDebugID+1, 16))
		m.HasDebugID = true
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(GetReadVersionRequestSlotSpanContext); err == nil {
		m.SpanContext.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(GetReadVersionRequestSlotMaxVersion) {
		m.MaxVersion = r.ReadInt64(GetReadVersionRequestSlotMaxVersion)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *GetReadVersionRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	ps.VisitDynamicSize(len(m.Tags))
	if m.HasDebugID {
		ps.Write(ps.CurrentBufferSize + 16)
	}
	m.Reply.precomputeSize(ps)
	m.SpanContext.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(int(GetReadVersionRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(GetReadVersionRequestVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *GetReadVersionRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var tagsOff int
	var debugIDOff int
	var replyStart int
	var spanContextStart int
	tagsOff, _ = wb.VisitDynamicSize(m.Tags)
	if m.HasDebugID {
		wb.Write(m.DebugID[:], wb.CurrentBufferSize+16)
		debugIDOff = wb.CurrentBufferSize
	}
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	spanContextStart = m.SpanContext.writeToBuffer(wb, vtableStart, tmpl)
	selfW := wb.GetMessageWriter(int(GetReadVersionRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := GetReadVersionRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(GetReadVersionRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(m.TransactionCount))
		selfW.WriteScalar(b[:], int(vt[GetReadVersionRequestSlotTransactionCount+2]))
	}
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(m.Flags))
		selfW.WriteScalar(b[:], int(vt[GetReadVersionRequestSlotFlags+2]))
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.MaxVersion))
		selfW.WriteScalar(b[:], int(vt[GetReadVersionRequestSlotMaxVersion+2]))
	}
	selfW.WriteRelativeOffset(tagsOff, int(vt[GetReadVersionRequestSlotTags+2]))
	if m.HasDebugID {
		selfW.WriteScalar([]byte{1}, int(vt[GetReadVersionRequestSlotDebugID+2]))
		selfW.WriteRelativeOffset(debugIDOff, int(vt[GetReadVersionRequestSlotDebugID+1+2]))
	}
	selfW.WriteRelativeOffset(replyStart, int(vt[GetReadVersionRequestSlotReply+2]))
	selfW.WriteRelativeOffset(spanContextStart, int(vt[GetReadVersionRequestSlotSpanContext+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *GetReadVersionRequest) MarshalFDB() []byte {
	t := GetReadVersionRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetReadVersionRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *GetReadVersionRequest) MarshalFDBPooled(dst []byte) []byte {
	t := GetReadVersionRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], GetReadVersionRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseGetReadVersionRequestVectorFromReader reads a FlatBuffers vector of GetReadVersionRequest.
func ParseGetReadVersionRequestVectorFromReader(r *wire.Reader, slot int) []GetReadVersionRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GetReadVersionRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GetReadVersionRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
