// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// GetValueRequest fields:
//
//	slot 0: key — serialize_member, size=4, align=4, indirection
//	slot 1: version — scalar, size=8, align=8
//	slot 2: tags — union_like, size=4, align=4, indirection
//	slot 4: reply — serialize_member, size=4, align=4, indirection
//	slot 5: spanContext — serialize_member, size=4, align=4, indirection
//	slot 6: tenantInfo — serialize_member, size=4, align=4, indirection
//	slot 7: options — union_like, size=4, align=4, indirection
//	slot 9: ssLatestCommitVersions — dynamic_size, size=4, align=4, indirection
const (
	GetValueRequestSlotKey                    = 0
	GetValueRequestSlotVersion                = 1
	GetValueRequestSlotTags                   = 2
	GetValueRequestSlotReply                  = 4
	GetValueRequestSlotSpanContext            = 5
	GetValueRequestSlotTenantInfo             = 6
	GetValueRequestSlotOptions                = 7
	GetValueRequestSlotSsLatestCommitVersions = 9
)

var GetValueRequestVTable = wire.VTable{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36}

const GetValueRequestFileID uint32 = 8454530

var GetValueRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{18, 20, 4, 16, 17, 8, 18, 12, 19},
	{10, 29, 4, 20, 28},
	{24, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36},
}

type GetValueRequest struct {
	// Key: nested struct at slot 0 — use ReadNestedReader(GetValueRequestSlotKey)
	Version int64  // slot 1, ReadInt64
	HasTags bool   // slot 2, Optional, presence flag
	Tags    []byte // slot 3, Optional, ReadBytes
	// Reply: nested struct at slot 4 — use ReadNestedReader(GetValueRequestSlotReply)
	// SpanContext: nested struct at slot 5 — use ReadNestedReader(GetValueRequestSlotSpanContext)
	// TenantInfo: nested struct at slot 6 — use ReadNestedReader(GetValueRequestSlotTenantInfo)
	HasOptions             bool   // slot 7, Optional, presence flag
	Options                []byte // slot 8, Optional, ReadBytes
	SsLatestCommitVersions []byte // slot 9, ReadBytes
}

func (m *GetValueRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	// Key (slot 0): nested struct — use r.ReadNestedReader(GetValueRequestSlotKey)
	if r.FieldPresent(GetValueRequestSlotVersion) {
		m.Version = r.ReadInt64(GetValueRequestSlotVersion)
	}
	if r.FieldPresent(GetValueRequestSlotTags) && r.ReadUint8(GetValueRequestSlotTags) > 0 {
		m.Tags = r.ReadBytes(GetValueRequestSlotTags + 1)
		m.HasTags = true
	}
	// Reply (slot 4): nested struct — use r.ReadNestedReader(GetValueRequestSlotReply)
	// SpanContext (slot 5): nested struct — use r.ReadNestedReader(GetValueRequestSlotSpanContext)
	// TenantInfo (slot 6): nested struct — use r.ReadNestedReader(GetValueRequestSlotTenantInfo)
	if r.FieldPresent(GetValueRequestSlotOptions) && r.ReadUint8(GetValueRequestSlotOptions) > 0 {
		m.Options = r.ReadBytes(GetValueRequestSlotOptions + 1)
		m.HasOptions = true
	}
	if r.FieldPresent(GetValueRequestSlotSsLatestCommitVersions) {
		m.SsLatestCommitVersions = r.ReadBytes(GetValueRequestSlotSsLatestCommitVersions)
	}
	return nil
}

func (m *GetValueRequest) MarshalInto(obj *wire.ObjectWriter) {
	vt := GetValueRequestVTable
	obj.WriteInt64(int(vt[GetValueRequestSlotVersion+2]), m.Version)
	obj.WriteBytes(int(vt[GetValueRequestSlotSsLatestCommitVersions+2]), m.SsLatestCommitVersions)
}

var GetValueRequestTemplate = wire.NewMessageTemplate(
	GetValueRequestFileID, GetValueRequestVTable, 8, GetValueRequestVTableClosure,
)
