// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// GrvProxyInterface fields:
//
//	slot 0: processId — union_like, size=4, align=4, indirection
//	slot 2: provisional — scalar, size=1, align=1
//	slot 3: getConsistentReadVersion — serialize_member, size=4, align=4, indirection
const (
	GrvProxyInterfaceSlotProcessId                = 0
	GrvProxyInterfaceSlotProvisional              = 2
	GrvProxyInterfaceSlotGetConsistentReadVersion = 3
)

var GrvProxyInterfaceVTable = wire.VTable{12, 14, 12, 4, 13, 8}

const GrvProxyInterfaceFileID uint32 = 8743216

type GrvProxyInterface struct {
	HasProcessId bool   // slot 0, Optional, presence flag
	ProcessId    []byte // slot 1, Optional, ReadBytes
	Provisional  bool   // slot 2, ReadBool
	// GetConsistentReadVersion: nested struct at slot 3 — use ReadNestedReader(GrvProxyInterfaceSlotGetConsistentReadVersion)
}
