// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	GrvProxyInterfaceSlotProcessId                = 0
	GrvProxyInterfaceSlotProvisional              = 2
	GrvProxyInterfaceSlotGetConsistentReadVersion = 3
)

var GrvProxyInterfaceVTable = wire.VTable{12, 14, 12, 4, 13, 8}

const GrvProxyInterfaceFileID uint32 = 8743216

type GrvProxyInterface struct {
	HasProcessId bool   // slot 0, optional tag
	ProcessId    []byte // slot 1, optional value
	Provisional  bool   // slot 2
	// GetConsistentReadVersion: unregistered nested struct at slot 3
}

func (m *GrvProxyInterface) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(GrvProxyInterfaceSlotProcessId) && r.ReadUint8(GrvProxyInterfaceSlotProcessId) > 0 {
		m.ProcessId = r.ReadBytes(GrvProxyInterfaceSlotProcessId + 1)
		m.HasProcessId = true
	}
	if r.FieldPresent(GrvProxyInterfaceSlotProvisional) {
		m.Provisional = r.ReadBool(GrvProxyInterfaceSlotProvisional)
	}
}

func (m *GrvProxyInterface) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(GrvProxyInterfaceSlotProcessId) && r.ReadUint8(GrvProxyInterfaceSlotProcessId) > 0 {
		m.ProcessId = r.ReadBytes(GrvProxyInterfaceSlotProcessId + 1)
		m.HasProcessId = true
	}
	if r.FieldPresent(GrvProxyInterfaceSlotProvisional) {
		m.Provisional = r.ReadBool(GrvProxyInterfaceSlotProvisional)
	}
	return nil
}

func (m *GrvProxyInterface) MarshalInto(obj *wire.ObjectWriter) {
	vt := GrvProxyInterfaceVTable
	obj.WriteBool(int(vt[GrvProxyInterfaceSlotProvisional+2]), m.Provisional)
}

func WriteGrvProxyInterface(obj *wire.ObjectWriter, parentOffset int, provisional bool) {
	m := GrvProxyInterface{Provisional: provisional}
	obj.WriteStruct(parentOffset, GrvProxyInterfaceVTable, 4, m.MarshalInto)
}

func MarshalGrvProxyInterface(provisional bool) []byte {
	m := GrvProxyInterface{Provisional: provisional}
	return wire.MarshalStructBlob(GrvProxyInterfaceVTable, m.MarshalInto)
}

// ParseGrvProxyInterfaceVectorFromReader reads a FlatBuffers vector of GrvProxyInterface.
func ParseGrvProxyInterfaceVectorFromReader(r *wire.Reader, slot int) []GrvProxyInterface {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]GrvProxyInterface, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem GrvProxyInterface
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
