// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	IPAddressSlotAddr = 0
)

var IPAddressVTable = wire.VTable{8, 9, 8, 4}
const IPAddressMaxAlign = 4

type IPAddress struct {
	AddrTag uint8 // slot 0, variant tag
	AddrAlt0 uint32 // tag=1
	AddrAlt1 []byte // tag=2
}

func (m *IPAddress) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(IPAddressSlotAddr) {
		m.AddrTag = r.ReadUint8(IPAddressSlotAddr)
		switch m.AddrTag {
		case 1:
			m.AddrAlt0 = r.ReadRelOffUint32(IPAddressSlotAddr + 1)
		case 2:
			m.AddrAlt1 = r.ReadRelOffRaw(IPAddressSlotAddr + 1, 4)
		}
	}
}

func (m *IPAddress) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if r.FieldPresent(IPAddressSlotAddr) {
		m.AddrTag = r.ReadUint8(IPAddressSlotAddr)
		switch m.AddrTag {
		case 1:
			m.AddrAlt0 = r.ReadRelOffUint32(IPAddressSlotAddr + 1)
		case 2:
			m.AddrAlt1 = r.ReadRelOffRaw(IPAddressSlotAddr + 1, 4)
		}
	}
	return nil
}

func (m *IPAddress) blobSize() int {
	vt := IPAddressVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	switch m.AddrTag {
	case 1:
		oolSize += (4 + 3) &^ 3
	case 2:
		oolSize += (len(m.AddrAlt1) + 3) &^ 3
	}
	return (oolPos + oolSize + 3) &^ 3
}

func (m *IPAddress) writeBlob(buf []byte, pos int) int {
	vt := IPAddressVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	obj[int(vt[IPAddressSlotAddr+2])] = m.AddrTag
	switch m.AddrTag {
	case 1:
		var tmp [4]byte
		binary.LittleEndian.PutUint32(tmp[:], m.AddrAlt0)
		copy(buf[curOOL:], tmp[:])
		wire.PatchBlobRelOff(obj, int(vt[IPAddressSlotAddr+1+2]), objPos, curOOL)
		curOOL += (4 + 3) &^ 3
	case 2:
		copy(buf[curOOL:], m.AddrAlt1)
		wire.PatchBlobRelOff(obj, int(vt[IPAddressSlotAddr+1+2]), objPos, curOOL)
		curOOL += (len(m.AddrAlt1) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *IPAddress) measureEndOff(endOff int) int {
	switch m.AddrTag {
	case 1:
		endOff += (4 + 3) &^ 3
	case 2:
		endOff += (len(m.AddrAlt1) + 3) &^ 3
	}
	endOff = wire.MeasureObject(endOff, IPAddressVTable, IPAddressMaxAlign)
	return endOff
}

func (m *IPAddress) writeDirect(dw *wire.DirectWriter) int {
	var addrOOL int
	switch m.AddrTag {
	case 1:
		var tmp [4]byte
		binary.LittleEndian.PutUint32(tmp[:], m.AddrAlt0)
		addrOOL = dw.WriteRawOOL(tmp[:])
	case 2:
		if m.AddrAlt1 != nil {
			addrOOL = dw.WriteRawOOL(m.AddrAlt1)
		}
	}
	objPos, obj := dw.WriteObject(IPAddressVTable, IPAddressMaxAlign)
	vt := IPAddressVTable
	obj[int(vt[IPAddressSlotAddr+2])] = m.AddrTag
	if m.AddrTag > 0 {
		wire.PatchRelOff(obj, int(vt[IPAddressSlotAddr+1+2]), objPos, addrOOL)
	}
	return objPos
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Returns end-offset of this object (C++ RelativeOffset). Same as save_helper return.
func (m *IPAddress) precomputeSize(ps *wire.PrecomputeSize) int {
	{ n := ps.GetMessageWriter(int(IPAddressVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(IPAddressVTable[1])-4, 4)+4) }
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Must call GetMessageWriter in the SAME order as precomputeSize.
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *IPAddress) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	selfW := wb.GetMessageWriter(int(IPAddressVTable[1]), true)
	selfStart := selfW.FinalLocation
	{ soff := int32(vtableStart - tmpl.VTableOffset(IPAddressVTable) - selfStart); var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(soff)); selfW.WriteScalar(b[:], 0) }
	selfW.WriteToAt(selfStart)
	return selfStart
}

// ParseIPAddressVectorFromReader reads a FlatBuffers vector of IPAddress.
func ParseIPAddressVectorFromReader(r *wire.Reader, slot int) []IPAddress {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]IPAddress, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem IPAddress
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

