// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	KeyRangeRefSlotBegin = 0
	KeyRangeRefSlotEnd   = 1
)

var KeyRangeRefVTable = wire.VTable{8, 12, 4, 8}

const KeyRangeRefMaxAlign = 4

type KeyRangeRef struct {
	Begin []byte // slot 0
	End   []byte // slot 1
}

// UnmarshalFromReader / UnmarshalFDB are defined in keyrangeref_custom.go to
// invert the C++ single-key-range serialize optimization. The generator
// (cmd/fdb-schema-extract/main.cpp) skips them when hasCustomSerialize is true.

// ParseKeyRangeRefVectorFromReader reads a FlatBuffers vector of KeyRangeRef.
func ParseKeyRangeRefVectorFromReader(r *wire.Reader, slot int) []KeyRangeRef {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]KeyRangeRef, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem KeyRangeRef
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

// ParseKeyRangeRefStringVector decodes a VectorRef<KeyRangeRef, VecSerStrategy::String>.
// Each element's DynamicSize fields are inline: [len(4)][data] per field.
func ParseKeyRangeRefStringVector(data []byte) []KeyRangeRef {
	if len(data) < 4 {
		return nil
	}
	count := binary.LittleEndian.Uint32(data[0:4])
	if count == 0 {
		return nil
	}
	// Cap allocation to prevent OOM from crafted count values.
	// Minimum 8 bytes per element (4-byte length prefix per field).
	maxCount := uint32((len(data) - 4) / 8)
	if maxCount == 0 {
		maxCount = 1
	}
	allocCount := count
	if allocCount > maxCount {
		allocCount = maxCount
	}
	pos := 4
	result := make([]KeyRangeRef, 0, allocCount)
	for i := uint32(0); i < count; i++ {
		var elem KeyRangeRef
		if pos+4 > len(data) {
			break
		}
		{
			n := int(binary.LittleEndian.Uint32(data[pos:]))
			pos += 4
			if n < 0 || pos+n > len(data) {
				break
			}
			elem.Begin = data[pos : pos+n : pos+n]
			pos += n
		}
		if pos+4 > len(data) {
			break
		}
		{
			n := int(binary.LittleEndian.Uint32(data[pos:]))
			pos += 4
			if n < 0 || pos+n > len(data) {
				break
			}
			elem.End = data[pos : pos+n : pos+n]
			pos += n
		}
		// Apply the same single-key-optimization inversion as
		// UnmarshalFromReader (see keyrangeref_custom.go). Without this, a
		// vector element written by C++'s optimization (begin+\x00 == end →
		// emit (end, empty)) would parse with Begin/End swapped.
		// Note: after inversion, elem.Begin and elem.End share the same
		// backing array (the original wire buffer). Same zero-copy
		// convention as the rest of this function.
		if len(elem.End) == 0 && len(elem.Begin) > 0 {
			first := elem.Begin
			elem.Begin = first[:len(first)-1]
			elem.End = first
		}
		result = append(result, elem)
	}
	return result
}
