// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// KeyRangeRef fields:
//
//	slot 0: const_cast<KeyRef&>(begin) — dynamic_size, size=4, align=4, indirection
//	slot 1: const_cast<KeyRef&>(end) — dynamic_size, size=4, align=4, indirection
const (
	KeyRangeRefSlotBegin = 0
	KeyRangeRefSlotEnd   = 1
)

var KeyRangeRefVTable = wire.VTable{8, 12, 4, 8}

type KeyRangeRef struct {
	Begin []byte // slot 0, ReadBytes
	End   []byte // slot 1, ReadBytes
}

func (m *KeyRangeRef) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(KeyRangeRefSlotBegin) {
		m.Begin = r.ReadBytes(KeyRangeRefSlotBegin)
	}
	if r.FieldPresent(KeyRangeRefSlotEnd) {
		m.End = r.ReadBytes(KeyRangeRefSlotEnd)
	}
	return nil
}

func (m *KeyRangeRef) MarshalInto(obj *wire.ObjectWriter) {
	vt := KeyRangeRefVTable
	if len(m.Begin) > 0 {
		obj.WriteBytes(int(vt[KeyRangeRefSlotBegin+2]), m.Begin)
	}
	if len(m.End) > 0 {
		obj.WriteBytes(int(vt[KeyRangeRefSlotEnd+2]), m.End)
	}
}

func WriteKeyRangeRef(obj *wire.ObjectWriter, parentOffset int, begin []byte, end []byte) {
	m := KeyRangeRef{Begin: begin, End: end}
	obj.WriteStruct(parentOffset, KeyRangeRefVTable, 4, m.MarshalInto)
}

func MarshalKeyRangeRef(begin []byte, end []byte) []byte {
	m := KeyRangeRef{Begin: begin, End: end}
	return wire.MarshalStructBlob(KeyRangeRefVTable, m.MarshalInto)
}
