// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	KeySelectorRefSlotKey     = 0
	KeySelectorRefSlotOrEqual = 1
	KeySelectorRefSlotOffset  = 2
)

var KeySelectorRefVTable = wire.VTable{10, 13, 4, 12, 8}

type KeySelectorRef struct {
	Key     []byte // slot 0
	OrEqual bool   // slot 1
	Offset  int32  // slot 2
}

func (m *KeySelectorRef) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(KeySelectorRefSlotKey) {
		m.Key = r.ReadBytes(KeySelectorRefSlotKey)
	}
	if r.FieldPresent(KeySelectorRefSlotOrEqual) {
		m.OrEqual = r.ReadBool(KeySelectorRefSlotOrEqual)
	}
	if r.FieldPresent(KeySelectorRefSlotOffset) {
		m.Offset = r.ReadInt32(KeySelectorRefSlotOffset)
	}
}

func (m *KeySelectorRef) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(KeySelectorRefSlotKey) {
		m.Key = r.ReadBytes(KeySelectorRefSlotKey)
	}
	if r.FieldPresent(KeySelectorRefSlotOrEqual) {
		m.OrEqual = r.ReadBool(KeySelectorRefSlotOrEqual)
	}
	if r.FieldPresent(KeySelectorRefSlotOffset) {
		m.Offset = r.ReadInt32(KeySelectorRefSlotOffset)
	}
	return nil
}

func (m *KeySelectorRef) MarshalInto(obj *wire.ObjectWriter) {
	vt := KeySelectorRefVTable
	if m.Key != nil {
		obj.WriteBytes(int(vt[KeySelectorRefSlotKey+2]), m.Key)
	}
	obj.WriteBool(int(vt[KeySelectorRefSlotOrEqual+2]), m.OrEqual)
	obj.WriteInt32(int(vt[KeySelectorRefSlotOffset+2]), m.Offset)
}

func WriteKeySelectorRef(obj *wire.ObjectWriter, parentOffset int, key []byte, orEqual bool, offset int32) {
	m := KeySelectorRef{Key: key, OrEqual: orEqual, Offset: offset}
	obj.WriteStruct(parentOffset, KeySelectorRefVTable, 4, m.MarshalInto)
}

func MarshalKeySelectorRef(key []byte, orEqual bool, offset int32) []byte {
	m := KeySelectorRef{Key: key, OrEqual: orEqual, Offset: offset}
	return wire.MarshalStructBlob(KeySelectorRefVTable, m.MarshalInto)
}

// ParseKeySelectorRefVectorFromReader reads a FlatBuffers vector of KeySelectorRef.
func ParseKeySelectorRefVectorFromReader(r *wire.Reader, slot int) []KeySelectorRef {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]KeySelectorRef, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem KeySelectorRef
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
