// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// KeySelectorRef fields:
//
//	slot 0: key — dynamic_size, size=4, align=4, indirection
//	slot 1: orEqual — scalar, size=1, align=1
//	slot 2: offset — scalar, size=4, align=4
const (
	KeySelectorRefSlotKey     = 0
	KeySelectorRefSlotOrEqual = 1
	KeySelectorRefSlotOffset  = 2
)

var KeySelectorRefVTable = wire.VTable{10, 13, 4, 12, 8}

type KeySelectorRef struct {
	Key     []byte // slot 0, ReadBytes
	OrEqual bool   // slot 1, ReadBool
	Offset  int32  // slot 2, ReadInt32
}
