// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	LocationPairSlotKeyRange = 0
	LocationPairSlotServers  = 1
)

var LocationPairVTable = wire.VTable{8, 12, 4, 8}

type LocationPair struct {
	KeyRange KeyRangeRef // slot 0, nested
	Servers  []byte      // slot 1
}

func (m *LocationPair) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(LocationPairSlotKeyRange); err == nil {
		m.KeyRange.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(LocationPairSlotServers) {
		m.Servers = r.ReadBytes(LocationPairSlotServers)
	}
}

func (m *LocationPair) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(LocationPairSlotKeyRange); err == nil {
		m.KeyRange.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(LocationPairSlotServers) {
		m.Servers = r.ReadBytes(LocationPairSlotServers)
	}
	return nil
}

func (m *LocationPair) MarshalInto(obj *wire.ObjectWriter) {
	vt := LocationPairVTable
	obj.WriteStruct(int(vt[LocationPairSlotKeyRange+2]), KeyRangeRefVTable, 8, m.KeyRange.MarshalInto)
	if m.Servers != nil {
		obj.WriteRawOOL(int(vt[LocationPairSlotServers+2]), m.Servers)
	}
}

func WriteLocationPair(obj *wire.ObjectWriter, parentOffset int, servers []byte) {
	m := LocationPair{Servers: servers}
	obj.WriteStruct(parentOffset, LocationPairVTable, 4, m.MarshalInto)
}

func MarshalLocationPair(servers []byte) []byte {
	m := LocationPair{Servers: servers}
	return wire.MarshalStructBlob(LocationPairVTable, m.MarshalInto)
}

// ParseLocationPairVectorFromReader reads a FlatBuffers vector of LocationPair.
func ParseLocationPairVectorFromReader(r *wire.Reader, slot int) []LocationPair {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]LocationPair, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem LocationPair
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
