// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// MutationRef fields:
//
//	slot 0: field_0 — scalar, size=1, align=1
//	slot 1: field_1 — dynamic_size, size=4, align=4, indirection
//	slot 2: field_2 — dynamic_size, size=4, align=4, indirection
const (
	MutationRefSlotField_0 = 0
	MutationRefSlotField_1 = 1
	MutationRefSlotField_2 = 2
)

var MutationRefVTable = wire.VTable{10, 13, 12, 4, 8}

type MutationRef struct {
	Field_0 uint8  // slot 0, ReadUint8
	Field_1 []byte // slot 1, ReadBytes
	Field_2 []byte // slot 2, ReadBytes
}
