// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// NetworkAddressList fields:
//
//	slot 0: address — serialize_member, size=4, align=4, indirection
//	slot 1: secondaryAddress — union_like, size=4, align=4, indirection
const (
	NetworkAddressListSlotAddress          = 0
	NetworkAddressListSlotSecondaryAddress = 1
)

var NetworkAddressListVTable = wire.VTable{10, 13, 4, 12, 8}

type NetworkAddressList struct {
	Address             NetworkAddress // slot 0, nested
	HasSecondaryAddress bool           // slot 1, Optional, presence flag
	SecondaryAddress    []byte         // slot 2, Optional, ReadBytes
}

func (m *NetworkAddressList) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nestedR, err := r.ReadNestedReader(NetworkAddressListSlotAddress); err == nil {
		m.Address.UnmarshalFromReader(nestedR)
	}
	if r.FieldPresent(NetworkAddressListSlotSecondaryAddress) && r.ReadUint8(NetworkAddressListSlotSecondaryAddress) > 0 {
		m.SecondaryAddress = r.ReadBytes(NetworkAddressListSlotSecondaryAddress + 1)
		m.HasSecondaryAddress = true
	}
	return nil
}

func (m *NetworkAddressList) UnmarshalFromReader(r *wire.Reader) {
	if nestedR, err := r.ReadNestedReader(NetworkAddressListSlotAddress); err == nil {
		m.Address.UnmarshalFromReader(nestedR)
	}
	if r.FieldPresent(NetworkAddressListSlotSecondaryAddress) && r.ReadUint8(NetworkAddressListSlotSecondaryAddress) > 0 {
		m.SecondaryAddress = r.ReadBytes(NetworkAddressListSlotSecondaryAddress + 1)
		m.HasSecondaryAddress = true
	}
}

func (m *NetworkAddressList) MarshalInto(obj *wire.ObjectWriter) {
}

func WriteNetworkAddressList(obj *wire.ObjectWriter, parentOffset int) {
	m := NetworkAddressList{}
	obj.WriteStruct(parentOffset, NetworkAddressListVTable, 4, m.MarshalInto)
}

func MarshalNetworkAddressList() []byte {
	m := NetworkAddressList{}
	return wire.MarshalStructBlob(NetworkAddressListVTable, m.MarshalInto)
}
