// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	NetworkAddressListSlotAddress          = 0
	NetworkAddressListSlotSecondaryAddress = 1
)

var NetworkAddressListVTable = wire.VTable{10, 13, 4, 12, 8}

const NetworkAddressListMaxAlign = 4

type NetworkAddressList struct {
	Address             NetworkAddress // slot 0, nested
	HasSecondaryAddress bool           // slot 1, optional tag
	SecondaryAddress    []byte         // slot 2, optional value
}

func (m *NetworkAddressList) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(NetworkAddressListSlotAddress); err == nil {
		m.Address.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(NetworkAddressListSlotSecondaryAddress) && r.ReadUint8(NetworkAddressListSlotSecondaryAddress) > 0 {
		m.SecondaryAddress = r.ReadBytes(NetworkAddressListSlotSecondaryAddress + 1)
		m.HasSecondaryAddress = true
	}
}

func (m *NetworkAddressList) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(NetworkAddressListSlotAddress); err == nil {
		m.Address.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(NetworkAddressListSlotSecondaryAddress) && r.ReadUint8(NetworkAddressListSlotSecondaryAddress) > 0 {
		m.SecondaryAddress = r.ReadBytes(NetworkAddressListSlotSecondaryAddress + 1)
		m.HasSecondaryAddress = true
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *NetworkAddressList) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Address.precomputeSize(ps)
	if m.HasSecondaryAddress {
		ps.VisitDynamicSize(len(m.SecondaryAddress))
	}
	{
		n := ps.GetMessageWriter(int(NetworkAddressListVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(NetworkAddressListVTable[1])-4, 4)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *NetworkAddressList) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var addressStart int
	var secondaryAddressOff int
	addressStart = m.Address.writeToBuffer(wb, vtableStart, tmpl)
	if m.HasSecondaryAddress {
		secondaryAddressOff, _ = wb.VisitDynamicSize(m.SecondaryAddress)
	}
	selfW := wb.GetMessageWriter(int(NetworkAddressListVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := NetworkAddressListVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(NetworkAddressListVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	selfW.WriteRelativeOffset(addressStart, int(vt[NetworkAddressListSlotAddress+2]))
	if m.HasSecondaryAddress {
		selfW.WriteScalar([]byte{1}, int(vt[NetworkAddressListSlotSecondaryAddress+2]))
		selfW.WriteRelativeOffset(secondaryAddressOff, int(vt[NetworkAddressListSlotSecondaryAddress+1+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

// ParseNetworkAddressListVectorFromReader reads a FlatBuffers vector of NetworkAddressList.
func ParseNetworkAddressListVectorFromReader(r *wire.Reader, slot int) []NetworkAddressList {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]NetworkAddressList, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem NetworkAddressList
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
