// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	OpenDatabaseCoordRequestSlotIssues            = 0
	OpenDatabaseCoordRequestSlotSupportedVersions = 1
	OpenDatabaseCoordRequestSlotTraceLogGroup     = 2
	OpenDatabaseCoordRequestSlotKnownClientInfoID = 3
	OpenDatabaseCoordRequestSlotClusterKey        = 4
	OpenDatabaseCoordRequestSlotCoordinators      = 5
	OpenDatabaseCoordRequestSlotReply             = 6
	OpenDatabaseCoordRequestSlotHostnames         = 7
	OpenDatabaseCoordRequestSlotInternal          = 8
)

var OpenDatabaseCoordRequestVTable = wire.VTable{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48}

const OpenDatabaseCoordRequestFileID uint32 = 214728

var OpenDatabaseCoordRequestVTableClosure = []wire.VTable{
	{10, 13, 4, 8, 12},
	{6, 20, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48},
	{10, 16, 4, 8, 12},
}

var OpenDatabaseCoordRequestTemplate = wire.NewMessageTemplate(
	OpenDatabaseCoordRequestFileID, OpenDatabaseCoordRequestVTable, 8, OpenDatabaseCoordRequestVTableClosure,
)

const OpenDatabaseCoordRequestMaxAlign = 8

type OpenDatabaseCoordRequest struct {
	Issues            []byte       // slot 0
	SupportedVersions []byte       // slot 1
	TraceLogGroup     []byte       // slot 2
	KnownClientInfoID [16]byte     // slot 3
	ClusterKey        []byte       // slot 4
	Coordinators      []byte       // slot 5
	Reply             ReplyPromise // slot 6, nested
	Hostnames         []byte       // slot 7
	Internal          bool         // slot 8
}

func (m *OpenDatabaseCoordRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(OpenDatabaseCoordRequestSlotIssues) {
		m.Issues = r.ReadBytes(OpenDatabaseCoordRequestSlotIssues)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotSupportedVersions) {
		m.SupportedVersions = r.ReadBytes(OpenDatabaseCoordRequestSlotSupportedVersions)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotTraceLogGroup) {
		m.TraceLogGroup = r.ReadBytes(OpenDatabaseCoordRequestSlotTraceLogGroup)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotKnownClientInfoID) {
		m.KnownClientInfoID = r.ReadUID(OpenDatabaseCoordRequestSlotKnownClientInfoID)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotClusterKey) {
		m.ClusterKey = r.ReadBytes(OpenDatabaseCoordRequestSlotClusterKey)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotCoordinators) {
		m.Coordinators = r.ReadBytes(OpenDatabaseCoordRequestSlotCoordinators)
	}
	if nr, err := r.ReadNestedReader(OpenDatabaseCoordRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotHostnames) {
		m.Hostnames = r.ReadBytes(OpenDatabaseCoordRequestSlotHostnames)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotInternal) {
		m.Internal = r.ReadBool(OpenDatabaseCoordRequestSlotInternal)
	}
}

func (m *OpenDatabaseCoordRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotIssues) {
		m.Issues = r.ReadBytes(OpenDatabaseCoordRequestSlotIssues)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotSupportedVersions) {
		m.SupportedVersions = r.ReadBytes(OpenDatabaseCoordRequestSlotSupportedVersions)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotTraceLogGroup) {
		m.TraceLogGroup = r.ReadBytes(OpenDatabaseCoordRequestSlotTraceLogGroup)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotKnownClientInfoID) {
		m.KnownClientInfoID = r.ReadUID(OpenDatabaseCoordRequestSlotKnownClientInfoID)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotClusterKey) {
		m.ClusterKey = r.ReadBytes(OpenDatabaseCoordRequestSlotClusterKey)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotCoordinators) {
		m.Coordinators = r.ReadBytes(OpenDatabaseCoordRequestSlotCoordinators)
	}
	if nr, err := r.ReadNestedReader(OpenDatabaseCoordRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotHostnames) {
		m.Hostnames = r.ReadBytes(OpenDatabaseCoordRequestSlotHostnames)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotInternal) {
		m.Internal = r.ReadBool(OpenDatabaseCoordRequestSlotInternal)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *OpenDatabaseCoordRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	ps.VisitDynamicSize(len(m.Issues))
	ps.VisitDynamicSize(len(m.SupportedVersions))
	ps.VisitDynamicSize(len(m.TraceLogGroup))
	ps.VisitDynamicSize(len(m.ClusterKey))
	ps.VisitDynamicSize(len(m.Coordinators))
	m.Reply.precomputeSize(ps)
	ps.VisitDynamicSize(len(m.Hostnames))
	{
		n := ps.GetMessageWriter(int(OpenDatabaseCoordRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(OpenDatabaseCoordRequestVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *OpenDatabaseCoordRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var issuesOff int
	var supportedVersionsOff int
	var traceLogGroupOff int
	var clusterKeyOff int
	var coordinatorsOff int
	var replyStart int
	var hostnamesOff int
	issuesOff, _ = wb.VisitDynamicSize(m.Issues)
	supportedVersionsOff, _ = wb.VisitDynamicSize(m.SupportedVersions)
	traceLogGroupOff, _ = wb.VisitDynamicSize(m.TraceLogGroup)
	clusterKeyOff, _ = wb.VisitDynamicSize(m.ClusterKey)
	coordinatorsOff, _ = wb.VisitDynamicSize(m.Coordinators)
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	hostnamesOff, _ = wb.VisitDynamicSize(m.Hostnames)
	selfW := wb.GetMessageWriter(int(OpenDatabaseCoordRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := OpenDatabaseCoordRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(OpenDatabaseCoordRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	selfW.WriteScalar(m.KnownClientInfoID[:], int(vt[OpenDatabaseCoordRequestSlotKnownClientInfoID+2]))
	if m.Internal {
		selfW.WriteScalar([]byte{1}, int(vt[OpenDatabaseCoordRequestSlotInternal+2]))
	}
	selfW.WriteRelativeOffset(issuesOff, int(vt[OpenDatabaseCoordRequestSlotIssues+2]))
	selfW.WriteRelativeOffset(supportedVersionsOff, int(vt[OpenDatabaseCoordRequestSlotSupportedVersions+2]))
	selfW.WriteRelativeOffset(traceLogGroupOff, int(vt[OpenDatabaseCoordRequestSlotTraceLogGroup+2]))
	selfW.WriteRelativeOffset(clusterKeyOff, int(vt[OpenDatabaseCoordRequestSlotClusterKey+2]))
	selfW.WriteRelativeOffset(coordinatorsOff, int(vt[OpenDatabaseCoordRequestSlotCoordinators+2]))
	selfW.WriteRelativeOffset(replyStart, int(vt[OpenDatabaseCoordRequestSlotReply+2]))
	selfW.WriteRelativeOffset(hostnamesOff, int(vt[OpenDatabaseCoordRequestSlotHostnames+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *OpenDatabaseCoordRequest) MarshalFDB() []byte {
	t := OpenDatabaseCoordRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], OpenDatabaseCoordRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *OpenDatabaseCoordRequest) MarshalFDBPooled(dst []byte) []byte {
	t := OpenDatabaseCoordRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], OpenDatabaseCoordRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseOpenDatabaseCoordRequestVectorFromReader reads a FlatBuffers vector of OpenDatabaseCoordRequest.
func ParseOpenDatabaseCoordRequestVectorFromReader(r *wire.Reader, slot int) []OpenDatabaseCoordRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]OpenDatabaseCoordRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem OpenDatabaseCoordRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
