// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// OpenDatabaseCoordRequest fields:
//
//	slot 0: issues — serialize_member, size=4, align=4, indirection
//	slot 1: supportedVersions — serialize_member, size=4, align=4, indirection
//	slot 2: traceLogGroup — serialize_member, size=4, align=4, indirection
//	slot 3: knownClientInfoID — scalar, size=16, align=8
//	slot 4: clusterKey — serialize_member, size=4, align=4, indirection
//	slot 5: coordinators — vector_like, size=4, align=4, indirection
//	slot 6: reply — serialize_member, size=4, align=4, indirection
//	slot 7: hostnames — vector_like, size=4, align=4, indirection
//	slot 8: internal — scalar, size=1, align=1
const (
	OpenDatabaseCoordRequestSlotIssues            = 0
	OpenDatabaseCoordRequestSlotSupportedVersions = 1
	OpenDatabaseCoordRequestSlotTraceLogGroup     = 2
	OpenDatabaseCoordRequestSlotKnownClientInfoID = 3
	OpenDatabaseCoordRequestSlotClusterKey        = 4
	OpenDatabaseCoordRequestSlotCoordinators      = 5
	OpenDatabaseCoordRequestSlotReply             = 6
	OpenDatabaseCoordRequestSlotHostnames         = 7
	OpenDatabaseCoordRequestSlotInternal          = 8
)

var OpenDatabaseCoordRequestVTable = wire.VTable{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48}

const OpenDatabaseCoordRequestFileID uint32 = 214728

var OpenDatabaseCoordRequestVTableClosure = []wire.VTable{
	{10, 13, 4, 8, 12},
	{6, 20, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48},
	{10, 16, 4, 8, 12},
}

type OpenDatabaseCoordRequest struct {
	// Issues: nested struct at slot 0 — use ReadNestedReader(OpenDatabaseCoordRequestSlotIssues)
	// SupportedVersions: nested struct at slot 1 — use ReadNestedReader(OpenDatabaseCoordRequestSlotSupportedVersions)
	// TraceLogGroup: nested struct at slot 2 — use ReadNestedReader(OpenDatabaseCoordRequestSlotTraceLogGroup)
	KnownClientInfoID []byte // slot 3, ReadBytes
	// ClusterKey: nested struct at slot 4 — use ReadNestedReader(OpenDatabaseCoordRequestSlotClusterKey)
	ClusterKey   string // marshal-only: cluster key string
	Coordinators []byte // slot 5, ReadBytes
	// Reply: nested struct at slot 6 — use ReadNestedReader(OpenDatabaseCoordRequestSlotReply)
	ReplyFirst  uint64 // marshal-only: reply promise UID first
	ReplySecond uint64 // marshal-only: reply promise UID second
	Hostnames   []byte // slot 7, ReadBytes
	Internal    bool   // slot 8, ReadBool
}

var OpenDatabaseCoordRequestTemplate = wire.NewMessageTemplate(
	OpenDatabaseCoordRequestFileID, OpenDatabaseCoordRequestVTable, 8, OpenDatabaseCoordRequestVTableClosure,
)
