// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// OpenDatabaseCoordRequest fields:
//
//	slot 0: issues — vector_like, size=4, align=4, indirection
//	slot 1: supportedVersions — vector_like, size=4, align=4, indirection
//	slot 2: traceLogGroup — dynamic_size, size=4, align=4, indirection
//	slot 3: knownClientInfoID — scalar, size=16, align=8
//	slot 4: clusterKey — dynamic_size, size=4, align=4, indirection
//	slot 5: coordinators — vector_like, size=4, align=4, indirection
//	slot 6: reply — serialize_member, size=4, align=4, indirection
//	slot 7: hostnames — vector_like, size=4, align=4, indirection
//	slot 8: internal — scalar, size=1, align=1
const (
	OpenDatabaseCoordRequestSlotIssues            = 0
	OpenDatabaseCoordRequestSlotSupportedVersions = 1
	OpenDatabaseCoordRequestSlotTraceLogGroup     = 2
	OpenDatabaseCoordRequestSlotKnownClientInfoID = 3
	OpenDatabaseCoordRequestSlotClusterKey        = 4
	OpenDatabaseCoordRequestSlotCoordinators      = 5
	OpenDatabaseCoordRequestSlotReply             = 6
	OpenDatabaseCoordRequestSlotHostnames         = 7
	OpenDatabaseCoordRequestSlotInternal          = 8
)

var OpenDatabaseCoordRequestVTable = wire.VTable{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48}

const OpenDatabaseCoordRequestFileID uint32 = 214728

var OpenDatabaseCoordRequestVTableClosure = []wire.VTable{
	{10, 13, 4, 8, 12},
	{6, 20, 4},
	{8, 9, 8, 4},
	{12, 13, 4, 8, 10, 12},
	{6, 8, 4},
	{22, 49, 20, 24, 28, 4, 32, 36, 40, 44, 48},
	{10, 16, 4, 8, 12},
}

type OpenDatabaseCoordRequest struct {
	Issues            []byte       // slot 0, ReadBytes
	SupportedVersions []byte       // slot 1, ReadBytes
	TraceLogGroup     []byte       // slot 2, ReadBytes
	KnownClientInfoID [16]byte     // slot 3, ReadUID
	ClusterKey        []byte       // slot 4, ReadBytes
	Coordinators      []byte       // slot 5, ReadBytes
	Reply             ReplyPromise // slot 6, nested
	Hostnames         []byte       // slot 7, ReadBytes
	Internal          bool         // slot 8, ReadBool
}

func (m *OpenDatabaseCoordRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotIssues) {
		m.Issues = r.ReadBytes(OpenDatabaseCoordRequestSlotIssues)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotSupportedVersions) {
		m.SupportedVersions = r.ReadBytes(OpenDatabaseCoordRequestSlotSupportedVersions)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotTraceLogGroup) {
		m.TraceLogGroup = r.ReadBytes(OpenDatabaseCoordRequestSlotTraceLogGroup)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotKnownClientInfoID) {
		m.KnownClientInfoID = r.ReadUID(OpenDatabaseCoordRequestSlotKnownClientInfoID)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotClusterKey) {
		m.ClusterKey = r.ReadBytes(OpenDatabaseCoordRequestSlotClusterKey)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotCoordinators) {
		m.Coordinators = r.ReadBytes(OpenDatabaseCoordRequestSlotCoordinators)
	}
	if nestedR, err := r.ReadNestedReader(OpenDatabaseCoordRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nestedR)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotHostnames) {
		m.Hostnames = r.ReadBytes(OpenDatabaseCoordRequestSlotHostnames)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotInternal) {
		m.Internal = r.ReadBool(OpenDatabaseCoordRequestSlotInternal)
	}
	return nil
}

func (m *OpenDatabaseCoordRequest) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(OpenDatabaseCoordRequestSlotIssues) {
		m.Issues = r.ReadBytes(OpenDatabaseCoordRequestSlotIssues)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotSupportedVersions) {
		m.SupportedVersions = r.ReadBytes(OpenDatabaseCoordRequestSlotSupportedVersions)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotTraceLogGroup) {
		m.TraceLogGroup = r.ReadBytes(OpenDatabaseCoordRequestSlotTraceLogGroup)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotKnownClientInfoID) {
		m.KnownClientInfoID = r.ReadUID(OpenDatabaseCoordRequestSlotKnownClientInfoID)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotClusterKey) {
		m.ClusterKey = r.ReadBytes(OpenDatabaseCoordRequestSlotClusterKey)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotCoordinators) {
		m.Coordinators = r.ReadBytes(OpenDatabaseCoordRequestSlotCoordinators)
	}
	if nestedR, err := r.ReadNestedReader(OpenDatabaseCoordRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nestedR)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotHostnames) {
		m.Hostnames = r.ReadBytes(OpenDatabaseCoordRequestSlotHostnames)
	}
	if r.FieldPresent(OpenDatabaseCoordRequestSlotInternal) {
		m.Internal = r.ReadBool(OpenDatabaseCoordRequestSlotInternal)
	}
}

func (m *OpenDatabaseCoordRequest) MarshalInto(obj *wire.ObjectWriter) {
	vt := OpenDatabaseCoordRequestVTable
	if len(m.Issues) > 0 {
		obj.WriteRawOOL(int(vt[OpenDatabaseCoordRequestSlotIssues+2]), m.Issues)
	}
	if len(m.SupportedVersions) > 0 {
		obj.WriteRawOOL(int(vt[OpenDatabaseCoordRequestSlotSupportedVersions+2]), m.SupportedVersions)
	}
	if len(m.TraceLogGroup) > 0 {
		obj.WriteBytes(int(vt[OpenDatabaseCoordRequestSlotTraceLogGroup+2]), m.TraceLogGroup)
	}
	obj.WriteUID(int(vt[OpenDatabaseCoordRequestSlotKnownClientInfoID+2]), m.KnownClientInfoID)
	if len(m.ClusterKey) > 0 {
		obj.WriteBytes(int(vt[OpenDatabaseCoordRequestSlotClusterKey+2]), m.ClusterKey)
	}
	if len(m.Coordinators) > 0 {
		obj.WriteRawOOL(int(vt[OpenDatabaseCoordRequestSlotCoordinators+2]), m.Coordinators)
	}
	if len(m.Hostnames) > 0 {
		obj.WriteRawOOL(int(vt[OpenDatabaseCoordRequestSlotHostnames+2]), m.Hostnames)
	}
	obj.WriteBool(int(vt[OpenDatabaseCoordRequestSlotInternal+2]), m.Internal)
}

func WriteOpenDatabaseCoordRequest(obj *wire.ObjectWriter, parentOffset int, issues []byte, supportedVersions []byte, traceLogGroup []byte, knownClientInfoID [16]byte, clusterKey []byte, coordinators []byte, hostnames []byte, internal bool) {
	m := OpenDatabaseCoordRequest{Issues: issues, SupportedVersions: supportedVersions, TraceLogGroup: traceLogGroup, KnownClientInfoID: knownClientInfoID, ClusterKey: clusterKey, Coordinators: coordinators, Hostnames: hostnames, Internal: internal}
	obj.WriteStruct(parentOffset, OpenDatabaseCoordRequestVTable, 8, m.MarshalInto)
}

func MarshalOpenDatabaseCoordRequest(issues []byte, supportedVersions []byte, traceLogGroup []byte, knownClientInfoID [16]byte, clusterKey []byte, coordinators []byte, hostnames []byte, internal bool) []byte {
	m := OpenDatabaseCoordRequest{Issues: issues, SupportedVersions: supportedVersions, TraceLogGroup: traceLogGroup, KnownClientInfoID: knownClientInfoID, ClusterKey: clusterKey, Coordinators: coordinators, Hostnames: hostnames, Internal: internal}
	return wire.MarshalStructBlob(OpenDatabaseCoordRequestVTable, m.MarshalInto)
}

func (m *OpenDatabaseCoordRequest) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessagePacked(OpenDatabaseCoordRequestTemplate, func(obj *wire.ObjectWriter) {
		if len(m.Issues) > 0 {
			obj.WriteRawOOL(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotIssues+2]), m.Issues)
		}
		if len(m.SupportedVersions) > 0 {
			obj.WriteRawOOL(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotSupportedVersions+2]), m.SupportedVersions)
		}
		if len(m.TraceLogGroup) > 0 {
			obj.WriteBytes(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotTraceLogGroup+2]), m.TraceLogGroup)
		}
		obj.WriteUID(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotKnownClientInfoID+2]), m.KnownClientInfoID)
		if len(m.ClusterKey) > 0 {
			obj.WriteBytes(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotClusterKey+2]), m.ClusterKey)
		}
		if len(m.Coordinators) > 0 {
			obj.WriteRawOOL(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotCoordinators+2]), m.Coordinators)
		}
		obj.WriteStruct(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotReply+2]), ReplyPromiseVTable, 8, m.Reply.MarshalInto)
		if len(m.Hostnames) > 0 {
			obj.WriteRawOOL(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotHostnames+2]), m.Hostnames)
		}
		obj.WriteBool(int(OpenDatabaseCoordRequestVTable[OpenDatabaseCoordRequestSlotInternal+2]), m.Internal)
	})
}

var OpenDatabaseCoordRequestTemplate = wire.NewMessageTemplate(
	OpenDatabaseCoordRequestFileID, OpenDatabaseCoordRequestVTable, 8, OpenDatabaseCoordRequestVTableClosure,
)
