// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	ReadOptionsSlotType = 0
	ReadOptionsSlotCacheResult = 1
	ReadOptionsSlotLockAware = 2
	ReadOptionsSlotField_4 = 4
	ReadOptionsSlotField_6 = 6
)

var ReadOptionsVTable = wire.VTable{18, 20, 4, 16, 17, 8, 18, 12, 19}
const ReadOptionsMaxAlign = 4

type ReadOptions struct {
	Type int32 // slot 0
	CacheResult bool // slot 1
	HasLockAware bool   // slot 2, optional tag
	LockAware    []byte // slot 3, optional value
	HasField_4 bool   // slot 4, optional tag
	Field_4    []byte // slot 5, optional value
	Field_6 bool // slot 6
}

func (m *ReadOptions) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ReadOptionsSlotType) {
		m.Type = r.ReadInt32(ReadOptionsSlotType)
	}
	if r.FieldPresent(ReadOptionsSlotCacheResult) {
		m.CacheResult = r.ReadBool(ReadOptionsSlotCacheResult)
	}
	if r.FieldPresent(ReadOptionsSlotLockAware) && r.ReadUint8(ReadOptionsSlotLockAware) > 0 {
		m.LockAware = r.ReadBytes(ReadOptionsSlotLockAware + 1)
		m.HasLockAware = true
	}
	if r.FieldPresent(ReadOptionsSlotField_4) && r.ReadUint8(ReadOptionsSlotField_4) > 0 {
		m.Field_4 = r.ReadBytes(ReadOptionsSlotField_4 + 1)
		m.HasField_4 = true
	}
	if r.FieldPresent(ReadOptionsSlotField_6) {
		m.Field_6 = r.ReadBool(ReadOptionsSlotField_6)
	}
}

func (m *ReadOptions) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil { return err }
	if r.FieldPresent(ReadOptionsSlotType) {
		m.Type = r.ReadInt32(ReadOptionsSlotType)
	}
	if r.FieldPresent(ReadOptionsSlotCacheResult) {
		m.CacheResult = r.ReadBool(ReadOptionsSlotCacheResult)
	}
	if r.FieldPresent(ReadOptionsSlotLockAware) && r.ReadUint8(ReadOptionsSlotLockAware) > 0 {
		m.LockAware = r.ReadBytes(ReadOptionsSlotLockAware + 1)
		m.HasLockAware = true
	}
	if r.FieldPresent(ReadOptionsSlotField_4) && r.ReadUint8(ReadOptionsSlotField_4) > 0 {
		m.Field_4 = r.ReadBytes(ReadOptionsSlotField_4 + 1)
		m.HasField_4 = true
	}
	if r.FieldPresent(ReadOptionsSlotField_6) {
		m.Field_6 = r.ReadBool(ReadOptionsSlotField_6)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *ReadOptions) precomputeSize(ps *wire.PrecomputeSize) int {
	if m.HasLockAware { ps.VisitDynamicSize(len(m.LockAware)) }
	if m.HasField_4 { ps.VisitDynamicSize(len(m.Field_4)) }
	{ n := ps.GetMessageWriter(int(ReadOptionsVTable[1])); n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(ReadOptionsVTable[1])-4, 4)+4) }
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *ReadOptions) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var lockAwareOff int
	var field_4Off int
	if m.HasLockAware { lockAwareOff, _ = wb.VisitDynamicSize(m.LockAware) }
	if m.HasField_4 { field_4Off, _ = wb.VisitDynamicSize(m.Field_4) }
	selfW := wb.GetMessageWriter(int(ReadOptionsVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := ReadOptionsVTable
	{ soff := int32(vtableStart - tmpl.VTableOffset(ReadOptionsVTable) - selfStart); var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(soff)); selfW.WriteScalar(b[:], 0) }
	{ var b [4]byte; binary.LittleEndian.PutUint32(b[:], uint32(m.Type)); selfW.WriteScalar(b[:], int(vt[ReadOptionsSlotType+2])) }
	if m.CacheResult { selfW.WriteScalar([]byte{1}, int(vt[ReadOptionsSlotCacheResult+2])) }
	if m.Field_6 { selfW.WriteScalar([]byte{1}, int(vt[ReadOptionsSlotField_6+2])) }
	if m.HasLockAware {
		selfW.WriteScalar([]byte{1}, int(vt[ReadOptionsSlotLockAware+2]))
		selfW.WriteRelativeOffset(lockAwareOff, int(vt[ReadOptionsSlotLockAware+1+2]))
	}
	if m.HasField_4 {
		selfW.WriteScalar([]byte{1}, int(vt[ReadOptionsSlotField_4+2]))
		selfW.WriteRelativeOffset(field_4Off, int(vt[ReadOptionsSlotField_4+1+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

// ParseReadOptionsVectorFromReader reads a FlatBuffers vector of ReadOptions.
func ParseReadOptionsVectorFromReader(r *wire.Reader, slot int) []ReadOptions {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 { return nil }
	result := make([]ReadOptions, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil { continue }
		var elem ReadOptions
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}

