// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	ReadOptionsSlotType        = 0
	ReadOptionsSlotCacheResult = 1
	ReadOptionsSlotLockAware   = 2
	ReadOptionsSlotField_4     = 4
	ReadOptionsSlotField_6     = 6
)

var ReadOptionsVTable = wire.VTable{18, 20, 4, 16, 17, 8, 18, 12, 19}

type ReadOptions struct {
	Type         int32  // slot 0
	CacheResult  bool   // slot 1
	HasLockAware bool   // slot 2, optional tag
	LockAware    []byte // slot 3, optional value
	HasField_4   bool   // slot 4, optional tag
	Field_4      []byte // slot 5, optional value
	Field_6      bool   // slot 6
}

func (m *ReadOptions) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ReadOptionsSlotType) {
		m.Type = r.ReadInt32(ReadOptionsSlotType)
	}
	if r.FieldPresent(ReadOptionsSlotCacheResult) {
		m.CacheResult = r.ReadBool(ReadOptionsSlotCacheResult)
	}
	if r.FieldPresent(ReadOptionsSlotLockAware) && r.ReadUint8(ReadOptionsSlotLockAware) > 0 {
		m.LockAware = r.ReadBytes(ReadOptionsSlotLockAware + 1)
		m.HasLockAware = true
	}
	if r.FieldPresent(ReadOptionsSlotField_4) && r.ReadUint8(ReadOptionsSlotField_4) > 0 {
		m.Field_4 = r.ReadBytes(ReadOptionsSlotField_4 + 1)
		m.HasField_4 = true
	}
	if r.FieldPresent(ReadOptionsSlotField_6) {
		m.Field_6 = r.ReadBool(ReadOptionsSlotField_6)
	}
}

func (m *ReadOptions) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ReadOptionsSlotType) {
		m.Type = r.ReadInt32(ReadOptionsSlotType)
	}
	if r.FieldPresent(ReadOptionsSlotCacheResult) {
		m.CacheResult = r.ReadBool(ReadOptionsSlotCacheResult)
	}
	if r.FieldPresent(ReadOptionsSlotLockAware) && r.ReadUint8(ReadOptionsSlotLockAware) > 0 {
		m.LockAware = r.ReadBytes(ReadOptionsSlotLockAware + 1)
		m.HasLockAware = true
	}
	if r.FieldPresent(ReadOptionsSlotField_4) && r.ReadUint8(ReadOptionsSlotField_4) > 0 {
		m.Field_4 = r.ReadBytes(ReadOptionsSlotField_4 + 1)
		m.HasField_4 = true
	}
	if r.FieldPresent(ReadOptionsSlotField_6) {
		m.Field_6 = r.ReadBool(ReadOptionsSlotField_6)
	}
	return nil
}

func (m *ReadOptions) MarshalInto(obj *wire.ObjectWriter) {
	vt := ReadOptionsVTable
	obj.WriteInt32(int(vt[ReadOptionsSlotType+2]), m.Type)
	obj.WriteBool(int(vt[ReadOptionsSlotCacheResult+2]), m.CacheResult)
	obj.WriteBool(int(vt[ReadOptionsSlotField_6+2]), m.Field_6)
}

func WriteReadOptions(obj *wire.ObjectWriter, parentOffset int, type_ int32, cacheResult bool, field_6 bool) {
	m := ReadOptions{Type: type_, CacheResult: cacheResult, Field_6: field_6}
	obj.WriteStruct(parentOffset, ReadOptionsVTable, 4, m.MarshalInto)
}

func MarshalReadOptions(type_ int32, cacheResult bool, field_6 bool) []byte {
	m := ReadOptions{Type: type_, CacheResult: cacheResult, Field_6: field_6}
	return wire.MarshalStructBlob(ReadOptionsVTable, m.MarshalInto)
}

// ParseReadOptionsVectorFromReader reads a FlatBuffers vector of ReadOptions.
func ParseReadOptionsVectorFromReader(r *wire.Reader, slot int) []ReadOptions {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]ReadOptions, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem ReadOptions
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
