// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// ReadOptions fields:
//
//	slot 0: type — scalar, size=4, align=4
//	slot 1: cacheResult — scalar, size=1, align=1
//	slot 2: debugID — union_like, size=4, align=4, indirection
//	slot 4: consistencyCheckStartVersion — union_like, size=4, align=4, indirection
//	slot 6: lockAware — scalar, size=1, align=1
const (
	ReadOptionsSlotType                         = 0
	ReadOptionsSlotCacheResult                  = 1
	ReadOptionsSlotDebugID                      = 2
	ReadOptionsSlotConsistencyCheckStartVersion = 4
	ReadOptionsSlotLockAware                    = 6
)

var ReadOptionsVTable = wire.VTable{18, 20, 4, 16, 17, 8, 18, 12, 19}

type ReadOptions struct {
	Type                            []byte // slot 0, ReadBytes
	CacheResult                     bool   // slot 1, ReadBool
	HasDebugID                      bool   // slot 2, Optional, presence flag
	DebugID                         []byte // slot 3, Optional, ReadBytes
	HasConsistencyCheckStartVersion bool   // slot 4, Optional, presence flag
	ConsistencyCheckStartVersion    []byte // slot 5, Optional, ReadBytes
	LockAware                       bool   // slot 6, ReadBool
}

func (m *ReadOptions) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ReadOptionsSlotType) {
		m.Type = r.ReadBytes(ReadOptionsSlotType)
	}
	if r.FieldPresent(ReadOptionsSlotCacheResult) {
		m.CacheResult = r.ReadBool(ReadOptionsSlotCacheResult)
	}
	if r.FieldPresent(ReadOptionsSlotDebugID) && r.ReadUint8(ReadOptionsSlotDebugID) > 0 {
		m.DebugID = r.ReadBytes(ReadOptionsSlotDebugID + 1)
		m.HasDebugID = true
	}
	if r.FieldPresent(ReadOptionsSlotConsistencyCheckStartVersion) && r.ReadUint8(ReadOptionsSlotConsistencyCheckStartVersion) > 0 {
		m.ConsistencyCheckStartVersion = r.ReadBytes(ReadOptionsSlotConsistencyCheckStartVersion + 1)
		m.HasConsistencyCheckStartVersion = true
	}
	if r.FieldPresent(ReadOptionsSlotLockAware) {
		m.LockAware = r.ReadBool(ReadOptionsSlotLockAware)
	}
	return nil
}

func (m *ReadOptions) MarshalInto(obj *wire.ObjectWriter) {
	vt := ReadOptionsVTable
	obj.WriteBytes(int(vt[ReadOptionsSlotType+2]), m.Type)
	obj.WriteBool(int(vt[ReadOptionsSlotCacheResult+2]), m.CacheResult)
	obj.WriteBool(int(vt[ReadOptionsSlotLockAware+2]), m.LockAware)
}
