// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// ReplyPromise fields:
//
//	slot 0: field_0 — scalar, size=16, align=8
const (
	ReplyPromiseSlotField_0 = 0
)

var ReplyPromiseVTable = wire.VTable{6, 20, 4}

const ReplyPromiseFileID uint32 = 18156145

var ReplyPromiseVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
}

type ReplyPromise struct {
	Field_0 []byte // slot 0, ReadBytes
}

var ReplyPromiseTemplate = wire.NewMessageTemplate(
	ReplyPromiseFileID, ReplyPromiseVTable, 8, ReplyPromiseVTableClosure,
)
