// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

// SpanContext fields:
//
//	slot 0: traceID — scalar, size=16, align=8
//	slot 1: spanID — scalar, size=8, align=8
//	slot 2: m_Flags — scalar, size=1, align=1
const (
	SpanContextSlotTraceID = 0
	SpanContextSlotSpanID  = 1
	SpanContextSlotFlags   = 2
)

var SpanContextVTable = wire.VTable{10, 29, 4, 20, 28}

type SpanContext struct {
	TraceID []byte // slot 0, ReadBytes
	SpanID  uint64 // slot 1, ReadUint64
	Flags   []byte // slot 2, ReadBytes
}
