// Code generated by fdb-schema-extract from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	SpanContextSlotTraceID = 0
	SpanContextSlotSpanID  = 1
	SpanContextSlotFlags   = 2
)

var SpanContextVTable = wire.VTable{10, 29, 4, 20, 28}

type SpanContext struct {
	TraceID [16]byte // slot 0
	SpanID  uint64   // slot 1
	Flags   uint8    // slot 2
}

func (m *SpanContext) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(SpanContextSlotTraceID) {
		m.TraceID = r.ReadUID(SpanContextSlotTraceID)
	}
	if r.FieldPresent(SpanContextSlotSpanID) {
		m.SpanID = r.ReadUint64(SpanContextSlotSpanID)
	}
	if r.FieldPresent(SpanContextSlotFlags) {
		m.Flags = r.ReadUint8(SpanContextSlotFlags)
	}
}

func (m *SpanContext) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(SpanContextSlotTraceID) {
		m.TraceID = r.ReadUID(SpanContextSlotTraceID)
	}
	if r.FieldPresent(SpanContextSlotSpanID) {
		m.SpanID = r.ReadUint64(SpanContextSlotSpanID)
	}
	if r.FieldPresent(SpanContextSlotFlags) {
		m.Flags = r.ReadUint8(SpanContextSlotFlags)
	}
	return nil
}

func (m *SpanContext) MarshalInto(obj *wire.ObjectWriter) {
	vt := SpanContextVTable
	obj.WriteUID(int(vt[SpanContextSlotTraceID+2]), m.TraceID)
	obj.WriteUint64(int(vt[SpanContextSlotSpanID+2]), m.SpanID)
	obj.WriteUint8(int(vt[SpanContextSlotFlags+2]), m.Flags)
}

func WriteSpanContext(obj *wire.ObjectWriter, parentOffset int, traceID [16]byte, spanID uint64, flags uint8) {
	m := SpanContext{TraceID: traceID, SpanID: spanID, Flags: flags}
	obj.WriteStruct(parentOffset, SpanContextVTable, 8, m.MarshalInto)
}

func MarshalSpanContext(traceID [16]byte, spanID uint64, flags uint8) []byte {
	m := SpanContext{TraceID: traceID, SpanID: spanID, Flags: flags}
	return wire.MarshalStructBlob(SpanContextVTable, m.MarshalInto)
}

// ParseSpanContextVectorFromReader reads a FlatBuffers vector of SpanContext.
func ParseSpanContextVectorFromReader(r *wire.Reader, slot int) []SpanContext {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]SpanContext, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem SpanContext
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
