// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	SplitRangeRequestSlotKeys       = 0
	SplitRangeRequestSlotChunkSize  = 1
	SplitRangeRequestSlotReply      = 2
	SplitRangeRequestSlotTenantInfo = 3
	SplitRangeRequestSlotField_4    = 4
)

var SplitRangeRequestVTable = wire.VTable{12, 24, 12, 4, 16, 20}

const SplitRangeRequestFileID uint32 = 10725174

var SplitRangeRequestVTableClosure = []wire.VTable{
	{6, 20, 4},
	{10, 17, 4, 16, 12},
	{6, 8, 4},
	{12, 24, 12, 4, 16, 20},
	{8, 12, 4, 8},
}

var SplitRangeRequestTemplate = wire.NewMessageTemplate(
	SplitRangeRequestFileID, SplitRangeRequestVTable, 8, SplitRangeRequestVTableClosure,
)

const SplitRangeRequestMaxAlign = 8

type SplitRangeRequest struct {
	Keys       KeyRangeRef  // slot 0, nested
	ChunkSize  int64        // slot 1
	Reply      ReplyPromise // slot 2, nested
	TenantInfo TenantInfo   // slot 3, nested
	Field_4    []byte       // slot 4
}

func (m *SplitRangeRequest) UnmarshalFromReader(r *wire.Reader) {
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotKeys); err == nil {
		m.Keys.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(SplitRangeRequestSlotChunkSize) {
		m.ChunkSize = r.ReadInt64(SplitRangeRequestSlotChunkSize)
	}
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(SplitRangeRequestSlotField_4) {
		m.Field_4 = r.ReadBytes(SplitRangeRequestSlotField_4)
	}
}

func (m *SplitRangeRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotKeys); err == nil {
		m.Keys.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(SplitRangeRequestSlotChunkSize) {
		m.ChunkSize = r.ReadInt64(SplitRangeRequestSlotChunkSize)
	}
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotReply); err == nil {
		m.Reply.UnmarshalFromReader(nr)
	}
	if nr, err := r.ReadNestedReader(SplitRangeRequestSlotTenantInfo); err == nil {
		m.TenantInfo.UnmarshalFromReader(nr)
	}
	if r.FieldPresent(SplitRangeRequestSlotField_4) {
		m.Field_4 = r.ReadBytes(SplitRangeRequestSlotField_4)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *SplitRangeRequest) precomputeSize(ps *wire.PrecomputeSize) int {
	m.Keys.precomputeSize(ps)
	m.Reply.precomputeSize(ps)
	m.TenantInfo.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(int(SplitRangeRequestVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(SplitRangeRequestVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *SplitRangeRequest) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var keysStart int
	var replyStart int
	var tenantInfoStart int
	keysStart = m.Keys.writeToBuffer(wb, vtableStart, tmpl)
	replyStart = m.Reply.writeToBuffer(wb, vtableStart, tmpl)
	tenantInfoStart = m.TenantInfo.writeToBuffer(wb, vtableStart, tmpl)
	selfW := wb.GetMessageWriter(int(SplitRangeRequestVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := SplitRangeRequestVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(SplitRangeRequestVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.ChunkSize))
		selfW.WriteScalar(b[:], int(vt[SplitRangeRequestSlotChunkSize+2]))
	}
	selfW.WriteRelativeOffset(keysStart, int(vt[SplitRangeRequestSlotKeys+2]))
	selfW.WriteRelativeOffset(replyStart, int(vt[SplitRangeRequestSlotReply+2]))
	selfW.WriteRelativeOffset(tenantInfoStart, int(vt[SplitRangeRequestSlotTenantInfo+2]))
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *SplitRangeRequest) MarshalFDB() []byte {
	t := SplitRangeRequestTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], SplitRangeRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *SplitRangeRequest) MarshalFDBPooled(dst []byte) []byte {
	t := SplitRangeRequestTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], SplitRangeRequestFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseSplitRangeRequestVectorFromReader reads a FlatBuffers vector of SplitRangeRequest.
func ParseSplitRangeRequestVectorFromReader(r *wire.Reader, slot int) []SplitRangeRequest {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]SplitRangeRequest, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem SplitRangeRequest
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
