// Code generated by fdb-schema-extract v5 from FDB 7.3.77. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"fdb.dev/pkg/fdbgo/wire"
)

const (
	TenantMapEntrySlotId                       = 0
	TenantMapEntrySlotTenantName               = 1
	TenantMapEntrySlotTenantLockState          = 2
	TenantMapEntrySlotTenantLockId             = 3
	TenantMapEntrySlotTenantGroup              = 5
	TenantMapEntrySlotConfigurationSequenceNum = 7
)

var TenantMapEntryVTable = wire.VTable{20, 35, 4, 20, 32, 33, 24, 34, 28, 12}

const TenantMapEntryFileID uint32 = 7054389

var TenantMapEntryVTableClosure = []wire.VTable{
	{20, 35, 4, 20, 32, 33, 24, 34, 28, 12},
	{6, 8, 4},
}

var TenantMapEntryTemplate = wire.NewMessageTemplate(
	TenantMapEntryFileID, TenantMapEntryVTable, 8, TenantMapEntryVTableClosure,
)

const TenantMapEntryMaxAlign = 8

type TenantMapEntry struct {
	Id                       int64    // slot 0
	TenantName               []byte   // slot 1
	TenantLockState          uint8    // slot 2
	HasTenantLockId          bool     // slot 3, optional tag
	TenantLockId             [16]byte // slot 4, optional scalar value
	HasTenantGroup           bool     // slot 5, optional tag
	TenantGroup              []byte   // slot 6, optional value
	ConfigurationSequenceNum int64    // slot 7
}

func (m *TenantMapEntry) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(TenantMapEntrySlotId) {
		m.Id = r.ReadInt64(TenantMapEntrySlotId)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantName) {
		m.TenantName = r.ReadBytes(TenantMapEntrySlotTenantName)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantLockState) {
		m.TenantLockState = r.ReadUint8(TenantMapEntrySlotTenantLockState)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantLockId) && r.ReadUint8(TenantMapEntrySlotTenantLockId) > 0 {
		copy(m.TenantLockId[:], r.ReadRelOffRaw(TenantMapEntrySlotTenantLockId+1, 16))
		m.HasTenantLockId = true
	}
	if r.FieldPresent(TenantMapEntrySlotTenantGroup) && r.ReadUint8(TenantMapEntrySlotTenantGroup) > 0 {
		m.TenantGroup = r.ReadBytes(TenantMapEntrySlotTenantGroup + 1)
		m.HasTenantGroup = true
	}
	if r.FieldPresent(TenantMapEntrySlotConfigurationSequenceNum) {
		m.ConfigurationSequenceNum = r.ReadInt64(TenantMapEntrySlotConfigurationSequenceNum)
	}
}

func (m *TenantMapEntry) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(TenantMapEntrySlotId) {
		m.Id = r.ReadInt64(TenantMapEntrySlotId)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantName) {
		m.TenantName = r.ReadBytes(TenantMapEntrySlotTenantName)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantLockState) {
		m.TenantLockState = r.ReadUint8(TenantMapEntrySlotTenantLockState)
	}
	if r.FieldPresent(TenantMapEntrySlotTenantLockId) && r.ReadUint8(TenantMapEntrySlotTenantLockId) > 0 {
		copy(m.TenantLockId[:], r.ReadRelOffRaw(TenantMapEntrySlotTenantLockId+1, 16))
		m.HasTenantLockId = true
	}
	if r.FieldPresent(TenantMapEntrySlotTenantGroup) && r.ReadUint8(TenantMapEntrySlotTenantGroup) > 0 {
		m.TenantGroup = r.ReadBytes(TenantMapEntrySlotTenantGroup + 1)
		m.HasTenantGroup = true
	}
	if r.FieldPresent(TenantMapEntrySlotConfigurationSequenceNum) {
		m.ConfigurationSequenceNum = r.ReadInt64(TenantMapEntrySlotConfigurationSequenceNum)
	}
	return nil
}

// precomputeSize — C++ SaveVisitorLambda::operator() with PrecomputeSize writer.
// Fields processed in SERIALIZE ORDER (same as C++ for_each over members).
// Returns end-offset of this object (C++ RelativeOffset).
func (m *TenantMapEntry) precomputeSize(ps *wire.PrecomputeSize) int {
	ps.VisitDynamicSize(len(m.TenantName))
	if m.HasTenantLockId {
		ps.Write(ps.CurrentBufferSize + 16)
	}
	if m.HasTenantGroup {
		ps.VisitDynamicSize(len(m.TenantGroup))
	}
	{
		n := ps.GetMessageWriter(int(TenantMapEntryVTable[1]))
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+int(TenantMapEntryVTable[1])-4, 8)+4)
	}
	return ps.CurrentBufferSize
}

// writeToBuffer — C++ SaveVisitorLambda::operator() with WriteToBuffer writer.
// Fields in SERIALIZE ORDER (same as precomputeSize, same as C++ for_each).
// Returns selfStart (end-offset of this object) for parent's RelativeOffset.
func (m *TenantMapEntry) writeToBuffer(wb *wire.WriteToBuffer, vtableStart int, tmpl *wire.MessageTemplate) int {
	var tenantNameOff int
	var tenantLockIdOff int
	var tenantGroupOff int
	tenantNameOff, _ = wb.VisitDynamicSize(m.TenantName)
	if m.HasTenantLockId {
		wb.Write(m.TenantLockId[:], wb.CurrentBufferSize+16)
		tenantLockIdOff = wb.CurrentBufferSize
	}
	if m.HasTenantGroup {
		tenantGroupOff, _ = wb.VisitDynamicSize(m.TenantGroup)
	}
	selfW := wb.GetMessageWriter(int(TenantMapEntryVTable[1]), true)
	selfStart := selfW.FinalLocation
	vt := TenantMapEntryVTable
	{
		soff := int32(vtableStart - tmpl.VTableOffset(TenantMapEntryVTable) - selfStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		selfW.WriteScalar(b[:], 0)
	}
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.Id))
		selfW.WriteScalar(b[:], int(vt[TenantMapEntrySlotId+2]))
	}
	selfW.WriteScalar([]byte{byte(m.TenantLockState)}, int(vt[TenantMapEntrySlotTenantLockState+2]))
	{
		var b [8]byte
		binary.LittleEndian.PutUint64(b[:], uint64(m.ConfigurationSequenceNum))
		selfW.WriteScalar(b[:], int(vt[TenantMapEntrySlotConfigurationSequenceNum+2]))
	}
	selfW.WriteRelativeOffset(tenantNameOff, int(vt[TenantMapEntrySlotTenantName+2]))
	if m.HasTenantLockId {
		selfW.WriteScalar([]byte{1}, int(vt[TenantMapEntrySlotTenantLockId+2]))
		selfW.WriteRelativeOffset(tenantLockIdOff, int(vt[TenantMapEntrySlotTenantLockId+1+2]))
	}
	if m.HasTenantGroup {
		selfW.WriteScalar([]byte{1}, int(vt[TenantMapEntrySlotTenantGroup+2]))
		selfW.WriteRelativeOffset(tenantGroupOff, int(vt[TenantMapEntrySlotTenantGroup+1+2]))
	}
	selfW.WriteToAt(selfStart)
	return selfStart
}

func (m *TenantMapEntry) MarshalFDB() []byte {
	t := TenantMapEntryTemplate
	packedVT := t.PackedVTables()

	// Pass 1: PrecomputeSize
	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	// Pass 2: WriteToBuffer
	buf := make([]byte, totalSize)
	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	// FakeRoot object
	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], TenantMapEntryFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// MarshalFDBPooled is like MarshalFDB but reuses dst if capacity is sufficient.
func (m *TenantMapEntry) MarshalFDBPooled(dst []byte) []byte {
	t := TenantMapEntryTemplate
	packedVT := t.PackedVTables()

	ps := wire.NewPrecomputeSize()
	vtNoop := ps.GetMessageWriter(len(packedVT))
	m.precomputeSize(ps)
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+4, 4)+4)
	}
	vtNoop.WriteTo(ps)
	vtableStart := ps.CurrentBufferSize
	{
		n := ps.GetMessageWriter(8)
		n.WriteToAt(ps, wire.RightAlign(ps.CurrentBufferSize+8, 8))
	}
	totalSize := ps.CurrentBufferSize

	var buf []byte
	if cap(dst) >= totalSize {
		buf = dst[:totalSize]
		for i := range buf {
			buf[i] = 0
		}
	} else {
		buf = make([]byte, totalSize)
	}

	wb := wire.NewWriteToBuffer(buf, vtableStart, ps.WriteToOffsets)
	vtW := wb.GetMessageWriter(len(packedVT), false)
	vtW.WriteScalar(packedVT, 0)
	rootStart := m.writeToBuffer(wb, vtableStart, t)

	fakeRootW := wb.GetMessageWriter(8, true)
	fakeRootStart := fakeRootW.FinalLocation
	fakeRootW.WriteRelativeOffset(rootStart, int(wire.FakeRootVTable[2]))
	{
		soff := int32(vtableStart - t.VTableOffset(wire.FakeRootVTable) - fakeRootStart)
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], uint32(soff))
		fakeRootW.WriteScalar(b[:], 0)
	}
	fakeRootW.WriteToAt(fakeRootStart)

	vtW.WriteTo()
	footerW := wb.GetMessageWriter(8, false)
	footerW.WriteRelativeOffset(fakeRootStart, 0)
	{
		var b [4]byte
		binary.LittleEndian.PutUint32(b[:], TenantMapEntryFileID)
		footerW.WriteScalar(b[:], 4)
	}
	footerW.WriteToAt(wire.RightAlign(wb.CurrentBufferSize+8, 8))
	wire.ReleaseWriteToBuffer(wb)
	wire.ReleasePrecomputeSize(ps)
	return buf
}

// ParseTenantMapEntryVectorFromReader reads a FlatBuffers vector of TenantMapEntry.
func ParseTenantMapEntryVectorFromReader(r *wire.Reader, slot int) []TenantMapEntry {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]TenantMapEntry, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem TenantMapEntry
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
