package explaindiff

import (
	"strings"
	"testing"
)

// TestNormalizeAliasesIsStableAndInjective pins both halves of the
// alias-normalization contract. The corpus-wide determinism test proves only
// the first half — a normalizer that collapsed EVERY correlation to `q$0`
// would also be deterministic while destroying the aliasing structure that
// distinguishes two different subqueries from the same one used twice. That
// is the dimension this test covers.
//
// Regression origin: the planner's correlation ids come from a process-global
// counter, so the identical plan rendered `q$6381` on the first corpus pass
// and `q$407245` on the second within one process.
func TestNormalizeAliasesIsStableAndInjective(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "global counter erased",
			in:   "Project([(SCALAR_SUBQUERY q$407245)], Limit(1, Scan(SCORES)))",
			want: "Project([(SCALAR_SUBQUERY q$0)], Limit(1, Scan(SCORES)))",
		},
		{
			name: "distinct correlations stay distinct",
			in:   "Join(q$91, q$7, q$91)",
			want: "Join(q$0, q$1, q$0)",
		},
		{
			name: "prefix case preserved — q$ and Q$ come from different render paths",
			in:   "Filter(Q$12, q$99)",
			want: "Filter(Q$0, q$1)",
		},
		{
			name: "same id under different prefixes keeps one identity",
			in:   "Pair(Q$12, q$12)",
			want: "Pair(Q$0, q$0)",
		},
		{
			name: "plans without correlations are untouched",
			in:   "Fetch(IndexScan(IDX_A, [=]))",
			want: "Fetch(IndexScan(IDX_A, [=]))",
		},
	}
	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := normalizeAliases(tc.in)
			if got != tc.want {
				t.Fatalf("normalizeAliases(%q)\n got  %q\n want %q", tc.in, got, tc.want)
			}
			// Renumbering must be a fixpoint: normalizing an already
			// normalized plan cannot shift the ids again, or two baselines
			// generated by different code paths would never converge.
			if again := normalizeAliases(got); again != got {
				t.Fatalf("not idempotent: %q → %q", got, again)
			}
		})
	}
}

// TestIsDMLClassification pins the statement-class routing the collect loop
// depends on: DELETE/UPDATE go to the DML harness, SELECT/WITH/VALUES stay on
// the Query path, and INSERT (plus everything else) is a non-plannable
// sequencing step. A misclassification here silently drops a plannable DML
// stanza back into NonQuery — the exact DML-blindness this change closes.
func TestIsDMLClassification(t *testing.T) {
	t.Parallel()
	cases := map[string]bool{
		"DELETE FROM t WHERE id > 5":           true,
		"UPDATE t SET x = 1":                   true,
		"delete from t":                        true, // case-insensitive
		"  \n\tDELETE FROM t":                  true, // leading whitespace tolerated
		"SELECT * FROM t":                      false,
		"WITH x AS (SELECT 1) SELECT * FROM x": false,
		"VALUES (1)":                           false,
		"INSERT INTO t VALUES (1)":             false,
		"INSERT INTO t SELECT * FROM u":        false,
		"":                                     false,
	}
	for sql, want := range cases {
		if got := isDML(sql); got != want {
			t.Errorf("isDML(%q) = %v, want %v", sql, got, want)
		}
	}
}

// TestNormalizeErrIsSingleLineAndBounded pins the marker-line invariants the
// baseline format depends on: no newline (which would break Parse and split
// one query across two hunks), no raw pointer address (which would make a
// marker diff against itself), and no unescaped ">" (which could forge the
// end of a marker).
func TestNormalizeErrIsSingleLineAndBounded(t *testing.T) {
	t.Parallel()

	got := normalizeErr("boom at 0xc000123456:\n  caused by <thing> not found\n")
	// `<` is left alone — the marker opens with a literal `<PLAN-ERROR:` and
	// an inner `<` is unambiguous — but the CLOSING delimiter must not
	// survive raw.
	if want := "boom at 0xADDR: caused by <thing› not found"; got != want {
		t.Errorf("normalizeErr\n got  %q\n want %q", got, want)
	}
	if strings.ContainsAny(got, "\n\r") {
		t.Errorf("normalizeErr kept a line break: %q", got)
	}
	if strings.Contains(got, "0xc000123456") {
		t.Errorf("normalizeErr kept a pointer address: %q", got)
	}
	if strings.Contains(got, ">") {
		t.Errorf("normalizeErr left a raw '>', which can forge the marker's end: %q", got)
	}

	long := make([]byte, 5000)
	for i := range long {
		long[i] = 'x'
	}
	if n := len(normalizeErr(string(long))); n > 320 {
		t.Errorf("normalizeErr did not cap a 5000-byte message: got %d chars", n)
	}
}
