package query

// RFC-200 §7's two 3a pins: the dotted readers on the correlated-scalar channel
// analysed as NOT needing producer-first sequencing, with each negative pinned
// so the claim survives the person who measured it.
//
// THE QUESTION RFC-197 MAKES THESE ANSWER. Its producer-first ordering says a
// dotted-text READER may only be converted after the PRODUCER that packs a leg
// into a column name is gone — convert the reader first and it stops matching
// names its producer is still minting. RFC-200 gives the layout authority a
// NESTED window kind, which changes which rows carry a merged layout, so the
// standing question for every dotted reader is: does a positional-merge row now
// reach it? If one does, the reader's conversion has to be sequenced BEFORE the
// seed change rather than after.
//
// For these two the answer is no, and the reason is that their counterparty is a
// DIFFERENT PRODUCER: clusteredOuterOrdinalSeed, which mints `LEG.COL` names and
// asserts a FLAT ordinal join seed on its own output. A positional merge names
// its fields `_0`, `_1`, … (values.OrdinalFieldName — Java's
// Type.java:2922 isAutoGenerated spelling, from Column::unnamedOf), and those
// two namespaces cannot intersect: an auto-generated ordinal name contains no
// dot, so it can neither BE a minted key nor MATCH one.
//
// Analysis is what that paragraph is. These tests are what makes it checkable.

import (
	"strings"
	"testing"

	"fdb.dev/pkg/recordlayer/query/plan/cascades/values"
)

// mergeRowLegPullUp is a cluster pull-up whose leg carries a POSITIONAL MERGE
// row as its flowed type: the exact shape RFC-200 teaches the layout authority
// to accept, put through the producer path these two readers read the output of.
//
// The second leg is an ordinary named-column leg, because a pull-up with only
// the merge row would let a reader return false for the uninteresting reason
// that it had nothing to match at all.
func mergeRowLegPullUp(t testing.TB) (*clusterPullUp, *values.RecordConstructorValue) {
	t.Helper()
	mergeRow := &values.RecordType{Fields: []values.Field{
		{Name: values.OrdinalFieldName(0), FieldType: values.NotNullLong, Ordinal: 0},
		{Name: values.OrdinalFieldName(1), FieldType: values.NotNullLong, Ordinal: 1},
	}}
	mergeLeg := clusterLegSpan{binding: "M", start: 0, typ: mergeRow}
	plainLeg := clusterLegSpan{
		binding: "O",
		start:   2,
		typ:     &values.RecordType{Fields: []values.Field{{Name: "ID", Ordinal: 0, FieldType: values.NotNullLong}}},
	}

	// The merge RC itself, built exactly as positionalMergeCase builds it — one
	// unnamed column per collapsed lower quantifier, each holding that
	// quantifier's whole row.
	rc := values.NewRawRecordConstructorValue(
		values.RecordConstructorField{
			Name:  values.OrdinalFieldName(0),
			Value: exactTestQOV(t, "A", &values.RecordType{Fields: []values.Field{{Name: "ID", Ordinal: 0, FieldType: values.NotNullLong}}}),
		},
		values.RecordConstructorField{
			Name:  values.OrdinalFieldName(1),
			Value: exactTestQOV(t, "B", &values.RecordType{Fields: []values.Field{{Name: "QTY", Ordinal: 0, FieldType: values.NotNullLong}}}),
		},
	)
	return &clusterPullUp{
		outerCorr: values.NamedCorrelationIdentifier("outer"),
		legs:      []clusterLegSpan{mergeLeg, plainLeg},
		legByBinding: map[string]clusterLegSpan{
			"M": mergeLeg,
			"O": plainLeg,
		},
	}, rc
}

const mergeRowPinReArms = "a positional-merge row is now feeding this dotted reader; " +
	"RFC-197's producer-first ordering applies and the conversion must be sequenced " +
	"BEFORE the seed change, not after."

// RFC-200 §7 pin 1: clusterFieldResolvable's inner-scalar-key arm.
//
// Its counterparty is the inner scalar key clusteredOuterOrdinalSeed mints as
// `UPPER(innerAlias) + "." + scalarCol`. A positional merge's field names carry
// no dot at all, so no merge field can be that key.
func TestClusterFieldResolvable_APositionalMergeRowNamesNothing(t *testing.T) {
	t.Parallel()

	pu, rc := mergeRowLegPullUp(t)
	// The fixture really is the shape RFC-200 admits, or the negative below is a
	// negative about something else.
	if !values.IsPositionalMergeRC(rc) {
		t.Fatal("fixture: the merge row is not a positional merge — the pin would be " +
			"asserting a negative about a shape the layout authority never sees")
	}
	innerKey := "S.CV" // what clusteredOuterOrdinalSeed mints for the inner scalar

	for _, f := range rc.Fields {
		if clusterFieldResolvable(f.Name, pu, innerKey) {
			t.Errorf("clusterFieldResolvable(%q) resolved. %s", f.Name, mergeRowPinReArms)
		}
		if strings.Contains(f.Name, ".") {
			t.Errorf("a positional-merge field is named %q, which contains a dot — the "+
				"disjointness this pin rests on is that an auto-generated ordinal name "+
				"can neither BE a dotted key nor MATCH one. %s", f.Name, mergeRowPinReArms)
		}
	}

	// The POSITIVE CONTROL. Without it a reader that had stopped resolving
	// anything at all would satisfy the negatives above, and the pin would read
	// as "merge rows are excluded" when it actually meant "this reader is dead".
	if !clusterFieldResolvable(innerKey, pu, innerKey) {
		t.Fatal("the inner scalar key does not resolve — this reader is not answering " +
			"at all, so every negative above holds vacuously")
	}
	if !clusterFieldResolvable("O.ID", pu, innerKey) {
		t.Fatal("a plain leg column does not resolve — the leg arm is dead and every " +
			"negative above holds vacuously")
	}
}

// RFC-200 §7 pin 2: clusterSeedSlotByName's leg arm.
//
// Its counterparty is the leg column names clusteredOuterOrdinalSeed mints at
// the same walk. This pin is the sharper of the two, because the merge row is
// here as a LEG's own flowed type — so the producer WOULD mint names for it, and
// the question is whether those names can collide with the merged-row namespace
// a converted reader would key on.
//
// They cannot: the producer mints `M._0`, which is qualified by the leg binding
// and therefore lives in the same flat `LEG.COL` namespace as everything else it
// mints. What no merged-row reader ever produces is that spelling — a merged row
// is addressed by ORDINAL, and RFC-200 does not reintroduce a qualified mint.
func TestClusterSeedSlotByName_AMergeRowsOwnFieldNamesResolveToNothing(t *testing.T) {
	t.Parallel()

	pu, rc := mergeRowLegPullUp(t)

	for _, f := range rc.Fields {
		if slot, found := clusterSeedSlotByName(pu, f.Name); found {
			t.Errorf("clusterSeedSlotByName(%q) found slot %d. %s", f.Name, slot, mergeRowPinReArms)
		}
	}

	// What the producer DOES mint for a merge-row leg, and the fact that keeps
	// the two namespaces apart: it is qualified, so it is in the reader's flat
	// namespace and NOT in the merged row's ordinal one.
	qualified := "M." + values.OrdinalFieldName(0)
	slot, found := clusterSeedSlotByName(pu, qualified)
	if !found || slot != 0 {
		t.Fatalf("clusterSeedSlotByName(%q) = (%d, %t), want (0, true) — the producer "+
			"mints exactly this spelling for a merge-row leg, so a reader that cannot "+
			"find it has drifted from its own producer and the disjointness argument "+
			"below rests on nothing", qualified, slot, found)
	}
	// And the plain leg still resolves at its own offset, so the walk is live and
	// the merge leg did not swallow the row.
	if slot, found := clusterSeedSlotByName(pu, "O.ID"); !found || slot != 2 {
		t.Fatalf("clusterSeedSlotByName(\"O.ID\") = (%d, %t), want (2, true) — the merge "+
			"leg occupies slots 0 and 1, so a plain leg after it must start at 2. A "+
			"different answer means the reader is walking a different layout than the "+
			"one the producer builds.", slot, found)
	}
}
