load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rowstruct",
    srcs = [
        "ordinal.go",
        "rowstruct.go",
    ],
    importpath = "fdb.dev/pkg/relational/core/rowstruct",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fdbgo/fdb/tuple",
        "//pkg/recordlayer/query/plan/cascades/values",
        "//pkg/relational/api",
        "//pkg/relational/core/functions",
        "//pkg/relational/core/metadata",
        "@org_golang_google_protobuf//reflect/protoreflect",
    ],
)
