package plans

import "fdb.dev/pkg/recordlayer/query/plan/cascades/properties"

// Compile-time proof that every physical plan answers the cost and ordering
// questions the memo asks (RFC-183 P5). These assertions are the guard that
// keeps a newly added plan type from silently falling back to the cost model's
// pessimistic default arm — the failure mode is invisible at runtime because
// the default arm always returns *a* number.

var (
	_ properties.CostHinter = (*RecordQueryScanPlan)(nil)
	_ properties.CostHinter = (*RecordQueryIndexPlan)(nil)
	_ properties.CostHinter = (*RecordQueryVectorIndexPlan)(nil)
	_ properties.CostHinter = (*RecordQueryAggregateIndexPlan)(nil)
	_ properties.CostHinter = (*RecordQueryValuesPlan)(nil)
	_ properties.CostHinter = (*RecordQueryExplodePlan)(nil)
	_ properties.CostHinter = (*RecordQueryTempTableScanPlan)(nil)
	_ properties.CostHinter = (*RecordQueryTableFunctionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryFilterPlan)(nil)
	_ properties.CostHinter = (*RecordQueryPredicatesFilterPlan)(nil)
	_ properties.CostHinter = (*RecordQueryTypeFilterPlan)(nil)
	_ properties.CostHinter = (*RecordQueryFetchFromPartialRecordPlan)(nil)
	_ properties.CostHinter = (*RecordQueryFirstOrDefaultPlan)(nil)
	_ properties.CostHinter = (*RecordQueryInMemorySortPlan)(nil)
	_ properties.CostHinter = (*RecordQueryDistinctPlan)(nil)
	_ properties.CostHinter = (*RecordQueryMapPlan)(nil)
	_ properties.CostHinter = (*RecordQueryProjectionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryDefaultOnEmptyPlan)(nil)
	_ properties.CostHinter = (*RecordQueryTempTableInsertPlan)(nil)
	_ properties.CostHinter = (*RecordQueryLimitPlan)(nil)
	_ properties.CostHinter = (*RecordQueryStreamingAggregationPlan)(nil)
	_ properties.CostHinter = (*RecordQueryInsertPlan)(nil)
	_ properties.CostHinter = (*RecordQueryDeletePlan)(nil)
	_ properties.CostHinter = (*RecordQueryUpdatePlan)(nil)
	_ properties.CostHinter = (*RecordQueryUnionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryUnorderedUnionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryMergeSortUnionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryIntersectionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryMultiIntersectionOnValuesPlan)(nil)
	_ properties.CostHinter = (*RecordQueryFlatMapPlan)(nil)
	_ properties.CostHinter = (*RecordQueryNestedLoopJoinPlan)(nil)
	_ properties.CostHinter = (*RecordQueryInJoinPlan)(nil)
	_ properties.CostHinter = (*RecordQueryInUnionPlan)(nil)
	_ properties.CostHinter = (*RecordQueryRecursiveDfsJoinPlan)(nil)
	_ properties.CostHinter = (*RecordQueryRecursiveLevelUnionPlan)(nil)
)

var (
	_ properties.OrderingHinter = (*RecordQueryFilterPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryPredicatesFilterPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryTypeFilterPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryDistinctPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryProjectionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryMapPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryLimitPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryDefaultOnEmptyPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryFetchFromPartialRecordPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryScanPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryIndexPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryInMemorySortPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryMergeSortUnionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryInUnionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryMultiIntersectionOnValuesPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryStreamingAggregationPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryAggregateIndexPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryInJoinPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryUnorderedUnionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryVectorIndexPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryExplodePlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryFlatMapPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryNestedLoopJoinPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryRecursiveDfsJoinPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryRecursiveLevelUnionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryTableFunctionPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryTempTableInsertPlan)(nil)
	_ properties.OrderingHinter = (*RecordQueryTempTableScanPlan)(nil)
)
