load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "keyspace",
    srcs = [
        "domains.go",
        "keyspace.go",
    ],
    importpath = "fdb.dev/pkg/relational/core/keyspace",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/fdbgo/fdb/subspace",
        "//pkg/fdbgo/fdb/tuple",
        "//pkg/relational/api",
    ],
)

go_test(
    name = "keyspace_test",
    srcs = [
        "domains_test.go",
        "keyspace_test.go",
    ],
    embed = [":keyspace"],
    deps = [
        "//pkg/fdbgo/fdb/subspace",
        "//pkg/relational/api",
    ],
)
