#!/usr/bin/env bash
# Derive website/data/gomodules.yaml — the list of NESTED Go module roots that need a
# vanity-import stub page on fdb.dev.
#
# Why only nested module roots, and not one entry per package: `go get fdb.dev/a/b/c`
# queries `?go-get=1` for each prefix of the path, longest first, and stops at the first
# HTTP 200 carrying a matching go-import. The site serves that meta at `/`, so the single
# root tag resolves EVERY package in the root module — present and future — with no list
# to maintain. A nested module is the one case the walk cannot reach: it finds the
# `fdb.dev` root tag first and resolves the package against the root module, which does
# not contain it (a nested go.mod carves that subtree out of the parent). So a nested
# module root needs an HTTP 200 at its exact path to be discoverable at all.
#
# Run from anywhere. Regenerate locally with `just vanity-modules`; CI regenerates it
# during the site build (.github/workflows/website.yml), so a new nested module is picked
# up automatically and the committed copy can never go stale in production.
set -euo pipefail

cd "$(dirname "$0")/.."

out=website/data/gomodules.yaml

{
	printf -- '# GENERATED by scripts/gen-vanity-modules.sh — do not edit by hand.\n'
	printf -- '# Nested Go module roots under fdb.dev needing a vanity-import stub page.\n'
	printf -- '# The root module (fdb.dev) needs no entry: the go-import meta on / covers\n'
	printf -- "# every package in it via Go's prefix walk. See the script for the details.\n"
	printf -- 'modules:\n'
	# -not -path excludes: agent worktrees, the vendored Java reference checkout, the
	# vendored Hugo theme, and bazel's symlinked output trees. All are gitignored, so
	# they are absent in CI; the excludes keep a local run honest.
	find . -name go.mod \
		-not -path './.git/*' \
		-not -path './.claude/*' \
		-not -path './fdb-record-layer/*' \
		-not -path './website/themes/*' \
		-not -path './bazel-*' |
		sed 's|^\./||; s|/go\.mod$||' |
		grep -v '^go\.mod$' |
		LC_ALL=C sort |
		sed 's|^|  - |'
} >"$out"

echo "wrote $out:"
cat "$out"
