#!/usr/bin/env python3
"""Collect license/notice files for the release CLI's pure-Go dependency graph.

Run from the repository root after dependency or release-target changes.
Uses go list (metadata only); it does not build or test the CLI. Review the
result: this file-based inventory is not a substitute for a licensing audit.
"""

import json
import os
from pathlib import Path
import subprocess


TARGETS = ("linux/amd64", "linux/arm64", "darwin/amd64", "darwin/arm64")
OUTPUT = Path("THIRD_PARTY_NOTICES.txt")


def packages(target, env):
    goos, goarch = target.split("/")
    env = dict(env, CGO_ENABLED="0", GOOS=goos, GOARCH=goarch)
    text = subprocess.check_output(
        ["go", "list", "-mod=readonly", "-deps", "-json", "./cmd/frl"],
        env=env,
        text=True,
    )
    decoder = json.JSONDecoder()
    while text.strip():
        package, end = decoder.raw_decode(text.lstrip())
        yield package
        text = text.lstrip()[end:]


def legal_file(path):
    name = path.name.lower()
    return path.is_file() and any(
        name == prefix or name.startswith(prefix + ".") or name.startswith(prefix + "-")
        for prefix in ("license", "licence", "notice", "copying", "copyright")
    )


def main():
    # Match setup-go's go-version-file release toolchain, not a newer local Go
    # or ambient experiment/build flags that could change the imported graph.
    version = next(line.split()[1] for line in Path("go.mod").read_text().splitlines()
                   if line.startswith("go "))
    env = dict(os.environ, GOTOOLCHAIN="go" + version, GOEXPERIMENT="", GOFLAGS="")
    modules = {}
    standard_dirs = set()
    goroot = None
    for target in TARGETS:
        for package in packages(target, env):
            if package.get("Goroot"):
                goroot = Path(package["Root"])
                standard_dirs.add(Path(package["Dir"]))
            module = package.get("Module")
            if not module or module.get("Main"):
                continue
            if module.get("Replace"):
                raise RuntimeError("Review replacement module licensing: " + module["Path"])
            modules[(module["Path"], module["Version"])] = Path(module["Dir"])
    if not modules or goroot is None:
        raise RuntimeError("Empty dependency/toolchain inventory")

    sections = []

    def add(label, root, files):
        if not files:
            raise RuntimeError("No license/notice files found for " + label)
        for path in sorted(files):
            sections.append(
                "=" * 78 + "\n" + label + "\n" + str(path.relative_to(root))
                + "\n" + "=" * 78 + "\n\n" + path.read_text().rstrip() + "\n"
            )

    # Toolchain root license plus notices along imported standard-library and
    # vendored package paths; do not sweep unrelated compiler/test fixtures.
    standard_files = set()
    for directory in standard_dirs:
        while directory.is_relative_to(goroot):
            standard_files.update(p for p in directory.iterdir() if legal_file(p))
            if directory == goroot:
                break
            directory = directory.parent
    version = subprocess.check_output(["go", "env", "GOVERSION"], env=env, text=True).strip()
    add("Go toolchain " + version, goroot, standard_files)
    for (name, version), directory in sorted(modules.items()):
        # Preserve nested notices too, including separately licensed tables or
        # vendored material within a dependency module.
        add(name + " " + version, directory,
            {p for p in directory.rglob("*") if legal_file(p)})

    header = (
        "Third-party license and notice texts for the pure-Go frl CLI\n\n"
        "Generated by scripts/update-third-party-notices.py from go list -deps.\n"
        "Targets: " + ", ".join(TARGETS) + "; CGO_ENABLED=0.\n"
        "Includes license/notice files in dependency modules, which may cover\n"
        "additional files not linked into a particular binary. Source comments\n"
        "and nonstandard notice locations still require review. This inventory\n"
        "does not relicense third-party material or constitute legal clearance.\n"
        "For incorporated FoundationDB/Record Layer source, see NOTICE.\n\n"
    )
    OUTPUT.write_text(header + "\n".join(sections))
    print(f"Wrote {OUTPUT}: {len(modules)} modules, {len(sections)} license/notice files")


if __name__ == "__main__":
    main()
