package docscheck

import (
	"sort"
	"strings"
	"testing"
)

// The corpus reading in TestUnexportedFuncsAreReferenced exercises only the arms
// this repository happens to contain today. Every arm is driven here instead —
// including the vacuity guards — so an arm that is rare now cannot ship untested
// and then be read as a *finding* the first time it fires, which is the most
// expensive way to discover a bug in an instrument.

// scanned is a test helper: run the detector over synthetic sources and return
// the unreferenced names, sorted, plus the outcome for the callers that need it.
func scanned(t *testing.T, sources map[string]string) ([]string, scanOutcome) {
	t.Helper()
	out, err := scanPackageSources(sources)
	if err != nil {
		t.Fatalf("scanPackageSources: %v", err)
	}
	names := make([]string, 0, len(out.Unreferenced))
	for _, s := range out.Unreferenced {
		names = append(names, s.Name)
	}
	sort.Strings(names)
	return names, out
}

func TestUnreferencedFuncDetector_Candidacy(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name    string
		sources map[string]string
		// want is the set of unreferenced candidate names.
		want []string
		// wantCandidates, when non-negative, pins the population size — the
		// distinction between "considered and referenced" and "never considered".
		wantCandidates int
	}{
		{
			name: "an unexported no-receiver func with no reference is a violation",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\n",
			},
			want:           []string{"helper"},
			wantCandidates: 1,
		},
		{
			name: "an EXPORTED func with no reference is not even a candidate",
			sources: map[string]string{
				"p/a.go": "package p\nfunc Helper() int { return 1 }\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "a METHOD with no reference is not even a candidate",
			sources: map[string]string{
				"p/a.go": "package p\ntype T struct{}\nfunc (T) helper() int { return 1 }\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "init and main are never candidates — the runtime and the linker call them",
			sources: map[string]string{
				"p/a.go": "package main\nfunc init() {}\nfunc main() {}\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "a blank func declaration is not a candidate",
			sources: map[string]string{
				"p/a.go": "package p\nfunc _() {}\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "a func declared only in a _test.go file is not a candidate",
			sources: map[string]string{
				"p/a_test.go": "package p\nfunc onlyInTests() int { return 1 }\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "a func in a GENERATED file is not a candidate",
			sources: map[string]string{
				"p/a.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\nfunc helper() int { return 1 }\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
		{
			name: "a file excluded by a go:build ignore constraint contributes nothing",
			sources: map[string]string{
				"p/gen.go": "//go:build ignore\n\npackage main\nfunc helper() int { return 1 }\n",
			},
			want:           nil,
			wantCandidates: 0,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, out := scanned(t, tc.sources)
			if strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("unreferenced = %v, want %v", got, tc.want)
			}
			if out.Candidates != tc.wantCandidates {
				t.Errorf("Candidates = %d, want %d", out.Candidates, tc.wantCandidates)
			}
		})
	}
}

func TestUnreferencedFuncDetector_ReferenceCounting(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name    string
		sources map[string]string
		want    []string
	}{
		{
			name: "a call from a non-test file in the same package discharges it",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\nfunc Live() int { return helper() }\n",
			},
			want: nil,
		},
		{
			name: "a call from ANOTHER non-test file in the same package discharges it",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\n",
				"p/b.go": "package p\nfunc Live() int { return helper() }\n",
			},
			want: nil,
		},
		{
			name: "used as a VALUE, not called, still discharges it",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\nvar Live = helper\n",
			},
			want: nil,
		},
		{
			name: "passed as an argument discharges it",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\nfunc Live(f func() int) int { return f() }\nfunc Go() int { return Live(helper) }\n",
			},
			want: nil,
		},
		{
			name: "referenced from a GENERATED file still discharges it — generated code runs",
			sources: map[string]string{
				"p/a.go":    "package p\nfunc helper() int { return 1 }\n",
				"p/a.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\nfunc Live() int { return helper() }\n",
			},
			want: nil,
		},
		{
			name: "referenced only from a _test.go file is the DEAD TWIN shape and still a violation",
			sources: map[string]string{
				"p/a.go":      "package p\nfunc helper() int { return 1 }\n",
				"p/a_test.go": "package p\nimport \"testing\"\nfunc TestX(t *testing.T) { _ = helper() }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "DIRECT RECURSION does not discharge it — a func that only calls itself is dead",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper(n int) int { if n == 0 { return 0 }; return helper(n - 1) }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a reference from a DIFFERENT candidate's body does discharge it, even if that one is itself dead",
			sources: map[string]string{
				"p/a.go": "package p\nfunc leaf() int { return 1 }\nfunc caller() int { return leaf() }\n",
			},
			// Known limit, pinned so it is a documented property and not a
			// surprise: the walk is one level deep, so a dead CALLER keeps its
			// callee alive. Only `caller` surfaces; deleting it re-arms `leaf`
			// on the next run, which is the intended ratchet behaviour.
			want: []string{"caller"},
		},
		{
			name: "MUTUAL recursion hides both — the documented limit of a one-level walk",
			sources: map[string]string{
				"p/a.go": "package p\nfunc ping(n int) int { return pong(n) }\nfunc pong(n int) int { if n == 0 { return 0 }; return ping(n - 1) }\n",
			},
			want: nil,
		},
		{
			name: "a same-named SELECTOR is not a reference",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\ntype T struct{ helper int }\nfunc Live(t T) int { return t.helper }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a same-named method call is not a reference",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\ntype T struct{}\nfunc (T) helper() int { return 2 }\nfunc Live(t T) int { return t.helper() }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a mention in a COMMENT is not a reference — this is where grep gets it wrong",
			sources: map[string]string{
				"p/a.go": "package p\n// Live used to call helper, and no longer does.\nfunc helper() int { return 1 }\nfunc Live() int { return 2 }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a same-named STRING literal is not a reference",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper() int { return 1 }\nfunc Live() string { return \"helper\" }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a build-constrained file still supplies references",
			sources: map[string]string{
				"p/a.go":       "package p\nfunc helper() int { return 1 }\n",
				"p/a_linux.go": "//go:build linux\n\npackage p\nfunc Live() int { return helper() }\n",
			},
			want: nil,
		},
		{
			name: "a build-constrained file is itself scanned for candidates",
			sources: map[string]string{
				"p/a_linux.go": "//go:build linux\n\npackage p\nfunc helper() int { return 1 }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "a composite-literal KEY discharges it — the deliberate under-report",
			sources: map[string]string{
				// `helper` here is a struct FIELD name, not the func. Telling
				// the two apart needs type information, so the detector counts
				// it and stays quiet. Pinned so the direction is deliberate.
				"p/a.go": "package p\nfunc helper() int { return 1 }\ntype T struct{ helper int }\nvar Live = T{helper: 1}\n",
			},
			want: nil,
		},
		{
			name: "a func used only in its own signature's type is still dead",
			sources: map[string]string{
				"p/a.go": "package p\nfunc helper(f func() int) int { return f() }\n",
			},
			want: []string{"helper"},
		},
		{
			name: "several dead funcs are all reported",
			sources: map[string]string{
				"p/a.go": "package p\nfunc one() int { return 1 }\nfunc two() int { return 2 }\nfunc Live() int { return 3 }\n",
			},
			want: []string{"one", "two"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, _ := scanned(t, tc.sources)
			if strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("unreferenced = %v, want %v", got, tc.want)
			}
		})
	}
}

// The prod=0/test=0 versus prod=0/test>0 split is what separates unambiguous
// dead code from the dead-twin shape, and the whole ledger is organised around
// it, so the counter is pinned rather than trusted.
func TestUnreferencedFuncDetector_TestRefCount(t *testing.T) {
	t.Parallel()

	_, out := scanned(t, map[string]string{
		"p/a.go": "package p\nfunc twin() int { return 1 }\nfunc orphan() int { return 2 }\n",
		"p/a_test.go": "package p\nimport \"testing\"\n" +
			"func TestA(t *testing.T) { _ = twin() }\n" +
			"func TestB(t *testing.T) { _ = twin(); _ = twin() }\n",
	})

	if got := out.TestRefs["p/a.go # twin"]; got != 3 {
		t.Errorf("TestRefs for twin = %d, want 3 (the dead-twin shape: production never calls it, tests do)", got)
	}
	if got := out.TestRefs["p/a.go # orphan"]; got != 0 {
		t.Errorf("TestRefs for orphan = %d, want 0 (dead everywhere, not a twin)", got)
	}
}

// The ledger key must not carry a line number: a key that drifts on any edit
// above the function trains readers to re-stamp the ledger instead of reading
// it, which is the opposite of a ratchet.
func TestUnreferencedFuncSiteKeyIsLineIndependent(t *testing.T) {
	t.Parallel()
	a := funcSite{Path: "pkg/x/y.go", Name: "helper", Line: 10}
	b := funcSite{Path: "pkg/x/y.go", Name: "helper", Line: 4000}
	if a.key() != b.key() {
		t.Fatalf("key() must not depend on the line: %q != %q", a.key(), b.key())
	}
	if want := "pkg/x/y.go # helper"; a.key() != want {
		t.Fatalf("key() = %q, want %q", a.key(), want)
	}
}

// buildIgnored decides whether a file is package code at all, so a regression in
// it either silently drops a whole file's references (loud, but for the wrong
// reason) or silently drops candidates (quiet, and the gate goes blind).
func TestBuildIgnoredConstraint(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"go:build ignore", "//go:build ignore\n\npackage main\n", true},
		{"legacy +build ignore", "// +build ignore\n\npackage main\n", true},
		{"go:build ignore in a disjunction", "//go:build ignore || tools\n\npackage main\n", true},
		{"no constraint", "package p\n", false},
		{"a GOOS constraint is not an exclusion", "//go:build linux\n\npackage p\n", false},
		{"a negated tag is not an exclusion", "//go:build !race\n\npackage p\n", false},
		{"cgo constraint is not an exclusion", "//go:build cgo\n\npackage p\n", false},
		{"the word ignore inside another tag does not match", "//go:build ignoreme\n\npackage p\n", false},
		{"the word ignore in an ordinary comment does not match", "// this file used to ignore windows\npackage p\n", false},
		{"a go:build line AFTER the package clause is not a constraint", "package p\n\nfunc f() {\n\t//go:build ignore\n}\n", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			out, err := scanPackageSources(map[string]string{"p/a.go": tc.src + "\nfunc helper() int { return 1 }\n"})
			if err != nil {
				t.Fatalf("scan: %v", err)
			}
			// An ignored file contributes no candidates at all.
			if got := out.Candidates == 0; got != tc.want {
				t.Errorf("buildIgnored = %v, want %v (Candidates = %d)", got, tc.want, out.Candidates)
			}
		})
	}
}
