load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "logical",
    srcs = [
        "inline_values.go",
        "operator.go",
        "operators.go",
    ],
    importpath = "fdb.dev/pkg/relational/core/query/logical",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/recordlayer/query/plan/cascades/predicates",
        "//pkg/recordlayer/query/plan/cascades/values",
    ],
)

go_test(
    name = "logical_test",
    srcs = [
        "inline_values_test.go",
        "operators_test.go",
    ],
    embed = [":logical"],
    deps = ["//pkg/recordlayer/query/plan/cascades/values"],
)
