package factory

import (
	"fdb.dev/pkg/relational/conformance/rowdiff"
)

// NestedGeneratorVersion identifies the NESTED candidate-derivation rules.
//
// It is a second version string rather than a bump of GeneratorVersion because
// the two case families are derived by different entry points over disjoint
// candidate namespaces: a change to the nested rules must not declare the
// hundreds of committed FLAT scenarios unreproducible, and vice versa. Every
// consumer that dispatches on a committed header's generator therefore reads
// this constant, never a substring of it.
const NestedGeneratorVersion = "rowdiff-nested/1"

// NestedCandidates enumerates a seed's TLP-eligible NESTED candidates: the same
// derivation as Candidates, over a case whose table carries a struct column.
//
// Eligibility is the SAME predicate, deliberately. A nested query is not a
// different oracle problem — the ternary-logic partition is a property of the
// WHERE, and a WHERE over `n.a` partitions exactly as one over `a` does — so
// giving the nested family its own eligibility rules would be inventing a
// second, less-tested oracle for no reason.
func NestedCandidates(seed uint64) []Candidate {
	c := rowdiff.GenerateNested(seed)
	if len(c.Rows) > FactoryRowCap {
		c.Rows = c.Rows[:FactoryRowCap]
	}
	var out []Candidate
	for qi, q := range c.Queries {
		if !tlpEligible(q) {
			continue
		}
		for pi, proj := range c.ProjectionsFor(q) {
			out = append(out, Candidate{
				Seed:          seed,
				QueryIndex:    qi,
				ProjIndex:     pi,
				Case:          c,
				Query:         q,
				Projection:    proj,
				Nested:        true,
				FeatureVector: FeatureVector(c, q, proj),
			})
		}
	}
	return out
}

// CandidatesForGenerator derives a seed's candidates under the generator a
// committed header names.
//
// The determinism gate reads it. Dispatching there on the header's declared
// generator is what keeps the gate honest across two families: matching on the
// build's single GeneratorVersion would make every nested scenario report
// "generator drifted" — a red that says nothing about reproducibility — while
// ignoring the field would check a nested file against a flat candidate and
// report a drift that is really a lookup error. Unknown generator returns
// ok=false so a header naming a generator this build does not have FAILS rather
// than being silently regenerated by the wrong one.
func CandidatesForGenerator(generator string, seed uint64) (cands []Candidate, ok bool) {
	switch generator {
	case GeneratorVersion:
		return Candidates(seed), true
	case NestedGeneratorVersion:
		return NestedCandidates(seed), true
	}
	return nil, false
}
