// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	ErrorSlotErrorCode = 0
)

var ErrorVTable = wire.VTable{6, 6, 4}

const ErrorFileID uint32 = 14065384

var ErrorVTableClosure = []wire.VTable{
	{6, 8, 4},
	{6, 6, 4},
}
var ErrorTemplate = wire.NewMessageTemplate(
	ErrorFileID, ErrorVTable, 4, ErrorVTableClosure,
)

const ErrorMaxAlign = 4

type Error struct {
	ErrorCode uint16 // slot 0
}

func (m *Error) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
}

func (m *Error) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ErrorSlotErrorCode) {
		m.ErrorCode = r.ReadUint16(ErrorSlotErrorCode)
	}
	return nil
}

func (m *Error) blobSize() int {
	vt := ErrorVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	return (oolPos + oolSize + 3) &^ 3
}

func (m *Error) writeBlob(buf []byte, pos int) int {
	vt := ErrorVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	binary.LittleEndian.PutUint16(obj[int(vt[ErrorSlotErrorCode+2]):], m.ErrorCode)
	return curOOL - pos
}

func (m *Error) measureEndOff(endOff int) int {
	endOff = wire.MeasureObject(endOff, ErrorVTable, ErrorMaxAlign)
	return endOff
}

func (m *Error) writeDirect(dw *wire.DirectWriter) int {
	objPos, obj := dw.WriteObject(ErrorVTable, ErrorMaxAlign)
	vt := ErrorVTable
	binary.LittleEndian.PutUint16(obj[int(vt[ErrorSlotErrorCode+2]):], m.ErrorCode)
	return objPos
}

func (m *Error) MarshalFDB() []byte {
	t := ErrorTemplate
	endOff := 0
	bodySize := int(ErrorVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 4 - 1) &^ (4 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseErrorVectorFromReader reads a FlatBuffers vector of Error.
func ParseErrorVectorFromReader(r *wire.Reader, slot int) []Error {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]Error, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem Error
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
