// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import (
	"encoding/binary"

	"github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"
)

const (
	KeySelectorRefSlotKey     = 0
	KeySelectorRefSlotOrEqual = 1
	KeySelectorRefSlotOffset  = 2
)

var KeySelectorRefVTable = wire.VTable{10, 13, 4, 12, 8}

const KeySelectorRefMaxAlign = 4

type KeySelectorRef struct {
	Key     []byte // slot 0
	OrEqual bool   // slot 1
	Offset  int32  // slot 2
}

func (m *KeySelectorRef) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(KeySelectorRefSlotKey) {
		m.Key = r.ReadBytes(KeySelectorRefSlotKey)
	}
	if r.FieldPresent(KeySelectorRefSlotOrEqual) {
		m.OrEqual = r.ReadBool(KeySelectorRefSlotOrEqual)
	}
	if r.FieldPresent(KeySelectorRefSlotOffset) {
		m.Offset = r.ReadInt32(KeySelectorRefSlotOffset)
	}
}

func (m *KeySelectorRef) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(KeySelectorRefSlotKey) {
		m.Key = r.ReadBytes(KeySelectorRefSlotKey)
	}
	if r.FieldPresent(KeySelectorRefSlotOrEqual) {
		m.OrEqual = r.ReadBool(KeySelectorRefSlotOrEqual)
	}
	if r.FieldPresent(KeySelectorRefSlotOffset) {
		m.Offset = r.ReadInt32(KeySelectorRefSlotOffset)
	}
	return nil
}

func (m *KeySelectorRef) blobSize() int {
	vt := KeySelectorRefVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	if m.Key != nil {
		oolSize += (4 + len(m.Key) + 3) &^ 3
	}
	return (oolPos + oolSize + 3) &^ 3
}

func (m *KeySelectorRef) writeBlob(buf []byte, pos int) int {
	vt := KeySelectorRefVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	if m.OrEqual {
		obj[int(vt[KeySelectorRefSlotOrEqual+2])] = 1
	}
	binary.LittleEndian.PutUint32(obj[int(vt[KeySelectorRefSlotOffset+2]):], uint32(m.Offset))
	if m.Key != nil {
		binary.LittleEndian.PutUint32(buf[curOOL:], uint32(len(m.Key)))
		copy(buf[curOOL+4:], m.Key)
		wire.PatchBlobRelOff(obj, int(vt[KeySelectorRefSlotKey+2]), objPos, curOOL)
		curOOL += (4 + len(m.Key) + 3) &^ 3
	}
	return curOOL - pos
}

func (m *KeySelectorRef) measureEndOff(endOff int) int {
	endOff = wire.MeasureBytesOOL(endOff, m.Key)
	endOff = wire.MeasureObject(endOff, KeySelectorRefVTable, KeySelectorRefMaxAlign)
	return endOff
}

func (m *KeySelectorRef) writeDirect(dw *wire.DirectWriter) int {
	var keyOOL int
	if m.Key != nil {
		keyOOL = dw.WriteBytesOOL(m.Key)
	}
	objPos, obj := dw.WriteObject(KeySelectorRefVTable, KeySelectorRefMaxAlign)
	vt := KeySelectorRefVTable
	if m.OrEqual {
		obj[int(vt[KeySelectorRefSlotOrEqual+2])] = 1
	}
	binary.LittleEndian.PutUint32(obj[int(vt[KeySelectorRefSlotOffset+2]):], uint32(m.Offset))
	if m.Key != nil {
		wire.PatchRelOff(obj, int(vt[KeySelectorRefSlotKey+2]), objPos, keyOOL)
	}
	return objPos
}

// ParseKeySelectorRefVectorFromReader reads a FlatBuffers vector of KeySelectorRef.
func ParseKeySelectorRefVectorFromReader(r *wire.Reader, slot int) []KeySelectorRef {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]KeySelectorRef, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem KeySelectorRef
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
