// Code generated by fdb-schema-extract v5 from FDB 7.3.75. DO NOT EDIT.

package types

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const (
	ReplyPromiseSlotToken = 0
)

var ReplyPromiseVTable = wire.VTable{6, 20, 4}

const ReplyPromiseFileID uint32 = 18156145

var ReplyPromiseVTableClosure = []wire.VTable{
	{6, 20, 4},
	{6, 8, 4},
}

var ReplyPromiseTemplate = wire.NewMessageTemplate(
	ReplyPromiseFileID, ReplyPromiseVTable, 8, ReplyPromiseVTableClosure,
)

const ReplyPromiseMaxAlign = 8

type ReplyPromise struct {
	Token [16]byte // slot 0
}

func (m *ReplyPromise) UnmarshalFromReader(r *wire.Reader) {
	if r.FieldPresent(ReplyPromiseSlotToken) {
		m.Token = r.ReadUID(ReplyPromiseSlotToken)
	}
}

func (m *ReplyPromise) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(ReplyPromiseSlotToken) {
		m.Token = r.ReadUID(ReplyPromiseSlotToken)
	}
	return nil
}

func (m *ReplyPromise) blobSize() int {
	vt := ReplyPromiseVTable
	vtBytes := len(vt) * 2
	objPos := (vtBytes + 3) &^ 3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	oolSize := 0
	return (oolPos + oolSize + 3) &^ 3
}

func (m *ReplyPromise) writeBlob(buf []byte, pos int) int {
	vt := ReplyPromiseVTable
	obj := wire.WriteBlobVTable(buf, pos, vt)
	vtBytes := len(vt) * 2
	objPos := pos + (vtBytes+3)&^3
	oolPos := (objPos + int(vt[1]) + 3) &^ 3
	curOOL := oolPos
	copy(obj[int(vt[ReplyPromiseSlotToken+2]):], m.Token[:])
	return curOOL - pos
}

func (m *ReplyPromise) measureEndOff(endOff int) int {
	endOff = wire.MeasureObject(endOff, ReplyPromiseVTable, ReplyPromiseMaxAlign)
	return endOff
}

func (m *ReplyPromise) writeDirect(dw *wire.DirectWriter) int {
	objPos, obj := dw.WriteObject(ReplyPromiseVTable, ReplyPromiseMaxAlign)
	vt := ReplyPromiseVTable
	copy(obj[int(vt[ReplyPromiseSlotToken+2]):], m.Token[:])
	return objPos
}

func (m *ReplyPromise) MarshalFDB() []byte {
	t := ReplyPromiseTemplate
	endOff := 0
	bodySize := int(ReplyPromiseVTable[1]) - 4
	msgObjEnd := ((endOff + bodySize + 8 - 1) &^ (8 - 1)) + 4
	fakeRootEnd := ((msgObjEnd + 4 + 3) &^ 3) + 4
	vtableSize := t.PackedVTablesLen()
	vtableEnd := fakeRootEnd + vtableSize
	totalSize := (vtableEnd + 8 + 7) &^ 7
	vtablePos := totalSize - vtableEnd
	fakeRootPos := totalSize - fakeRootEnd
	msgObjPos := totalSize - msgObjEnd
	_ = msgObjPos
	buf := make([]byte, totalSize)
	var dw wire.DirectWriter
	dw.Init(buf, totalSize, vtablePos, t)
	m.writeDirect(&dw)
	t.WriteFakeRoot(buf, fakeRootPos, vtablePos, msgObjPos)
	t.WriteVTablesAndFooter(buf, vtablePos, fakeRootPos)
	return buf
}

// ParseReplyPromiseVectorFromReader reads a FlatBuffers vector of ReplyPromise.
func ParseReplyPromiseVectorFromReader(r *wire.Reader, slot int) []ReplyPromise {
	count, err := r.ReadVectorCount(slot)
	if err != nil || count == 0 {
		return nil
	}
	result := make([]ReplyPromise, 0, count)
	for i := 0; i < count; i++ {
		elemR, err := r.ReadVectorElementReader(slot, i)
		if err != nil {
			continue
		}
		var elem ReplyPromise
		elem.UnmarshalFromReader(elemR)
		result = append(result, elem)
	}
	return result
}
