// Code generated by fdb-wire-codegen from fdbclient/include/fdbclient/StorageServerInterface.h. DO NOT EDIT.
// FDB version: 7.3.75

package protocol

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const GetKeyRequest_FileIdentifier uint32 = 10457870

var GetKeyRequest_VTable = wire.VTable{26, 42, 12, 4, 40, 16, 20, 24, 28, 41, 32, 36, 0}

// GetKeyRequest — fdbclient/include/fdbclient/StorageServerInterface.h
type GetKeyRequest struct {
	Sel                    []byte // KeySelectorRef (slot 0)
	Version                int64  // Version (slot 1)
	Tags                   []byte // Optional<TagSet> (slot 2)
	Reply                  []byte // ReplyPromise<GetKeyReply> (slot 4)
	SpanContext            []byte // SpanContext (slot 5)
	TenantInfo             []byte // TenantInfo (slot 6)
	Options                []byte // Optional<ReadOptions> (slot 7)
	SsLatestCommitVersions []byte // VersionVector (slot 9)
}

func (m *GetKeyRequest) FileIdentifier() uint32 { return GetKeyRequest_FileIdentifier }

func (m *GetKeyRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(0) {
		m.Sel = r.ReadBytes(0)
	}
	if r.FieldPresent(1) {
		m.Version = r.ReadInt64(1)
	}
	if r.FieldPresent(4) {
		m.Reply = r.ReadBytes(4)
	}
	if r.FieldPresent(5) {
		m.SpanContext = r.ReadBytes(5)
	}
	if r.FieldPresent(6) {
		m.TenantInfo = r.ReadBytes(6)
	}
	if r.FieldPresent(9) {
		m.SsLatestCommitVersions = r.ReadBytes(9)
	}
	return nil
}

func (m *GetKeyRequest) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessage(GetKeyRequest_FileIdentifier, GetKeyRequest_VTable, 8, func(obj *wire.ObjectWriter) {
		obj.WriteBytes(int(GetKeyRequest_VTable[0+2]), m.Sel)
		obj.WriteInt64(int(GetKeyRequest_VTable[1+2]), m.Version)
		obj.WriteBytes(int(GetKeyRequest_VTable[4+2]), m.Reply)
		obj.WriteBytes(int(GetKeyRequest_VTable[5+2]), m.SpanContext)
		obj.WriteBytes(int(GetKeyRequest_VTable[6+2]), m.TenantInfo)
		obj.WriteBytes(int(GetKeyRequest_VTable[9+2]), m.SsLatestCommitVersions)
	})
}
