// Code generated by fdb-wire-codegen from fdbclient/include/fdbclient/CommitProxyInterface.h. DO NOT EDIT.
// FDB version: 7.3.75

package protocol

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const GetKeyServerLocationsReply_FileIdentifier uint32 = 10636023

var GetKeyServerLocationsReply_VTable = wire.VTable{12, 16, 4, 8, 12, 0}

// GetKeyServerLocationsReply — fdbclient/include/fdbclient/CommitProxyInterface.h
type GetKeyServerLocationsReply struct {
	Results           []byte // std::vector<std::pair<KeyRangeRef, std::vector<StorageServerInterface>>> (slot 0)
	ResultsTssMapping []byte // std::vector<std::pair<UID, StorageServerInterface>> (slot 1)
	ResultsTagMapping []byte // std::vector<std::pair<UID, Tag>> (slot 2)
}

func (m *GetKeyServerLocationsReply) FileIdentifier() uint32 {
	return GetKeyServerLocationsReply_FileIdentifier
}

func (m *GetKeyServerLocationsReply) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(0) {
		m.Results = r.ReadBytes(0)
	}
	if r.FieldPresent(1) {
		m.ResultsTssMapping = r.ReadBytes(1)
	}
	if r.FieldPresent(2) {
		m.ResultsTagMapping = r.ReadBytes(2)
	}
	return nil
}

func (m *GetKeyServerLocationsReply) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessage(GetKeyServerLocationsReply_FileIdentifier, GetKeyServerLocationsReply_VTable, 4, func(obj *wire.ObjectWriter) {
		obj.WriteBytes(int(GetKeyServerLocationsReply_VTable[0+2]), m.Results)
		obj.WriteBytes(int(GetKeyServerLocationsReply_VTable[1+2]), m.ResultsTssMapping)
		obj.WriteBytes(int(GetKeyServerLocationsReply_VTable[2+2]), m.ResultsTagMapping)
	})
}
