// Code generated by fdb-wire-codegen from fdbclient/include/fdbclient/StorageServerInterface.h. DO NOT EDIT.
// FDB version: 7.3.75

package protocol

import "github.com/birdayz/fdb-record-layer-go/pkg/fdbgo/wire"

const WatchValueRequest_FileIdentifier uint32 = 14747733

var WatchValueRequest_VTable = wire.VTable{26, 43, 12, 40, 16, 4, 41, 20, 42, 24, 28, 32, 36}

// WatchValueRequest — fdbclient/include/fdbclient/StorageServerInterface.h
type WatchValueRequest struct {
	Key         []byte // Key (slot 0)
	Value       []byte // Optional<Value> (slot 1)
	Version     int64  // Version (slot 3)
	Tags        []byte // Optional<TagSet> (slot 4)
	DebugID     []byte // Optional<UID> (slot 6)
	Reply       []byte // ReplyPromise<WatchValueReply> (slot 8)
	SpanContext []byte // SpanContext (slot 9)
	TenantInfo  []byte // TenantInfo (slot 10)
}

func (m *WatchValueRequest) FileIdentifier() uint32 { return WatchValueRequest_FileIdentifier }

func (m *WatchValueRequest) UnmarshalFDB(data []byte) error {
	r, err := wire.NewReader(data)
	if err != nil {
		return err
	}
	if r.FieldPresent(0) {
		m.Key = r.ReadBytes(0)
	}
	if r.FieldPresent(3) {
		m.Version = r.ReadInt64(3)
	}
	if r.FieldPresent(8) {
		m.Reply = r.ReadBytes(8)
	}
	if r.FieldPresent(9) {
		m.SpanContext = r.ReadBytes(9)
	}
	if r.FieldPresent(10) {
		m.TenantInfo = r.ReadBytes(10)
	}
	return nil
}

func (m *WatchValueRequest) MarshalFDB() []byte {
	w := wire.NewWriter(nil)
	return w.WriteMessage(WatchValueRequest_FileIdentifier, WatchValueRequest_VTable, 8, func(obj *wire.ObjectWriter) {
		obj.WriteBytes(int(WatchValueRequest_VTable[0+2]), m.Key)
		obj.WriteInt64(int(WatchValueRequest_VTable[3+2]), m.Version)
		obj.WriteBytes(int(WatchValueRequest_VTable[8+2]), m.Reply)
		obj.WriteBytes(int(WatchValueRequest_VTable[9+2]), m.SpanContext)
		obj.WriteBytes(int(WatchValueRequest_VTable[10+2]), m.TenantInfo)
	})
}
