load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "fuzzrun_lib",
    srcs = [
        "classify.go",
        "main.go",
        "summary.go",
    ],
    importpath = "fdb.dev/cmd/fuzzrun",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "fuzzrun",
    embed = [":fuzzrun_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "fuzzrun_test",
    srcs = [
        "classify_test.go",
        "gate_test.go",
        "runcommand_test.go",
        "summary_test.go",
    ],
    embed = [":fuzzrun_lib"],
)
