package sqldriver_test

// Eleventh axis: OPERAND COMMUTATION.
//
// `a > 5` and `5 < a` are the same predicate written two ways, so they must
// return the same rows — and, because an index may change the plan but never
// the answer, they must do so on both the indexed and the unindexed schema.
//
// This axis exists because the existing generator cannot reach it. Every
// comparison mhGen produces puts the COLUMN on the left:
//
//	g.pick(g.ints()) + " " + g.cmpOp() + " " + g.pick(mhIntLits)
//
// so `5 > a` is never generated by any sweep that uses it — and that is nine
// sweeps sharing one blind spot rather than one sweep with a gap.
//
// The blind spot sits directly over real planner machinery.
// comparisonOrientations (rule_match_intermediate.go) tries the as-written
// orientation first and then the COMMUTED one, flipping the operator through
// ComparisonType.Commute() so the literal-on-the-left form can still bind a
// placeholder and drive an index probe. A wrong flip there is not a plan
// difference, it is a WRONG ANSWER: `5 < a` matching what `a < 5` should, with
// nothing in any sweep able to see it because no sweep writes the literal
// first.
//
// The oracle is stronger than the twin alone. The twin catches a commutation
// that breaks only the INDEXED path; comparing the two spellings catches one
// that breaks BOTH paths identically, which the twin would report as agreement.
// Both are asserted here, and the absolute row set is asserted as well through
// mmTwin.Want, so three engines-wrong-the-same-way cannot satisfy it.

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"strings"
	"testing"
)

// mmcCommute flips a comparison operator so that swapping its operands
// preserves meaning: `a OP b` is equivalent to `b flip(OP) a`.
//
// Equality and inequality are their own flips; the four ordered operators pair
// up. This is the test's own table rather than a call into the engine's
// ComparisonType.Commute — an oracle that asked the code under test which
// spelling it considered equivalent would agree with itself by construction.
func mmcCommute(op string) (string, bool) {
	switch op {
	case "=":
		return "=", true
	case "<>":
		return "<>", true
	case "<":
		return ">", true
	case "<=":
		return ">=", true
	case ">":
		return "<", true
	case ">=":
		return "<=", true
	}
	return "", false
}

func TestFDB_MetamorphicOperandCommutation(t *testing.T) {
	t.Parallel()
	if clusterFilePath == "" {
		t.Skip("FDB not available (no Docker)")
	}
	ctx := context.Background()
	w := mmNewTwin(t, ctx, "/testdb_mhcommute", "mhcom",
		"CREATE TABLE t (id BIGINT, a BIGINT, b BIGINT, c DOUBLE, s STRING, f BOOLEAN, PRIMARY KEY (id)) ",
		"CREATE INDEX t_a ON t (a) CREATE INDEX t_ab ON t (a, b) "+
			"CREATE INDEX t_c ON t (c) CREATE INDEX t_s ON t (s) ")

	dataRand := rand.New(rand.NewSource(20260820))
	const nRows = 120
	var vals []string
	for i := 1; i <= nRows; i++ {
		vals = append(vals, mhRowLiteral(dataRand, i, false))
	}
	for start := 0; start < len(vals); start += 20 {
		end := start + 20
		if end > len(vals) {
			end = len(vals)
		}
		w.Exec("INSERT INTO t " + mhCols + " VALUES " + strings.Join(vals[start:end], ", "))
	}

	seed := int64(11)
	if s := os.Getenv("MHC_SEED"); s != "" {
		fmt.Sscan(s, &seed)
	}
	iters := 90
	if s := os.Getenv("MHC_ITERS"); s != "" {
		fmt.Sscan(s, &iters)
	}
	g := &mhGen{r: rand.New(rand.NewSource(seed))}

	// Three counters, because there are three ways to be green having proved
	// nothing: no pairs compared at all, no pair whose rows were non-empty, and
	// no pair whose two spellings could have differed (an operator with no flip
	// would silently compare a query with itself).
	var compared, nonEmpty, skipped int

	operands := []struct {
		name string
		col  func() string
		lit  func() string
	}{
		{"bigint", func() string { return g.pick(g.ints()) }, func() string { return g.pick(mhIntLits) }},
		{"double", func() string { return g.pick(g.dbls()) }, func() string { return g.pick(mhDblLits) }},
		{"string", func() string { return g.pick(g.strs()) }, func() string { return g.pick(mhStrLits) }},
	}

	for _, o := range operands {
		t.Run(o.name, func(t *testing.T) {
			w := w.Sub(t)
			for i := 0; i < iters; i++ {
				col, lit, op := o.col(), o.lit(), g.cmpOp()
				flipped, ok := mmcCommute(op)
				if !ok {
					t.Fatalf("the operator table has no flip for %q, so this iteration would "+
						"have compared a query with itself", op)
				}
				asWritten := fmt.Sprintf("SELECT id FROM t WHERE %s %s %s ORDER BY id", col, op, lit)
				commuted := fmt.Sprintf("SELECT id FROM t WHERE %s %s %s ORDER BY id", lit, flipped, col)

				want, err := mmRows(t, ctx, w.plain, asWritten)
				if err != nil {
					// An unsupported shape is not a finding, but the two
					// spellings must be unsupported TOGETHER — a commutation
					// that changes whether a query is ACCEPTED is a defect even
					// when no row is involved.
					if _, cerr := mmRows(t, ctx, w.plain, commuted); (cerr == nil) != (err == nil) {
						t.Errorf("commuting changed whether the query is ACCEPTED\n"+
							"  as written: %s\n  err: %v\n  commuted  : %s\n  err: %v",
							asWritten, err, commuted, cerr)
					}
					skipped++
					continue
				}
				compared++
				if len(want) > 0 {
					nonEmpty++
				}
				// Both spellings, on BOTH schemas, against the same expected
				// rows. Want() asserts the unindexed oracle, the indexed answer
				// and their agreement, so a commutation that breaks only the
				// index path and one that breaks both are separated.
				w.Want("as written: "+col+" "+op+" "+lit, asWritten, want)
				w.Want("commuted: "+lit+" "+flipped+" "+col, commuted, want)
			}
		})
	}

	// Measured on this fixture at 90 iterations x 3 operand types the compared
	// count sits near 270; the floor is well below that so ordinary generator
	// drift does not trip it while a collapse does.
	if compared < 150 {
		t.Fatalf("only %d commutation pairs were compared (%d unsupported and skipped) — "+
			"below this floor the axis is not exercising the engine", compared, skipped)
	}
	if nonEmpty < 80 {
		t.Fatalf("only %d of %d compared pairs had a NON-EMPTY expected row set. An empty "+
			"result matches an empty result whichever way the operands were written, so below "+
			"this floor the sweep is comparing absences", nonEmpty, compared)
	}
	t.Logf("commutation sweep: %d pairs compared (%d with non-empty rows), %d skipped",
		compared, nonEmpty, skipped)
}
