package executor

import (
	"testing"

	"fdb.dev/pkg/recordlayer/query/plan/cascades/expressions"
	"fdb.dev/pkg/recordlayer/query/plan/cascades/values"
)

// The aggregate cursor's emitted row is addressed by SLOT. Its column names are
// a display label and cannot be its identity (RFC-197 item 5).
//
// This is a NEGATIVE result made permanent, and the negative is the whole point.
// It was established by mutation: replacing every name finalizeGroup emits with
// `$PROBEn` leaves all twenty targets of //pkg/relational/... green, and reds
// only executor unit tests that assert on the emitted map keys. Nothing in
// production reads those names — so the "naming contract with the executor" the
// group-by output authorities are documented as serving is, on the executor
// side, already an ordinal one.
//
// A whole-suite mutation is not a test, so what is pinned here is the property
// that makes it true: two grouping keys with the SAME display name occupy two
// independently addressable slots, and the emitted labels collide. Anything that
// re-keys this row by name — a map, a name lookup, a dedup — loses one of them
// and fails here. That is what would re-arm the conflation.
//
// Java reaches the same place by not naming the columns at all:
// GroupByExpression.nestedResults composes the output row from Column.unnamedOf
// (GroupByExpression.java:754,758), and the `_0`/`_1` labels that appear
// downstream are synthesized from position by Type.Record.normalizeFields and
// explicitly classified as throwaway by Field.isAutoGenerated
// (Type.java:2651,2922-2923).
func TestAggregateCursor_OutputRowIdentityIsTheSlotNotTheName(t *testing.T) {
	t.Parallel()

	// Two sources, each with a column named X — the collision shape. The keys
	// read slots 0 and 1 of a flat input row; both render their display name as
	// the bare leaf X (expressions.AggregateKeyColumnName).
	rowType := values.NewRecordType("", false, []values.Field{
		{Name: "X", FieldType: values.NullableLong, Ordinal: 0},
		{Name: "Y", FieldType: values.NullableLong, Ordinal: 1},
	})
	qov := values.NewQuantifiedObjectValueOfType(values.NamedCorrelationIdentifier("T"), rowType)
	keyA, err := values.NewFieldValueOfOrdinal(qov, 0)
	if err != nil {
		t.Fatalf("NewFieldValueOfOrdinal(0): %v", err)
	}
	// The second key reads slot 1 but RENDERS as X too — the display-name
	// collision the contract has to survive, expressed without needing a join.
	// The executor sees two keys and one name.
	keyB := values.NewFieldValueWithResolvedOrdinal("X", 1, values.NullableLong)

	c := &aggregateCursor{
		groupingKeys: []values.Value{keyA, keyB},
		aggregates: []expressions.AggregateSpec{
			{Function: expressions.AggCount},
		},
	}
	c.currentKeyVals = []any{int64(7), int64(99)}
	c.current = c.newGroupState()
	c.current.count = 3

	out := c.finalizeGroup()
	if out.Positional == nil {
		t.Fatal("finalizeGroup emitted no positional row")
	}

	// Identity: each key reaches its OWN slot, even though the two share a name.
	slot0, ok0 := out.Positional.Get(0)
	slot1, ok1 := out.Positional.Get(1)
	if !ok0 || !ok1 {
		t.Fatalf("slots 0/1 not addressable: %+v", out.Positional)
	}
	if slot0 != int64(7) || slot1 != int64(99) {
		t.Errorf("group-key slots = (%v, %v), want (7, 99) — the two same-named keys "+
			"must stay independently addressable BY ORDINAL; if they collapsed, "+
			"something re-keyed this row by its display name", slot0, slot1)
	}
	if n, ok := out.Positional.Get(2); !ok || n != int64(3) {
		t.Errorf("aggregate slot = %v (ok=%v), want 3 — the aggregate follows the "+
			"grouping keys in ordinal order", n, ok)
	}

	// Display: the collision is still THERE, and must be. Ordinalizing the
	// binding does not rename what the user sees; Java carries the label as a
	// separate, optional identifier for exactly this reason
	// (Expression.java:72, Expressions.java:251-253).
	if got := len(out.Positional.Type.Fields); got != 3 {
		t.Fatalf("emitted %d fields, want 3", got)
	}
	if a, b := out.Positional.Type.Fields[0].Name, out.Positional.Type.Fields[1].Name; a != "X" || b != "X" {
		t.Errorf("emitted labels = (%q, %q), want both X — the display name is the "+
			"user's and stays colliding; only the BINDING is a slot", a, b)
	}
}
